const GUIDE_LIST = [
    [
        {cate_no:0, item_no:1, title:'Greetings', sub_title:'생명불 켜는 ON Hospital이 함께합니다', img_src:['doctor01.png', 'doctor02.png', 'doctor03.png'], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
        {cate_no:0, item_no:2, title:'History', sub_title:'History test', img_src:[''], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
        {cate_no:0, item_no:3, title:'Mission & Vision', sub_title:'Mission & Vision test', img_src:[''], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
        {cate_no:0, item_no:4, title:'Floor Guide', sub_title:'Floor Guide test', img_src:[''], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
        {cate_no:0, item_no:5, title:'Maps & Direction', sub_title:'Maps & Direction test', img_src:[''], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
        {cate_no:0, item_no:6, title:'Contact No.', sub_title:'Contact No. test', img_src:[''], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
        {cate_no:0, item_no:7, title:'Customer Service Center', sub_title:'Customer Service Center test', img_src:[''], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
        {cate_no:0, item_no:8, title:'Emergency Center', sub_title:'Emergency Center test', img_src:[''], context:['', ], cont_name: ['']},
        {cate_no:0, item_no:9, title:'편의시설안내', sub_title:'편의시설안내 test', img_src:[''], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
        {cate_no:0, item_no:10, title:'Funeral Home/Mortuary', sub_title:'Funeral Home/Mortuary test', img_src:[''], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
    ]
]