const GUIDE_LIST = [
    [
        {cate_no:0, item_no:1, title:'인사말', sub_title:'생명불 켜는 온종합병원이 함께합니다', img_src:['doctor01.png', 'doctor02.png', 'doctor03.png'], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
        {cate_no:0, item_no:2, title:'연혁', sub_title:'연혁 test', img_src:[''], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
        {cate_no:0, item_no:3, title:'미션/비전', sub_title:'미션/비전 test', img_src:[''], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
        {cate_no:0, item_no:4, title:'층별안내', sub_title:'층별안내 test', img_src:[''], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
        {cate_no:0, item_no:5, title:'오시는길', sub_title:'오시는길 test', img_src:[''], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
        {cate_no:0, item_no:6, title:'전화번호', sub_title:'전화번호 test', img_src:[''], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
        {cate_no:0, item_no:7, title:'고객지원센터', sub_title:'고객지원센터 test', img_src:[''], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
        {cate_no:0, item_no:8, title:'응급의료센터', sub_title:'응급의료센터 test', img_src:[''], context:['', ], cont_name: ['']},
        {cate_no:0, item_no:9, title:'편의시설안내', sub_title:'편의시설안내 test', img_src:[''], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
        {cate_no:0, item_no:10, title:'장례식장', sub_title:'장례식장 test', img_src:[''], context:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam inventore voluptatibus ducimus est corrupti molestias reprehenderit veritatis consectetur sit nostrum dicta nam, nisi et. Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', 'Aperiam voluptas nisi excepturi nulla ipsa.', ], cont_name: ['test1', 'test2', 'test3']},
    ]
]