const NEWS_DETAIL = [
    // Announcements
    [
        {cate_no:0, 
            item_no:1, 
            title:'[Recruitment] Hospice Volunteer Seminar & Certification Course', 
            date:['2023,03,16','(13:26:01)'], 
            date2:['23.03.16','(13:26:01)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            const:[''],
            red:[''],
            img_src:'notice/호스피스_자원봉사자_세미나_자격증과정.png'
        },
        {cate_no:0, 
            item_no:2, 
            title:'[Closed notice] March 1st holiday notice', 
            date:['2023,02,23','(09:41:05)'], 
            date2:['23.02.23','(09:41:05)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            const:[''],
            red:[''],
            img_src:'notice/삼일절_휴진_안내.jpg'},
        {cate_no:0, 
            item_no:3, 
            title:'[Treatment Information] January 2023 Treatment Schedule Guide (Lunar New Year Holidays)', 
            date:['2023,01,05','(09:53:38)'], 
            date2:['23.01.05','(09:53:38)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            const:['| Closed on January 21-23, 2023, substitute holiday on the 24th, only AM treatment is available, so please check the schedule.',],
            red:'',
            img_src:'notice/설연휴_2023년_1월.jpg'},
        // {cate_no:0, 
        //     item_no:4, 
        //     title:'[진료 안내] 10월 진료 일정 안내(2022년 개천절, 한글날)', 
        //     date:['2022,09,16','(11:17:32)'], 
        //     date2:['22.09.16','(11:17:32)'], 
        //     writer:'ON Group Medical Foundation ON Hospital', 
        //     const:['| 10월 3일(월) 개천절은 휴진, 10월 10일(월) 한글날은 AM 진료만 진행하오니 진료에 착오 없으시길 바랍니다.',],
        //     red:['ON Hospital Emergency Center는 365일 24시간 언제든 이용 가능합니다.'],
        //     img_src:'notice/2022년_10월_휴진_안내.jpg'},
        // {cate_no:0, 
        //     item_no:5, 
        //     title:'[진료 안내] 6월 진료 일정 안내(2022년 지방선거, 현충일)', 
        //     date:['2022,05,27','(19:00:32)'], 
        //     date2:['22.05.27','(19:00:32)'], 
        //     writer:'ON Hospital', 
        //     const:['| 6월 1일(수), 6월 6일(월) 2022년 지방선거, 현충일은 AM 진료만 진행하니 진료에 착오 없으시길 바랍니다.',],
        //     red:[''],
        //     img_src:'notice/2022년_6월_휴진안내.jpg'},
        // {cate_no:0, 
        //     item_no:6, 
        //     title:'[휴진 안내] 어린이날 휴진 안내', 
        //     date:['2022,05,27','(19:00:15)'], 
        //     date2:['22.05.27','(19:00:15)'], 
        //     writer:'ON Hospital', 
        //     const:['| 5월 5일(목) 어린이날은휴진하오니 진료에 착오 없으시길 바랍니다.', '| '],
        //     red:[''],
        //     img_src:''},
        // {cate_no:0, 
        //     item_no:7, 
        //     title:'[휴진 안내] 설연휴 휴진 안내', 
        //     date:['2022,05,27','(19:00:02)'], 
        //     date2:['22.05.27','(19:00:02)'], 
        //     writer:'ON Hospital', 
        //     const:['| 1월 31일(월)~2월 2일(수) 설연휴는 휴진하오니 진료에 착오 없으시길 바랍니다.', '| ',],
        //     red:[''],
        //     img_src:''},
        // {cate_no:0, 
        //     item_no:8, 
        //     title:'[휴진 안내] 성탄절 및 신정 휴진 안내', 
        //     date:['2022,05,27','(18:59:50)'], 
        //     date2:['22.05.27','(18:59:50)'], 
        //     writer:'ON Hospital', 
        //     const:['| 12월 25일(토) 성탄절, 1월 1일(토) 신정휴진하오니 진료에 착오 없으시길 바랍니다.', ],
        //     red:[''],
        //     img_src:''},
        // {cate_no:0, 
        //     item_no:9, 
        //     title:'[Medical Information] 한글날 진료 안내', 
        //     date:['2022,05,27','(18:57:08)'], 
        //     date2:['22.05.27','(18:57:08)'], 
        //     writer:'ON Hospital', 
        //     const:['| 10월 9일(금) 한글날은 AM진료(09:00 ~ 13:00)하오니 진료에 착오 없으시길 바랍니다.'],
        //     red:[''],
        //     img_src:''},
        // {cate_no:0, 
        //     item_no:10, 
        //     title:'[휴진 안내] 추석 휴진 안내', 
        //     date:['2022,05,27','(18:59:21)'], 
        //     date2:['22.05.27','(18:59:21)'], 
        //     writer:'ON Hospital', 
        //     const:[''],
        //     red:[''],
        //     img_src:''},
    ],
    // More News
    [
        {cate_no:1, 
            item_no:1, 
            title:'This is ONN card news for February.', 
            date:['2023.02.27','(15:59:31)'], 
            date2:['23.02.27','(15:59:31)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            const:[''], 
            img_src:'ext/2023년_2월_카드뉴스.jpg'
        },
        {cate_no:1, 
            item_no:2, 
            title:'This is the news of the dispatch of emergency medical volunteers to Turkey after the Great Earthquake in Turkey..', 
            date:['2023.02.20','(12:09:39)'], 
            date2:['23.02.20','(12:09:39)'], 
            writer:'ON Group Medical Foundation ON Hospital',
            img_src:'ext/튀르키예_대지진_대한민국_긴급의료봉사단_파견소식.png'
        },
        {cate_no:1, 
            item_no:3, 
            title:'This is ONN card news for January.', 
            date:['2023.01.26','(15:55:09)'], 
            date2:['23.01.26','(15:55:09)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            const:[''], 
            img_src:'ext/2023년_1월_카드뉴스.jpg'
        },
        // {cate_no:1, 
        //     item_no:4, 
        //     title:'호스피스 자원봉사자 교육 및 실습과정 수강 신청', 
        //     date:['2022.05.27','(18:53:37)'], 
        //     date2:['22.05.27','(18:53:37)'], 
        //     writer:'ON Hospital', 
        //     const:[''], 
        //     img_src:'ext/호스피스_자원봉사자_교육_실습_수강모집.jpg'
        // },
    ],
    // News & Publications
    [
        {cate_no:2, 
            item_no:10, 
            title:'Busan ON Hospital "Sudden deafness and tinnitus should be actively treated rather than neglected"', 
            date:['2023.04.03','(17:33:44)'], 
            date2:['23.04.03','(17:33:44)'], 
            writer:'ON Group Medical Foundation ON Hospital',
            top_small:'',
            img_text:['Lee Il-woo, chief of OTOLARYNGOLOGY at ON Hospital in Busan, is treating patients. (Provided by Busan ON Hospital)'],
            top_bold:['검사 거쳐야 정확한 진단 가능', '이 과장"이명 원인 질환 제거 중요"'],
            top_content:'',
            center_con:[
                'Recently, an increasing number of people complain of tinnitus and sudden hearing loss, but many of them ignore the symptoms and neglect them.',
                'In particular, more and more young people complain of symptoms compared to the past, and if the symptoms get worse, it can worsen to a condition where it is difficult to restore hearing, so attention is needed.',
                'Hearing loss, which is a representative disease of the ear, refers to a condition in which hearing is reduced or lost.',
                'Hearing loss can be largely divided into conductive hearing loss and sensorineural hearing loss, but it is difficult for patients to accurately distinguish their own hearing loss. Diagnosis is made through examinations such as medical history and hearing tests, and treatment varies depending on the type of hearing loss.',
                'Sudden hearing loss is sensorineural hearing loss that has occurred within 3 days of hearing loss of 30 dB or more in 3 or more consecutive frequencies in pure tone audiometry.',
                'It is sometimes accompanied by ringing in the ears (tinnitus), a feeling of fullness in the ears (ear fullness), or dizziness. In most cases, no specific cause can be found, but the prognosis is good with early detection and appropriate treatment.',
                'Lee Il-woo, director of OTOLARYNGOLOGY at ON Hospital in Busan, said, “1/3 of patients with sudden hearing loss regain normal hearing, but the remaining 1/3 partially recovers but loses hearing, and the remaining 1/3 completely loses hearing.” It is necessary to conduct appropriate symptomatic treatment, check the patient`s condition well, and actively treat it.”',
                'Tinnitus is a state in which you feel that you hear a sound in the absence of an external auditory stimulus. If you listen to the history and remove the cause, the symptoms will improve. In very rare cases, tinnitus may occur due to an auditory nerve tumor or cerebellar pontine tumor.',
                'Manager Lee Il-woo emphasized, “The cause of tinnitus is unclear, so there are few people who persistently go to the hospital.”.'
            ],
            editor:'Reporter Ahn Do-il doit0805@getnews.co.kr',
            sources:'Source: Global Economic Daily (https://www.getnews.co.kr/news<span>/articleView.html?idxno=621452)</span>' ,
            a_link:'https://www.getnews.co.kr/news/articleView.html?idxno=621452',
            img_src:'media/돌발성_난청_이명.jpg'},
        {cate_no:2, 
            item_no:9, 
            title:'Busan ON Hospital provides pansy flower sea squirt bibimbap to hospice patients and their families', 
            date:['2023,03,24','(11:47:57)'], 
            date2:['23.03.24','(11:47:57)'], 
            writer:'ON Group Medical Foundation ON Hospital',
            top_small:'',
            img_text:['Pansy flower sea squirt bibimbap. Photo = ON Hospital'], 
            top_bold:[''],
            top_content:'Busan ON Hospital (Director Kim Dong-heon) announced on the 21st that it cooked pansy flower sea squirt bibimbap and served it as a meal to Hospice & Palliative Care patients and their families.',
            center_con:[
                'The hospice ward of ON Hospital prepares and serves various dishes once a week for inpatient patients and their guardians. The pansy flower sea squirt bibimbap was hosted by the hospice ward of ON Hospital, and was provided to patients and their guardians through the hands of the hospice ward staff.',
                'Guardian Choi, who was served a meal, said, “It was sad to be alone in the hospital room without being able to see the flowers even though spring came. Thank you for providing such food of love,” she said.',
                'The hospice social worker who planned the event said, “It would be great if patients and their caregivers could gain strength and comfort to fight diseases through a cooking event delivered with love and sincerity.',
                'Kim Dong-heon, director of the hospital, said, "We will work harder and support the hospice ward patients and their families so that they can receive comfort and lead meaningful lives every day.'
            ],
            editor:'Reporter Jeongheon Park, Busan/Gyeongnam, ilyo33@ilyo.co.kr',
            sources:'Source: Sunday Newspaper (https://ilyo.co.kr/?ac=<span>article_view&entry_id=449016)</span>' ,
            a_link:'https://ilyo.co.kr/?ac=article_view&entry_id=449016',
            img_src:'media/호스피스환자_가족에_팬지꽃_멍게_비빔밥.png'},
        {cate_no:2, 
            item_no:8, 
            title:'A Korean doctor who suffered a cerebral hemorrhage while volunteering in Turkey...Treats victims of victims to the end', 
            date:['2023,03,24','(09:28:37)'], 
            date2:['23.03.24','(09:28:37)'], 
            writer:'ON Group Medical Foundation ON Hospital',
            top_small:'',
            img_text:['Oh Moo-young, director of the Respiratory Allergy Center at ON Hospital, is doing medical volunteer work in Turkey. Courtesy of ON Hospital'], 
            top_bold:[
                'Need to differentiate between disease and treatment depending on symptoms', 
                'Spinal stenosis, pain relief when bending over', 
                'Exercises that reduce back strain, such as swimming and walking, help'
            ],
            top_content:'',
            center_con:[
                'A Korean doctor in his 70s who went to Turkiye for medical service completed the service despite symptoms of a brain hemorrhage.',
                'According to the Green Doctors Foundation, an international medical volunteer organization, on the 20th, Oh Moo-young, director of the Respiratory Allergy Center at ON Hospital, suffered a cerebral hemorrhage while performing emergency medical volunteer activities at the site of the Great Turkiye Earthquake, such as Antakya, on the 17th and 24th of last month.',
                'Kim Seok-kwon, head of ON Hospital PLASTIC SURGERY CENTER, appeared on ON Group`s medical channel ONN Doctor TV on the 17th and explained the situation at the time.',
                'In response to the moderator`s question, "Is it true that a doctor was injured during the service?", Center Director Kim said, "Center Oh, who had been using the same room for the fifth day of volunteering, complained that he took painkillers for a headache, but far from subsiding, it was accompanied by dizziness. I suspected a cerebral hemorrhage or cerebral infarction.',
                'According to Center Director Kim, Center Director Oh tried to get treatment at a local hospital, but his symptoms improved, so he gave up hospitalization and completed his volunteering schedule as scheduled.',
                'Upon returning home, director Oh immediately underwent surgery after examining the patient and confirming that he had a large amount of blood in his brain. He is expected to return to the medical field soon.',
                'Center Director Oh, a specialist in PEDIATRICS, mainly took care of children and teenagers suffering from skin diseases or digestive system diseases at the earthquake volunteer site in Turkiye. Center director Oh said that as a family from South Vietnam, he participated in the volunteer service because he had a strong desire to repay Turkiye, who shed blood to protect our country`s freedom in the Korean War long ago.',
                'Jeong-geun, chairman of the Green Doctors Foundation, said, “Director Oh, who has a spirit of volunteerism, did not inform his colleagues about his illness. At the end of the (volunteer schedule), all 15 crew members who knew this were anxiously taking care of the victims throughout the rest of the schedule. It is enough to become an example for many people, regardless of nationality or religion.'
            ],
            editor:'Reporter Hyewon Lee hyewon@donga.com',
            sources:'Source: Donga.com(https://www.donga.com/news/<span>Society/article/all/20230320/118435491/2)</span>',
            a_link:'https://www.donga.com/news/Society/article/all/20230320/118435491/2',
            img_src:'media/튀르키예_의료지원_절실_2.jpg'},
        // {cate_no:2, 
        //     item_no:7, 
        //     title:'94세 간암·40세 췌장암 치료…ON Hospital 수술 명가 우뚝', 
        //     date:['2023,03,15','(14:07:58)'], 
        //     date2:['23.03.15','(14:07:58)'], 
        //     writer:'ON Group Medical Foundation ON Hospital',
        //     top_small:'Department of Hepatobiliary and Pancreatic Surgery 전문의들로 구성된 ON Hospital ‘하이테크서저리 팀’이 94세 간암환자와 4기 췌장암환자 등에 대한 고난도 수술을 잇따라 성공해 관심을 모은다. ON Hospital은 이를 바탕으로 암 중점치료 및 필수의료를 집중 보강해 대학병원과의 경쟁에 나선다.',
        //     img_text:['ON Hospital은 ‘하이테크서저리 팀’의 축적된 고난도 수술 성과를 바탕으로 올해 생체 간이식 분야로 그 영역을 넓힌다.', '  또한 암 중점 치료 및 필수의료 분야 등을 집중 보강해 대학병원과의 경쟁에 나선다.', '하이테크서저리 팀의 박광민 팀장(오른쪽·의무원장)과 Professor Park Yo-han가 병실에서 환자를 살펴보고 있다.'], 
        //     top_bold:['- 올해 생체 간이식까지 영역 넓혀', '- 최신 PET-CT 부울경서 첫 도입', '- DEPARTMENT OF NEUROSURGERY 전문의 등도 다수 초빙'],
        //     top_content:'',
        //     center_con:[
        //         'ON Hospital 하이테크서저리 팀은 지난달 간암환자 A(94) 씨의 수술에 성공했다고 13일 밝혔다. 그는 간 절제술을 받은 환자 중 최고령자로 알려졌다. 당초 A 씨는 간 CT와 PET-CT(양전자단층촬영) 검사에서 지름 8㎝의 간암세포가 발견됐다. 병원 측은 A 씨가 고령이라 수술을 꺼렸지만 심폐기능이 양호한 데다 그대로 방치할 경우 말기암의 극심한 통증 등을 고려해 수술에 들어갔다. 수술 후 한 달째인 된 A 씨는 일반 병실에서 별다른 통증 없이 생활하고 있다.',
        //         '이 팀은 간 전이와 상장간막 정맥 침범이 의심되는 4기 췌장암환자 B(여·40) 씨의 수술에도 성공했다. ‘SURGERY수술의 꽃’으로 불리는 췌두부십이지장 절제술(휘플 수술)과 간절제술을 동시 시행해 그의 암세포를 완전히 절제해낸 것이다. B 씨는 향후 진행된 항암치료를 통해 장기 생존이 기대되고 있다.',
        //         '박광민 하이테크서저리 팀장(전 서울아산병원 Department of Hepatobiliary and Pancreatic Surgery 주임교수)은 “간문맥과 상장간막 정맥에 침윤이 의심되는 췌장암 4기 환자는 우선 항암치료로 암 크기를 줄여야 수술이 가능하다. 그런데 암의 크기가 실제 줄어드는 것은 30∼40%에 불과하고, 그마저도 항암치료 과정에서의 염증반응으로 암이 주변 조직과 심하게 유착되므로 SURGERY의사들이 복부를 절제하고도 수술을 포기하는 경우가 태반이다”고 지적했다. 박 팀장은 “그럼에도 불구하고 췌장암 4기 같은 고난도 암환자들은 가능한 빨리 절제수술 후 항암치료를 받는 것이 치료효과를 높일 수 있다. 따라서 SURGERY의사들의 적극적인 자세가 중요하다”고 강조했다. 그러면서 B 씨의 이번 수술이 간 전이된 4기 췌장암환자에 대한 획기적인 치료법으로 고려될 수 있을 것으로 내다봤다.',
        //         '병원 측에 따르면 하이테크서저리 팀은 2020년 3월부터 현재까지 500여 건의 암수술 중에서 20여 건의 초고난도 암수술에 성공했다. 여기에다 올해는 생체 간이식 수술로 영역을 넓힌다. 이를 위해 서울아산병원에서 1000건 이상 간이식 수술을 집도했던 박광민 교수를 필두로 박요한(전 부산백병원 간이식센터) 교수, 문기명(전 양산부산대병원 간이식센터) 교수, 췌담도SURGERY Lee Sang-yeop, Head of Hepatobiliary and Pancreatic Surgery Dept 등이 손발을 맞춰왔다. 최근에는 감염내과·DEPARTMENT OF <SPAN>RESPIRATORY MEDICINE</SPAN> 중견 교수들을 영입해 완벽한 간이식 수술을 준비하고 있다.',
        //         'ON Hospital은 또 하이테크서저리 팀의 수술 활성화를 위해 부산 울산 경남 최초로 ‘디지털 PET-CT’를 도입해 각종 미세 암에 대한 조기 진단도 가능해졌다. 이 장비는 암 진단뿐만 아니라 피킨슨병과 사경 치매 등의 조기 진단에도 상당히 효과적이어서 해당 치료에 큰 도움을 줄 전망이다.',
        //         'ON Hospital 김동헌 병원장(전 부산대병원장·SURGERY 전문의)은 “올 들어 뇌수술과 뇌혈관중재술이 가능한 DEPARTMENT OF NEUROSURGERY 전문의들도 다수 확보해 응급 필수의료 대응력을 높였다. 아울러 음압실 10개, 중환자실 36병상을 포함해 총 720병상 규모로 확충함으로써 개원 13주년인 ON Hospital이 대학병원과 어깨를 나란히 할 수 있는 수준으로 성장했다”고 강조했다. 김 병원장은 또한 필수의료 서비스 강화와 감염병 대처에 앞장섬으로써 부산 지역 허브병원으로서의 역할을 다하겠다고 다짐했다.'
        //     ],
        //     editor:'구시영 선임기자 ksyoung@kookje.co.kr',
        //     sources:'출처: 국제신문(http://www.kookje.co.kr/news2011/asp/newsbody.asp?code=0700&key=20230314.22017003699)' ,
        //     a_link:'http://www.kookje.co.kr/news2011/asp/newsbody.asp?code=0700&key=20230314.22017003699',
        //     img_src:'media/94세_간암_췌장암치료_수술명가.jpg',
        //     img_src_2:'media/94세_간암_췌장암치료_수술명가_2.jpg',
        // },
        // {cate_no:2, 
        //     item_no:6, 
        //     title:'ON Hospital, 올바른 틀니 최초 사용법 안내', 
        //     date:['2023,03,14','(11:10:43)'], 
        //     date2:['23.03.14','(11:10:43)'], 
        //     writer:'ON Group Medical Foundation ON Hospital',
        //     top_small:'‘이가 없으면 잇몸으로 산다’는 속담이 있다. 있던 것이 없어지면 불편하더라도 없는 대로 참고 살아간다는 말이다. 하지만 실제로 이가 없이 잇몸으로 살기란 쉽지 않다. 생존에 필수인 음식 섭취에 직접 관여하는 치아가 없거나 부실해서 제대로 음식을 씹기 힘들다면 우리 몸의 여러 기능에 이상이 생긴다.',
        //     img_text:'부산 ON Hospital DENTISTRY 이의정 과장(DENTISTRY 전문의). 사진=ON Hospital 제공', 
        //     top_bold:['경제적 장점으로 많이 사용...첫 착용이라면 올바른 관리법 중요'],
        //     top_content:'',
        //     center_con:[
        //         '치아가 없어서 음식을 제대로 씹지 못하면 침이 분비되지 않고 잘게 쪼개지지 않은 음식물이 위장에 많은 부담을 줘 소화불량, 영양 불균형을 초래하기 쉽다. 일본의 한 연구팀에 의하면 치아가 인지기능에도 영향을 미친다고 밝혀졌다. 70대 이상 노인 1167명을 조사했더니, 인지기능이 정상인 그룹의 치아 개수는 14.9개인 반면 치매환자의 경우 치아 개수가 9.4개였다. 음식물을 씹는 저작행위가 뇌의 인지기능에도 영향을 미치는 것으로 추정된다.',
        //         '이렇게 중요한 역할과 기능을 하는 ‘치아’가 손실되면 치아의 역할을 대체해줄 수 있는 대체제인 틀니나 임플란트 치료를 해야 한다. 틀니와 임플란트 각자 장단점이 있어 환자의 상태에 따라 진행되는데 많은 사람들이 경제적인 장점이 있어 틀니를 사용한다.',
        //         '‘틀니’란 치아와 잇몸이 상실되었을 때 저작을 하고 심미적인 결손을 회복하기 위해 입안에 넣어 끼웠다 뺐다 하는 DENTISTRY 보철물이다. 틀니는 치아가 결손된 경우 음식을 씹을 수 있게 해주는 기능과 발음을 제대로 할 수 있게 해주고 치아 결손으로 인해 말려 들어간 입술을 다시 원위치로 잡아주어 얼굴의 형태를 유지해주는 등 매우 중요하다. 때문에 틀니를 올바르게 사용하고 관리하는 법을 알아둬야 한다.',
        //         '부산 ON Hospital DENTISTRY 이의정 과장(DENTISTRY 전문의)은 “틀니를 사용하는 것보다도 사용 후 관리를 어떻게 하는지가 중요하다”며 “처음 틀니를 접하는 많은 분들이 틀니의 불편함을 호소하는데, 틀니를 사용함에 있어 6개월에 한 번씩 DENTISTRY에 내원해 불편한 부분이 없는지 확인하여야 한다”고 설명했다.',
        //         '거동이 힘들거나 병원을 내원하기 힘든 분들의 경우 틀니 부착을 도와주는 크림 타입의 부착재를 사용할 수 있다. 하루 동안 착용한 후 씻어내면 되는 일회성 제품으로 유지력이 생겨 틀니와 입천장 사이에 음식물이 끼는 것도 방지할 수 있고 저작기능에도 큰 도움이 된다. 그러나 장기적으로 봤을 때 해결책으로 보긴 어렵다.',
        //         '틀니를 세척하기 위해 일반 치약을 사용하거나 끓는 물에 삶는 경우가 종종 있는데 이는 절대 금해야 한다. 치약에는 연마제 성분이 있어 틀니에 미세한 흡집이 생기고 마모가 나타나 틀니가 잘 맞지 않을 수 있고 미세한 틈에 세균이 번식할 수도 있기 때문이다. 가열을 하면 틀니의 모양이 변형될 수도 있기 때문이다.',
        //         '이의정 과장(DENTISTRY 전문의)은 “특히 밤에 깜빡하고 틀니를 끼운 상태로 주무시는 경우가 많은데, 이는 세균의 번식이 증가하고 잇몸 조직이 가라앉는 속도가 빨라져 절대 금한다”며 “틀니 세척의 경우 주방세제나 틀니 전용 솔을 사용하거나 약국에서 구매할 수 있는 틀니용 세정제를 사용하고 물컵에 담가놓는 것이 좋다”고 강조했다.'
        //     ],
        //     editor:'박정헌 부산/경남 기자 ilyo33@ilyo.co.kr',
        //     sources:'출처: 일요신문(https://ilyo.co.kr/?ac=article_view&entry_id=448537)' ,
        //     a_link:'https://ilyo.co.kr/?ac=article_view&entry_id=448537',
        //     img_src:'media/올바른_틀니_최초_사용법.png'
        // },
        // {cate_no:2, 
        //     item_no:5, 
        //     title:'부산 ON Hospital “백내장, 노안으로 생각해 방치 시 회복 어려워”', 
        //     date:['2023,03,08','(15:07:53)'], 
        //     date2:['23.03.08','(15:07:53)'], 
        //     writer:'ON Group Medical Foundation ON Hospital',
        //     top_small:'',
        //     img_text:'장영준 안과 과장 진료 모습. (제공: 부산 ON Hospital)', 
        //     top_bold:['최근 젊은 층 전자기기 사용 등으로 노안 증가', '“환자마다 상태 다 달라 수술 전 상담 필요”'],
        //     top_content:'',
        //     center_con:[
        //         '과거에는 60대 이상 연령층에서 노안 증상을 많이 호소했었으나 최근에는 심한 스트레스와 스마트폰, TV, 컴퓨터 등의 과다 사용 등 눈이 혹사당하며 30대 이하의 나이에서도 노안이 발생하는 경우가 증가하고 있다.',
        //         '눈에 발생하는 질환들은 초기에 특별한 이상 증상이 없어 시간이 어느 정도 흘러 증상의 중기 이상에 발견되는 경우가 많다.',
        //         '백내장도 노안과 마찬가지로 노화 현상으로 나타나는데 수정체의 노화로 인해 하얗게 혼탁해지는 현상이다. 눈으로 들어온 빛을 망막까지 제대로 전달하지 못하고 이로 인해 시력이 감소하는 증상이 나타난다. 75세 이상의 상당수 노인층에서 발병하는 흔한 질환인데 최근 50세 이상에서도 자주 보이고 있다.',
        //         '백내장은 단순히 노안이라 생각해 방치할 경우 치료를 해도 추후 정상적인 시력 회복에 장애가 될 수 있어 적기에 치료가 필요하다.',
        //         '장영준 부산 ON Hospital 안과 과장은 “노안과 백내장은 비슷한 증상을 보이지만 치료법이 달라 구분이 필요하다”며 “증상의 종류와 정도에 따라 비수술·수술 요법으로 교정이 가능하다”고 설명했다.',
        //         '단순 노안의 경우에는 비수술적 교정방법으로 다초점 안경과 다초점 렌즈 등을 사용해 시력 교정을 할 수 있다. 수술적 교정으로는 각막을 레이저로 절삭하는 시력 교정술을 한다.',
        //         '백내장은 진행 속도를 더디게 하는 점안약을 사용하는 약물 치료, 혼탁해진 수정체를 제거하고 인공수정체를 삽입하는 수술로 치료해야 한다.',
        //         '하지만 노안과 백내장을 동시에 앓고 있다면 치료법이 달라진다. 일반적으로 백내장 수술만 한다면 수정체를 제거하고 인공수정체를 삽입한다.',
        //         '노안과 백내장이 동시에 있다면 삽입하는 인공수정체를 조절이 가능한 다초점 인공수정체를 삽입해 수술한다. 현재 단순 노안만 있다면 백내장 수술은 굳이 고려하지 않아도 된다.',
        //         '장영준 과장은 “다초점 인공수정체를 결정할 때 환자 개인의 눈 상태와 생활에 근거해 적절한 인공수정체 종류를 정하는 것이 가장 중요하다”며 “수술 전 안과 전문의와의 충분한 상담이 필요하다”고 강조했다.',
        //         '오랜 시간 눈을 사용했다면 충분한 휴식을 취해주고 의식적으로 눈을 자주 깜빡여주는 것이 도움 된다. 실내 적정 습도를 유지하고 운전이나 야외활동 중에는 선글라스를 착용해 자외선을 차단하는 것이 좋다.',
        //         '장 과장은 “이러한 교정술을 시행한 후 부작용으로 눈물 흘림, 눈부심 증상, 야간 빛 번짐 증상 등이 있을 수 있으나 시간이 지나면서 줄어든다”며 “환자마다 상태가 다 달라 수술 전 전문의와 충분한 상담을 통해 부작용에 대해 설명 듣는 것이 필요하다”고 말했다.'
        //     ],
        //     editor:'안도일 기자 doit0805@getnews.co.kr',
        //     sources:'출처 : 글로벌경제신문(https://www.getnews.co.kr/news/articleView.html?idxno=619143)' ,
        //     a_link:'https://www.getnews.co.kr/news/articleView.html?idxno=619143',
        //     img_src:'media/백내장_노안_방치.jpg'
        // },
        // {cate_no:2, 
        //     item_no:4, 
        //     title:'온라이프상조, `이색`펫-헬스케어 상품 출시', 
        //     date:['2023,02,08','(15:21:07)'], 
        //     date2:['23.02.08','(15:21:07)'], 
        //     writer:'ON Group Medical Foundation ON Hospital',
        //     top_small:'',
        //     img_text:'온라이프상조 상품설명회 모습. (온라이프상조 제공)', 
        //     top_bold:['반려인구 1500만 시대, 화장·수의 등 장례도 ‘가족 보내듯’', '검진·성형·임플란트 등 ‘인구 고령화 맞춤형’ 상품 요구 반영'],
        //     top_content:'',
        //     center_con:[
        //         '지난해 9월 상조시장에 뛰어든 부산 온라이프상조가 1500만 반려인구 시대를 맞이해 펫상품을 출시한다고 7일 밝혔다. 이와 함께 평균수명이 늘어남에 따라 삶의 질을 높일 수 있는 헬스케어 상품까지 내놓아 반려인과 어르신들을 대상으로 큰 관심을 끌고 있다.',
        //         '온라이프상조에 따르면 390만 원과 490만 원짜리 펫 상조상품 ‘애기랑나랑’을 2월부터 판매 중이다. 온라이프상조의 펫 상조상품은 화장, 수의, 수의보, 관, 액자, 유물함 등 장의관련 상품은 물론 드라이어, 사료, 펫 용품까지 제공한다. ‘아기랑나랑’ 펫상조 상품인 ‘390상품’의 경우 매달 3만원씩 130회 불입한다. ‘490상품’은 매달 3만 5000원씩 총 140회 낸다. 반려견이나 반려묘의 평균수명(15∼18년)을 고려해서 불입 기간을 설정했다는 게 온라이프상조 관계자의 설명이다. 두 상품 모두 만기 시 환급 가능하다.',
        //         '온라이프상조 측은 “반려동물이 갑자기 죽으면 사람들은 대개 어찌할 바를 모르고 당황해한다”면서 “펫 상조상품 가입자들은 사별하는 즉시 상조회사로 연락하면 모든 서비스를 즉시 제공받을 수 있다”고 강조했다.',
        //         '온라이프상조는 또 펫 상품과 더불어, 인구고령화로 인해 삶의 질을 따지는 어르신들이 점점 늘어남에 따라 온VIP성형상품, 온VIP눈사랑상품, 온VIP치아사랑 상품, 온VIP건강검진 상품 등 헬스케어 상조상품을 출시한다.',
        //         '‘온VIP성형상품’은 ‘남은 인생을 더 가꾸고 즐기면서 보내려는 어르신들이 늘고 있는 요즘 성형의 새로운 추세’에 발맞춰 온라이프상조가 의욕적으로 내놓은 신상품이다. 기본적으로 눈과 코 성형은 물론, 대부분 어르신들이 겪고 있는 비만치료를 위해 지방흡입수술과 지방이식수술 시에도 도움을 받을 수 있다.',
        //         '‘온VIP눈사랑상품’은 백내장과 녹내장 수술뿐만 아니라, 안검하수나 안성형 서비스를 받는다. ‘온VIP치아사랑 상품’도 치료비가 적지 않게 드는 임플란트나 틀니 수술에 큰 도움을 받을 수 있다. ‘온VIP건강검진 상품’은 일반적인 혈액 및 청력검사, 안과검사는 물론 초음파나 MRI(자기공명영상검사) 검사로 암 등 노년 건강을 위협하는 각종 질병 조기진단 서비스를 제공한다. 특히 방사선 피폭선량이 최소화하면서도 화질이 선명해 미세 암이나 심뇌혈관, 치매 검사까지 가능한 디지털 PET-CT(양전자방출 단충촬영) 검사까지 받을 수 있다.',
        //         '온라이프상조 정근 원장은 “반려인구는 인구고령화 추세와 맞물리면서 점점 늘어나고 있다”고 지적하고, “어르신 반려인이나 반려동물 모두 행복한 동행을 아름답게 마무리하려면 미리 관련 상조상품에 가입하는 것도 노후생활의 지혜”라고 말했다.',
        //     ],
        //     editor:'원동화 기자 dhwon@busaneconomy.com',
        //     sources:'출처 : 부산제일경제(https://www.busaneconomy.com/news/articleView.html?idxno=297602)' ,
        //     a_link:'https://www.busaneconomy.com/news/articleView.html?idxno=297602',
        //     img_src:'media/이색_펫_상품출시.jpg',
        // },
        // {cate_no:2, 
        //     item_no:3, 
        //     title:'정근 “사명 바꾼 온라이프건설 책임경영…당월 현금결제”', 
        //     date:['2023.02.06','(14:48:51)'], 
        //     date2:['23.02.06','(14:48:51)'], 
        //     writer:'ON Group Medical Foundation ON Hospital',
        //     top_small:'',
        //     img_text:'온그룹 정 근 그룹원장.', 
        //     top_bold:[''],
        //     top_content:'정근안과병원과 ON Hospital 등 계열사를 이끄는 온그룹(그룹원장 정근·사진)이 작년 인수한 세정건설 사명을 온라이프건설㈜로 바꾸고 건설비용 공개, 당월 현금결재 등 책임 경영에 나선다.',
        //     center_con:[
        //         '정근 원장은 1일 “올해 온건설그룹이 부채없이 부산 최고의 신용있는 건설회사로 자리매김해 지난 30년간 사용해 온 세정건설을 ‘부채 제로’인 온그룹 이름을 빌려 온라이프건설로 회사명을 변경하기로 했다”며 “기존 ON Hospital 건설회사인 온종합건설과 온자재회사, 온라이프건설 등을 건설전문종합회사인 온건설그룹으로 변화·성장·발전시켜 나갈 것”이라고 밝혔다.',
        //         '세정그룹 인디언이 1989년 창립한 세정건설은 지난해 1월 온그룹에 인수됐다. 빌딩 등 일반 건물을 짓는 온라이프건설은 내달부터 당월 현금결재를 원칙으로 책임시공과 시공기간 완수를 준수할 방침이다.',
        //         '정 원장은 “세정건설을 인수한 뒤 보유한 현금으로 은행 부채 전액(500억 원)을 갚고, 인수 전 공사부실이 된 13곳 공사현장 가운데 12곳에 대해 책임 준공했다”면서 “온라이프건설은 현재 금융권 부채 없이 시티타워(부지면적 4554㎡, 건축 총면적 4만9500㎡의 48% 지분 소유) 등 자산만 1000억 원가량 되는 재정적으로 안정적이고 건실한 건축회사로 거듭났다”고 설명했다.',
        //         '그러면서 “올해 설정한 수주목표액 2000억 원도 현재 상당수 계약 성사 단계”라고 덧붙였다.'
        //     ],
        //     editor:'최영지 기자 jadore@kookje.co.kr',
        //     sources:'출처: 국제신문(http://www.kookje.co.kr/news2011/asp/newsbody.asp?code=2100&key=20230202.22017000434)' ,
        //     a_link:'http://www.kookje.co.kr/news2011/asp/newsbody.asp?code=2100&key=20230202.22017000434',
        //     img_src:'media/온라이프건설_현금결제.jpg'
        // },
        // {cate_no:2, 
        //     item_no:2, 
        //     title:'누가교회, 부산 ON Hospital에 휠체어 기부', 
        //     date:['2023.01.20','(12:25:03)'], 
        //     date2:['23.01.20','(12:25:03)'], 
        //     writer:'ON Group Medical Foundation ON Hospital',
        //     top_small:'',
        //     img_text:'휠체어를 전달받은 후 가진 기념촬영 모습. 사진=ON Hospital 제공', 
        //     top_bold:['2023년 맞아 헌금 모아 환우들 위해 기탁'],
        //     top_content:'ON Hospital은 병원 내에 소재한 누가교회(목사 권용수)에서 지난 16일 온병원그룹에 휠체어 10대(300만원 상당)를 기탁했다고 밝혔다.',
        //     center_con:[
        //         '누가교회는 부산 ON Hospital(병원장 김동헌) 내 속한 교회로 매주 주일예배, 수요예배를 운영 중이며 120여명의 환우 및 보호자들이 병마에 지친 몸과 마음을 위로받고 있다.',
        //         '예배를 드리며 헌금을 낸 환자 A 씨는 “오랜 병원 생활로 인해 지치고 힘들었는데 누가교회를 다니며 치유되고 있다”며 “비록 작은 돈이지만, 나처럼 아픈 환우들을 위해 사용된다 해서 기쁜 마음으로 헌금했다”고 밝혔다.',
        //         '누가교회 권용수 목사는 “2023년 희망의 새해를 시작하면서 환우들과 보호자들의 마음을 위로하기 위해 선한 이웃돕기 사마리아 헌금을 모아 휠체어를 기탁했다”며 “병원을 이용하는 환우들 중 몸이 불편해 휠체어를 이용하는 분들이 많으신데, 그분들이 잘 이용해주시면 기쁘겠다”고 소감을 밝혔다.',
        //         '한편, 누가교회 성금으로 구매한 휠체어는 일반형 휠체어 9대, 거상형 휠체어 1대로 병원 내에서 환우들의 편리한 이동에 도움을 줄 것으로 기대된다.',
        //         '누가교회 권 목사는 “앞으로도 약한 자, 병든 자, 어려움에 처한 자들을 위해 기도와 도움으로 용기를 줄 것”이라며 “일어나 걸어가는 기적의 역사를 위해 적은 힘이나마 보탬이 되고자 최선을 다하겠다”고 밝혔다.'
        //     ],
        //     editor:'박정헌 부산/경남 기자 ilyo33@ilyo.co.kr',
        //     sources:'출처: 일요신문(https://ilyo.co.kr/?ac=article_view&entry_id=445215)' ,
        //     a_link:'https://ilyo.co.kr/?ac=article_view&entry_id=445215',
        //     img_src:'media/누가교회_휠체어_기부.jpg'
        // },
        // {cate_no:2, 
        //     item_no:1, 
        //     title:'ON Hospital, 前 부산대병원 조군제 교수 초빙', 
        //     date:['2023.01.19','(16:21:08)'], 
        //     date2:['23.01.19','(16:21:08)'], 
        //     writer:'ON Group Medical Foundation ON Hospital',
        //     top_small:'',
        //     img_text:'', 
        //     top_bold:['대한혈액학회 회장 등 역임···"혈액암 포함 암치료 전문성 강화'],
        //     top_content:'',
        //     center_con:[
        //         '부산 ON Hospital(병원장 김동헌)은 최근 조군제 前 부산대병원 DEPARTMENT OF HEMATO-ONCOLOGY 교수를 초빙했다고 16일 밝혔다.',
        //         '이달 2일부터 ON Hospital에서 진료를 시작한 조군제 교수는 부산대 의대를 졸업하고 동대학원에서 석·박사를 수료한 DEPARTMENT OF HEMATO-ONCOLOGY 1세대 교수 출신이다.',
        //         '그는 부산대병원에서 내과 총괄과장 및 주임교수, DEPARTMENT OF HEMATO-ONCOLOGY 교수로 재직하다 지난 2013년 정년퇴직했다. 이후 혈우재단 부산의원 원장을 지냈다. ',
        //         '학술 분야에서는 대한혈액학회 회장, 대한조혈모세포이식학회 회장 등으로 활동했다. ',
        //         '김동헌 ON Hospital장은 "조군제 교수 영입으로 혈액암 및 고형암으로 투병 중인 환우들에게 보다 전문성 있는 진료를 제공할 수 있을 것으로 기대된다"고 말했다.'
        //     ],
        //     editor:'이슬비 기자 sbl@dailymedi.com',
        //     sources:'출처: 데일리메디(https://www.dailymedi.com/news/news_view.php?wr_id=893395)' ,
        //     a_link:'https://www.dailymedi.com/news/news_view.php?wr_id=893395',
        //     img_src:'media/조균제_교수_초빙.jpg'
        // },
    ],
    // Employment
    [
        {cate_no:3, item_no:10, 
            title:'[Closed] 2023 ON Hospital New Nurse Recruitment Announcement', 
            date:['2022.08.24','(14:48:05)'], 
            date2:['22.08.24','(14:48:05)'], 
            writer:'ON Hospital', 
            con1:[''], 
            img_src:'recruitment/2023년_신규간호사_채용공고_마감.png'},
        {cate_no:3, item_no:9, 
            title:'[Closed] 2022 ON Hospital Hospice Nurse Coordinator Job Announcement', 
            date:['2022.08.11','(15:11:57)'], 
            date2:['22.08.11','(15:11:57)'], 
            writer:'ON Hospital', 
            con1:[
                ' ON Hospital was opened in March 2010 based on Christian ideology',
                'It is a hospital that has grown significantly internally and externally in a short period of time, including a certified medical institution by the Ministry of Health and Welfare, an intern training hospital, a doctor training institution, a comprehensive nursing service pilot project institution, and a local emergency medical institution.',
                'It is also planned to expand to 800 beds in the future.',
            ],
            con2:[
                '1)Hospice nurse (coordinator)',
                '      - Completion of hospice education - full-time',
                '      I have a sense of mission as a hospice ward nurse, and I would like to ask for your support as a warm-hearted nurse.'
            ],
            con3:[
                ' -Experienced applicants preferred',
                ' -In the case of veterans and disabled people, preferential treatment is given according to the relevant laws.'
            ],
            con4:[
                ' 1.Full reduction of medical expenses (ON Hospital, Jeonggeun Eye Hospital)',
                '2.Patient INTRODUCTION Incentive payment',
                '3. Free use of staff cafeteria',
                '4. Free dormitory provided (limited to those who work in the 3rd shift)',
                '5.Overseas training for ward shift workers and friendly staff',
                '6.All staff summer retreat & sports meet',
                '7.Special support for club activities',
                '8.Participation in overseas medical volunteering (hosted by Green Doctors)',
                '9.Payment of birthday gifts, congratulations and condolences vacations, and congratulations and condolences money',
                '10.Employee Relations Association operation',
                '11.On Scholarship Foundation Benefit Grant (scheduled)'
            ],
            con5:[
                '가)Resume, self-INTRODUCTION 1 copy (form of the main office)',
                '     ①According to Article 11 of the Act on Fair Recruitment Procedures, job seekers` recruitment documents are kept for 180 days, after which they are destroyed in accordance with the Personal Information Protection Act.',
                '      ②If you wish to return employment documents, please contact the person in charge of personnel below, fill out the request for return of employment documents, and submit it via e-mail.',
                '      ③In principle, the job offerer is responsible for the cost of returning the employment documents, but the postal charges and postal service fees incurred in the case of delivery by special handling mail',
                '        Please note that the fee is borne by the job seeker.',
                '      ※Recruitment documents can only be submitted by e-mail',
            ],
            con6:[
                '   -Information on the interview schedule for successful applicants in the first document',
                '   -Information on passing the 2nd interview'
            ],
            con7:[
                '   -Human receptionist',
                '   -E-mail reception',
                '    Please write 1) hospice nurse "hospice nurse (coordinator) applicant OOO" in the subject line of the email and send it.',
                '   -Email address: onhospital@hanmail.net'
            ],
            con8:[
                '  -Person in charge: Personnel manager (general affairs planning team)ㅣonhospital@hanmail.net',
                '  -Tel: 051)607-0133'
            ],  
            con_title:[
                '■ Hospital INTRODUCTION', 
                '■ Recruitment fields',
                '■ Preferential treatment',
                '■ ON Hospital`s special employee benefits',
                '■ Submission documents',
                '■ Selection method',
                '■ How to apply',
                '■ Inquiries'
            ], 
            img_src:'recruitment/2022년_호스피스_전문간호사_코디네이터_채용공고_마감.jpg'},
        {cate_no:3, item_no:8, 
            title:'[Closed] 2022 ON Hospital Hospice Nurse Recruitment Announcement', 
            date:['2022.06.16','(14:22:22)'], 
            date2:['22.06.16','(14:22:22)'], 
            writer:'ON Hospital', 
            con1:[
                ' ON Hospital was opened in March 2010 based on Christian ideology',
                'It is a hospital that has grown significantly internally and externally in a short period of time, including a certified medical institution by the Ministry of Health and Welfare, an intern training hospital, a doctor training institution, a comprehensive nursing service pilot project institution, and a local emergency medical institution.',
                'It is also planned to expand to 800 beds in the future.',
                '부산의 중심 서면에 위치, 지하철2호선 부암역(ON Hospital역)과 바로 연결되어 가장 접근성이 좋고 교통이 편리한 도심형 종합병원입니다.'
            ],
            con2:[
                ' 1)Hospice ward nurse', 
                '     - Completion of hospice education',
                '       I have a sense of mission as a hospice ward nurse, and I would like to ask for your support as a warm-hearted nurse.'
            ],
            con3:[
                ' -Experienced applicants preferred',
                ' -In the case of veterans and disabled people, preferential treatment is given according to the relevant laws.'
            ],
            con4:[
                ' 1.Full reduction of medical expenses (ON Hospital, Jeonggeun Eye Hospital)',
                '2.Patient INTRODUCTION Incentive payment',
                ' 3.Free use of staff cafeteria',
                ' 4.Free dormitory provided (limited to those who work in the 3rd shift)',
                ' 5.Overseas training for ward shift workers and friendly staff',
                ' 6.All staff summer retreat & sports meet',
                ' 7.Special support for club activities',
                ' 8.Participation in overseas medical volunteering (hosted by Green Doctors)',
                ' 9.Payment of birthday gifts, congratulations and condolences vacations, and congratulations and condolences money',
                ' 10.Employee Relations Association operation',
                '11.On Scholarship Foundation Benefit Grant (scheduled)'
            ],
            con5:[
                ' 가)Resume, self-INTRODUCTION 1 copy (form of the main office)',
                '     ①According to Article 11 of the Act on Fair Recruitment Procedures, job seekers` recruitment documents are kept for 180 days, after which they are destroyed in accordance with the Personal Information Protection Act.',
                '      ②If you wish to return employment documents, please contact the person in charge of personnel below, fill out the request for return of employment documents, and submit it via e-mail.',
                '      ③In principle, the job offerer is responsible for the cost of returning the employment documents, but the postal charges and postal service fees incurred in the case of delivery by special handling mail',
                '        Please note that the fee is borne by the job seeker.',
                '      ※Recruitment documents can only be submitted by e-mail',
                '      ※Recruitment may be canceled if information such as resume and career is different from the facts.'
            ],
            con6:[
                '   -Information on the interview schedule for successful applicants in the first document',
                '   -Information on passing the 2nd interview'
            ],
            con7:[
                '   -Human receptionist',
                '   -E-mail reception',
                '    Please write 1) hospice nurse "hospice nurse (coordinator) applicant OOO" in the subject line of the email and send it.',
                '   -Email address: onhospital@hanmail.net'
            ],
            con8:[
                '  -Person in charge: Personnel manager (general affairs planning team)ㅣonhospital@hanmail.net',
                '  -Tel: 051)607-0133'
            ], 
            con_title:[
                '■ Hospital INTRODUCTION', 
                '■ Recruitment fields',
                '■ Preferential treatment',
                '■ ON Hospital`s special employee benefits',
                '■ Submission documents',
                '■ Selection method',
                '■ How to apply',
                '■ Inquiries'
            ],
            img_src:'recruitment/2022년_호스피스_병동_간호사_채용공고_마감.jpg'},
        // {cate_no:3, item_no:7, 
        //     title:'[공고]2022년 ON Hospital 간호사, 간호조무사(병동, 처치사)채용공고', 
        //     date:['2022.06.16','(14:14:07)'], 
        //     date2:['22.06.16','(14:14:07)'], 
        //     writer:'ON Hospital', 
        //     con1:[' ON Hospital was opened in March 2010 based on Christian ideology','보건복지부 인증의료기관, 인턴수련병원, 의사연수교육기관, 포괄간호서비스 시범사업기관, 지역응급의료기관 등 짧은 기간에 내·외적으로 크게 성장해온 병원입니다.','또한 향후 800병상 규모로 증축을 예정 하고 있습니다.','부산의 중심 서면에 위치, 지하철2호선 부암역(ON Hospital역)과 바로 연결되어 가장 접근성이 좋고 교통이 편리한 도심형 종합병원입니다.'],
        //     con2:[' 1)QPS팀장 - 경력5년',' 2)QPS간호사',' 3)병동 간호조무사',' 4)수술실 PA간호사',' 5)수술실 스크럽 간호사',' 6)수술실 처치사(간호조무사)',' 7)Liver PA간호사',' 8)교대근무 간호사-병동, 응급실, 중환자실 2교대/3교대',' 9)DEPARTMENT OF GASTROENTEROLOGY PA간호사',' 10)Department of Hepatobiliary and Pancreatic Surgery PA간호사'],
        //     con3:[' -경력자 우대',' -보훈대상자 및 장애인의 경우 관련법에 의하여 우대합니다.'],
        //     con4:[' 1.진료비 전액 감면혜택(ON Hospital, 정근안과병원)','2.환자 INTRODUCTION 인센트브 지급',' 3.직원식당 무료 이용',' 4.기숙사 무료제공(3교대 근무자에 한함)',' 5.병동교대근무 근속자 및 친절직원 해외연수',' 6.전직원 여름수련회&체육대회',' 7.동아리활동 특별지원',' 8.해외의료봉사 참여(그린닥터스 주관)',' 9.생일선물, 경조휴가 및 경조금 지급',' 10.직원상조회 운영','11.온장학재단 혜택부여(예정)'],
        //     con5:[' 가)이력서, 자기INTRODUCTION서 1부(본원양식)','     ①채용절차의 공정화에 관한 법률 제11조에 따라 구직자의 채용서류는 180일간 보관되며 이후 개인정보 보호법에 따라 채용서류는 파기됩니다.','      ②채용서류 반환을 원하시는 분들은 하단 인사담당자에게 연락하셔서 채용서류 반환청구서를 작성하신 후 전자우편으로 제출 부탁드립니다.','      ③채용서류의 반환에 소요되는 비용은 원칙적으로 구인자가 부담하지만 특수취급우편물로 송달하는 경우에 드는 우편에 관한 요금 및 우편이용에 관한','        수수료는 구직자가 부담함을 알려드립니다.','      ※채용서류는 이메일로만 접수 가능합니다.(우편, 방문접수 불가)','      ※이력, 경력 등의 정보가 사실과 다를시 채용이 취소될 수 있습니다.'],
        //     con6:['   -1차 서류 합격자 면접 일정 안내','   -2차 면접 합격여부 안내'],
        //     con7:['   -사람인 접수','   -이메일 접수','    이메일 제목을 이메일 제목을 1)QPS팀장_"QPS팀장 간호사 지원자 OOO"',' 2)QPS팀원_"QPS팀원 지원자 OOO"', '3)병동간호조무사_"간호조무사 지원자 OOO"', '4)수술실PA간호사_"수술실 PA 지원자 OOO"','5)수술실 스크럽 간호사_"수술실 스크럽 지원자 OOO"','6)수술실 처치사_"처치사 지원자 OOO"  로 작성하여 보내주십시오.','   -이메일 주소', ': onhospital@hanmail.net'],
        //     con8:['  -담당자 : 인사담당자(총무기획팀)ㅣonhospital@hanmail.net','  -전화 : 051)607-0133'], 
        //     con_title:['■병원INTRODUCTION', '■모집분야','■우대사항','■ON Hospital만의 특별한 직원복리후생','■제출서류','■전형방법','■접수방법','■문의사항'], 
        //     img_src:'recruitment/2022년_간호사_간호조무사_채용공고_공고.jpg'},
        // {cate_no:3, item_no:6, 
        //     title:'[마감]2022년 ON Hospital 간호사(QPS간호사, 교육전담간호사) 채용공고', 
        //     date:['2022.05.27','(17:07:34)'], 
        //     date2:['22.05.27','(17:07:34)'], 
        //     writer:'ON Hospital',
        //     con1:[' ON Hospital은 기독교이념을 바탕으로 2010년 3월 개원하였으며, 20개 DEPARTMENT목 500병상 규모로 70여명의 의료진과 700여명의 직원이 근무 중인 종합병원입니다.','보건복지부 인증의료기관, 인턴수련병원, 의사연수교육기관, 포괄간호서비스 시범사업기관, 지역응급의료기관 등 짧은 기간에 내·외적으로 크게 성장해온 병원입니다.','또한 향후 800병상 규모로 증축을 예정 하고 있습니다.','부산의 중심 서면에 위치, 지하철2호선 부암역(ON Hospital역)과 바로 연결되어 가장 접근성이 좋고 교통이 편리한 도심형 종합병원입니다.'],
        //     con2:[' 1)QPS팀장 - 경력5년',' 2)QPS간호사',' 3)간호간병통합병동 간호교육전담간호사','    -경력 5년 이상 중 병동근무경력 1년 이상 필수', '   -주40시간'],
        //     con3:'-보훈대상자 및 장애인의 경우 관련법에 의하여 우대합니다.',
        //     con4:[' 1.진료비 전액 감면혜택(ON Hospital, 정근안과병원)','2.환자 INTRODUCTION 인센트브 지급',' 3.직원식당 무료 이용',' 4.기숙사 무료제공(3교대 근무자에 한함)',' 5.병동교대근무 근속자 및 친절직원 해외연수',' 6.전직원 여름수련회&체육대회',' 7.동아리활동 특별지원',' 8.해외의료봉사 참여(그린닥터스 주관)',' 9.생일선물, 경조휴가 및 경조금 지급',' 10.직원상조회 운영','11.온장학재단 혜택부여(예정)'],
        //     con5:[' 가)이력서, 자기INTRODUCTION서 1부(본원양식)','     ①채용절차의 공정화에 관한 법률 제11조에 따라 구직자의 채용서류는 180일간 보관되며 이후 개인정보 보호법에 따라 채용서류는 파기됩니다.','      ②채용서류 반환을 원하시는 분들은 하단 인사담당자에게 연락하셔서 채용서류 반환청구서를 작성하신 후 전자우편으로 제출 부탁드립니다.','      ③채용서류의 반환에 소요되는 비용은 원칙적으로 구인자가 부담하지만 특수취급우편물로 송달하는 경우에 드는 우편에 관한 요금 및 우편이용에 관한','        수수료는 구직자가 부담함을 알려드립니다.','      ※채용서류는 이메일로만 접수 가능합니다.(우편, 방문접수 불가)','      ※이력, 경력 등의 정보가 사실과 다를시 채용이 취소될 수 있습니다.'],
        //     con6:['  -이메일 제목을 1)"QPS팀장 간호사 지원자 OOO"','                       2)"QPS간호사 지원자 OOO"','                       3)"교육전담간호사 지원자 OOO"로 작성하여 보내주십시오.','   -이메일 주소 ',': onhospital@hanmail.net'],
        //     con7:['  -담당자 : 인사담당자(총무기획팀)ㅣonhospital@hanmail.net','  -전화 : 051)607-0133'], 
        //     con_title:['■병원INTRODUCTION', '■모집분야','■우대사항','■ON Hospital만의 특별한 직원복리후생','■제출서류','■전형방법','■문의사항'], 
        //     img_text:'ON Hospital에서 2022년 간호사(QPS간호사, 교육전담간호사) 채용을 아래와 같이 진행하오니 많은 관심과 지원바랍니다.',
        //     img_src:'recruitment/2022년_QPS_교육전담간호사_채용공고_마감.jpg'
        // },
        // {cate_no:3, item_no:5, 
        //     title:'[마감]2022년 ON Hospital 간호사, 간호조무사, 도우미 모집', 
        //     date:['2022.05.27','(17:07:05)'], 
        //     date2:['22.05.27','(17:07:05)'], 
        //     writer:'ON Hospital',
        //     con1:[' ON Hospital은 기독교이념을 바탕으로 2010년 3월 개원하였으며, 20개 DEPARTMENT목 500병상 규모로 70여명의 의료진과 700여명의 직원이 근무 중인 종합병원입니다.','보건복지부 인증의료기관, 인턴수련병원, 의사연수교육기관, 포괄간호서비스 시범사업기관, 지역응급의료기관 등 짧은 기간에 내·외적으로 크게 성장해온 병원입니다.','또한 향후 800병상 규모로 증축을 예정 하고 있습니다.','부산의 중심 서면에 위치, 지하철2호선 부암역(ON Hospital역)과 바로 연결되어 가장 접근성이 좋고 교통이 편리한 도심형 종합병원입니다.'],
        //     con2:[' 1)PA간호사(간췌담도SURGERY, 비뇨기과, Liver, DEPARTMENT OF <SPAN>RESPIRATORY MEDICINE</SPAN>, 혈액종양학과)',' 2)수술어시스트(간호사, 간호조무사)',' 3)교대근무간호사(병동, 중환자실, 응급실)(D-keep, E-keep, 파트타임 가능)','4)코로나병동 (간호사, 간호조무사, 도우미)'],
        //     con3:['-경력자 우대', '-보훈대상자 및 장애인의 경우 관련법에 의하여 우대합니다.'],
        //     con4:[' 1.진료비 전액 감면혜택(ON Hospital, 정근안과병원)','2.환자 INTRODUCTION 인센트브 지급',' 3.직원식당 무료 이용',' 4.기숙사 무료제공(3교대 근무자에 한함)',' 5.병동교대근무 근속자 및 친절직원 해외연수',' 6.전직원 여름수련회&체육대회',' 7.동아리활동 특별지원',' 8.해외의료봉사 참여(그린닥터스 주관)',' 9.생일선물, 경조휴가 및 경조금 지급',' 10.직원상조회 운영','11.온장학재단 혜택부여(예정)'],
        //     con5:[' 가)이력서, 자기INTRODUCTION서 1부(본원양식)','     ①채용절차의 공정화에 관한 법률 제11조에 따라 구직자의 채용서류는 180일간 보관되며 이후 개인정보 보호법에 따라 채용서류는 파기됩니다.','      ②채용서류 반환을 원하시는 분들은 하단 인사담당자에게 연락하셔서 채용서류 반환청구서를 작성하신 후 전자우편으로 제출 부탁드립니다.','      ③채용서류의 반환에 소요되는 비용은 원칙적으로 구인자가 부담하지만 특수취급우편물로 송달하는 경우에 드는 우편에 관한 요금 및 우편이용에 관한','      ※채용서류는 이메일로만 접수 가능합니다.(우편, 방문접수 불가)','      ※이력, 경력 등의 정보가 사실과 다를시 채용이 취소될 수 있습니다.'],
        //     con6:['-1차 서류 합격자 면접일정안내', '-2차 면접 합격여부 안내'],
        //     con7:['-사람인 접수', '-이메일 접수', '이메일 제목을 1) PA간호사 " 지원부서 PA간호사 지원자 000 "', '                    2) 수술어시스트 "어시스트 간호사 지원자 000", "어시스트 간호조무사 지원자 000"','                    3) 교대근무간호사 "지원부서 간호사 지원자 000"','                    4) 코로나병동 "코로나병동 간호사 000", "코로나병동 간호조무사 000", "코로나병동 도우미 000"로 작성하여 보내주십시오.','이메일 : onhospital@hanmail.net'],
        //     con8:['  -담당자 : 인사담당자(총무기획팀)ㅣonhospital@hanmail.net','  -전화 : 051)607-0133'], 
        //     con_title:['■병원INTRODUCTION', '■모집분야','■우대사항','■ON Hospital만의 특별한 직원복리후생','■제출서류','■전형방법','■ 접수방법','■문의사항'], 
        //     img_text:'ON Hospital은 간호사, 간호조무사, 도우미 채용을 아래와 같이 진행하오니 많은 관심과 지원바랍니다.',
        //     img_src:'recruitment/2022년_간호사_간호조무사_도우미_모집_마감.jpg'
        // },
        // {cate_no:3, item_no:4, 
        //     title:'[마감]2022년 ON Hospital 간호사/간호조무사 채용', 
        //     date:['2022.05.27','(17:06:39)'], 
        //     date2:['22.05.27','(17:06:39)'], 
        //     writer:'ON Hospital',
        //     con1:[' ON Hospital은 기독교이념을 바탕으로 2010년 3월 개원하였으며, 20개 DEPARTMENT목 500병상 규모로 70여명의 의료진과 700여명의 직원이 근무 중인 종합병원입니다.','보건복지부 인증의료기관, 인턴수련병원, 의사연수교육기관, 포괄간호서비스 시범사업기관, 지역응급의료기관 등 짧은 기간에 내·외적으로 크게 성장해온 병원입니다.','또한 향후 800병상 규모로 증축을 예정 하고 있습니다.','부산의 중심 서면에 위치, 지하철2호선 부암역(ON Hospital역)과 바로 연결되어 가장 접근성이 좋고 교통이 편리한 도심형 종합병원입니다. (출퇴근도 편리합니다.)'],
        //     con2:[' 1) 처치사(간호사, 간호조무사)',' 2) 교대근무 간호사(병동, 응급실)',' 3) PA간호사(혈액종양학과, 비뇨기과(남자), OBSTETRICS AND GYNECOLOGY, DEPARTMENT OF ORTHOPEDICS)','4) 스크럽, 마취과 간호사사'],
        //     con3:['- 경력자 우대', '- 보훈대상자 및 장애인의 경우 관련법에 의하여 우대합니다.'],
        //     con4:[' 1.진료비 전액 감면혜택(ON Hospital, 정근안과병원)','2.환자 INTRODUCTION 인센트브 지급',' 3.직원식당 무료 이용',' 4.기숙사 무료제공(3교대 근무자에 한함)',' 5.병동교대근무 근속자 및 친절직원 해외연수',' 6.전직원 여름수련회&체육대회',' 7.동아리활동 특별지원',' 8.해외의료봉사 참여(그린닥터스 주관)',' 9.생일선물, 경조휴가 및 경조금 지급',' 10.직원상조회 운영','11.온장학재단 혜택부여(예정)'],
        //     con5:[' 가)이력서, 자기INTRODUCTION서 1부(본원양식)','     ①채용절차의 공정화에 관한 법률 제11조에 따라 구직자의 채용서류는 180일간 보관되며 이후 개인정보 보호법에 따라 채용서류는 파기됩니다.','      ②채용서류 반환을 원하시는 분들은 하단 인사담당자에게 연락하셔서 채용서류 반환청구서를 작성하신 후 전자우편으로 제출 부탁드립니다.','      ③채용서류의 반환에 소요되는 비용은 원칙적으로 구인자가 부담하지만 특수취급우편물로 송달하는 경우에 드는 우편에 관한 요금 및 우편이용에 관한','        수수료는 구직자가 부담함을 알려드립니다.','      ※채용서류는 이메일로만 접수 가능합니다.(우편, 방문접수 불가)','      ※이력, 경력 등의 정보가 사실과 다를시 채용이 취소될 수 있습니다.'],
        //     con6:['-1차 서류 합격자 면접일정안내', '-2차 면접 합격여부 안내'],
        //     con7:['- 사람인 접수', ' - 이메일 접수', '   이메일 제목을  1) `처치사 간호사 지원자 OOO`, `처치사 간호조무사 지원자 OOO`','                             2) `병동 간호사 지원자 OOO`, `응급실 간호사 지원자 OOO`', '                             3) `DEPARTMENT OF HEMATO-ONCOLOGY 간호사 지원자 OOO`, `비뇨기과 간호사 지원자 OOO`, `OBSTETRICS AND GYNECOLOGY 간호사 지원자 OOO`, `DEPARTMENT OF ORTHOPEDICS', '                                 간호사 지원자 OOO`', '                             4) `스크럽 간호사 지원자 OOO`, `마취과 간호사 지원자 OOO`로 작성하여 보내주십시오.', ' 이메일 : onhospital@hanmail.net'],
        //     con8:['  -담당자 : 인사담당자(총무기획팀)ㅣonhospital@hanmail.net','  -전화 : 051)607-0133'], 
        //     con_title:['■병원INTRODUCTION', '■모집분야','■우대사항','■ON Hospital만의 특별한 직원복리후생','■제출서류','■전형방법','■접수방법','■문의사항'], 
        //     img_text:'ON Hospital은 2022년 간호사/간호조무사 채용을 아래와 같이 진행하오니 많은 관심과 지원바랍니다.',
        //     img_src:'recruitment/2022년_간호사_간호조무사_채용_마감.jpg'
        // },
        // {cate_no:3, item_no:3, 
        //     title:'[마감]2022년 ON Hospital 간호사 및 PA전문간호사 채용', 
        //     date:['2022.05.27','(17:05:57)'], 
        //     date2:['22.05.27','(17:05:57)'], 
        //     writer:'ON Hospital',
        //     con1:[' ON Hospital은 기독교이념을 바탕으로 2010년 3월 개원하였으며, 20개 DEPARTMENT목 500병상 규모로 70여명의 의료진과 700여명의 직원이 근무 중인 종합병원입니다.','보건복지부 인증의료기관, 인턴수련병원, 의사연수교육기관, 포괄간호서비스 시범사업기관, 지역응급의료기관 등 짧은 기간에 내·외적으로 크게 성장해온 병원입니다.','또한 향후 800병상 규모로 증축을 예정 하고 있습니다.','부산의 중심 서면에 위치, 지하철2호선 부암역(ON Hospital역)과 바로 연결되어 가장 접근성이 좋고 교통이 편리한 도심형 종합병원입니다.'],
        //     con2:[' 1)Urology Department PA간호사',' 2)DEPARTMENT OF ORTHOPEDICS PA간호사',' 3)Liver PA간호사','4)췌담도내과 PA간호사', '5)SURGERY(수술실 어시스트) PA간호사', '6)항암담당 PA간호사', '7)병동 교대근무간호사(응급실, 병동, 중환자실)'],
        //     con3:['- 경력자 우대','-보훈대상자 및 장애인의 경우 관련법에 의하여 우대합니다.'],
        //     con4:[' 1.진료비 전액 감면혜택(ON Hospital, 정근안과병원)','2.환자 INTRODUCTION 인센트브 지급',' 3.직원식당 무료 이용',' 4.기숙사 무료제공(3교대 근무자에 한함)',' 5.병동교대근무 근속자 및 친절직원 해외연수',' 6.전직원 여름수련회&체육대회',' 7.동아리활동 특별지원',' 8.해외의료봉사 참여(그린닥터스 주관)',' 9.생일선물, 경조휴가 및 경조금 지급',' 10.직원상조회 운영','11.온장학재단 혜택부여(예정)'],
        //     con5:[' 가)이력서, 자기INTRODUCTION서 1부(본원양식)','     ①채용절차의 공정화에 관한 법률 제11조에 따라 구직자의 채용서류는 180일간 보관되며 이후 개인정보 보호법에 따라 채용서류는 파기됩니다.','      ②채용서류 반환을 원하시는 분들은 하단 인사담당자에게 연락하셔서 채용서류 반환청구서를 작성하신 후 전자우편으로 제출 부탁드립니다.','      ③채용서류의 반환에 소요되는 비용은 원칙적으로 구인자가 부담하지만 특수취급우편물로 송달하는 경우에 드는 우편에 관한 요금 및 우편이용에 관한','        수수료는 구직자가 부담함을 알려드립니다.','      ※채용서류는 이메일로만 접수 가능합니다.(우편, 방문접수 불가)','      ※이력, 경력 등의 정보가 사실과 다를시 채용이 취소될 수 있습니다.'],
        //     con6:['-1차 서류 합격자 면접일정안내', '-2차 면접 합격여부 안내'],
        //     con7:['- 이메일 주소: onhospital@hanmail.net'],
        //     con8:['  -담당자 : 인사담당자(총무기획팀)ㅣonhospital@hanmail.net','  -전화 : 051)607-0133'], 
        //     con_title:['■병원INTRODUCTION', '■모집분야','■우대사항','■ON Hospital만의 특별한 직원복리후생','■제출서류','■전형방법','■접수방법','■문의사항'], 
        //     img_text:'ON Hospital은 PA전문간호사 채용을 아래와 같이 진행하오니 많은 관심과 지원바랍니다.',
        //     img_src:'recruitment/2022년_간호사_PA전문간호사_채용_마감.jpg'
        // },
        // {cate_no:3, item_no:2, 
        //     title:'2022년 신규 간호사 최종 합격자 발표', 
        //     date:['2022.05.27','(17:04:40)'], 
        //     date2:['22.05.27','(17:04:40)'], 
        //     writer:'ON Hospital',
        //     con1:[
        //         'ON Hospital 2022년 신규간호사 합격자 발표', 
        //         '합격을 축하합니다.', 
        //         '추후 합격자는 전체카톡으로 ON Hospital 소식을 공유하겠습니다.', 
        //         '간호사 국가고시 모두가 합격하길 기도합니다.'
        //     ],
        //     con_small:'2022년 신규간호사 최종합격자 발표 2021.10.16.xlsx',
        //     img_src:''
        // },
        // {cate_no:3, item_no:1, 
        //     title:'[마감] 총무기획팀 경력 사원 모집', 
        //     date:['2022.05.27','(16:59:32)'], 
        //     date2:['22.05.27','(16:59:32)'], 
        //     writer:'ON Hospital',
        //     con1:['ON Hospital 총무기획팀 경력직 직원채용을 아래와 같이 진행하오니 많은 관심과 지원바랍니다.'],
        // },
    ],
    // Today's Meal
    [
        {cate_no:4, 
            item_no:10, 
            title:'April 17th - April 23rd', 
            date:['2023.04.11','(16:28:40)'], 
            date2:['23.04.11','(16:28:40)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            img_src:'diet/2023_4월_17_23일.jpg'},
        {cate_no:4, 
            item_no:9, 
            title:'April 10th - April 16th', 
            date:['2023.04.06','(15:14:08)'], 
            date2:['23.04.06','(15:14:08)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            img_src:'diet/2023_4월_10_16일.jpg'
        },
        {cate_no:4, 
            item_no:8, 
            title:'April 3 - April 9', 
            date:['2023.03.30','(09:36:38)'], 
            date2:['23.03.30','(09:36:38)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            img_src:'diet/2023_4월_3_9일.jpg'
        },
        // {cate_no:4, 
        //     item_no:7, 
        //     title:'3월 27일 ~ 4월 2일', 
        //     date:['2023.03.23','(16:42:46)'], 
        //     date2:['23.03.23','(16:42:46)'], 
        //     writer:'ON Group Medical Foundation ON Hospital', 
        //     img_src:'diet/2023_3월_27_4월_2일.jpg'
        // },
        // {cate_no:4, 
        //     item_no:6, 
        //     title:'3월 20일 ~ 3월 26일', 
        //     date:['2023.03.16','(14:35:26)'], 
        //     date2:['23.03.16','(14:35:26)'], 
        //     writer:'ON Group Medical Foundation ON Hospital', 
        //     img_src:'diet/2023_3월_20_26일.jpg'
        // },
        // {cate_no:4, 
        //     item_no:5, 
        //     title:'3월 13일 ~ 3월 19일', 
        //     date:['2023.03.08','(17:37:03)'], 
        //     date2:['23.03.08','(17:37:03)'], 
        //     writer:'ON Group Medical Foundation ON Hospital', 
        //     img_src:'diet/2023_3월_13_19일.jpg'
        // },
        // {cate_no:4, 
        //     item_no:4, 
        //     title:'3월 6일 ~ 3월 12일', 
        //     date:['2023.03.02','(16:31:12)'], 
        //     date2:['23.03.02','(16:31:12)'], 
        //     writer:'ON Group Medical Foundation ON Hospital', 
        //     img_src:'diet/2023_3월_6_12일.jpg'
        // },
        // {cate_no:4, 
        //     item_no:3, 
        //     title:'2월 27일 ~ 3월 5일', 
        //     date:['2023.02.23','(14:00:57)'], 
        //     date2:['23.02.23','(14:00:57)'], 
        //     writer:'ON Group Medical Foundation ON Hospital', 
        //     img_src:'diet/2023_2월_27_3월_5일.jpg'
        // },
        // {cate_no:4, 
        //     item_no:2, 
        //     title:'2월 20일 ~ 2월 26일', 
        //     date:['2023.02.16','(09:59:14)'], 
        //     date2:['23.02.16','(09:59:14)'], 
        //     writer:'ON Group Medical Foundation ON Hospital', 
        //     img_src:'diet/2023_3월_20_26일.jpg'
        // },
        // {cate_no:4, 
        //     item_no:1, 
        //     title:'2월 13일 ~ 2월 19일', 
        //     date:['2023.02.08','(13:27:35)'], 
        //     date2:['23.02.08','(13:27:35)'], 
        //     writer:'ON Group Medical Foundation ON Hospital', 
        //     img_src:'diet/2023_2월_13_19일.jpg'
        // },

    ],
    // Frequently Asked Questions
    [
        {cate_no:5, 
            item_no:10, 
            title:'How to reissue health certificate', 
            date:['2022.05.27','(16:56:58)'], 
            date2:['22.05.27','(16:56:58)'], 
            writer:'ON Hospital', 
            const:['Do I have to visit in person to reissue the health certificate?', 'Is there any way to issue it online?']},
        {cate_no:5, 
            item_no:9, 
            title:'Hospitalization room access time for inpatient guardians', 
            date:['2022.05.27','(16:56:48)'], 
            date2:['22.05.27','(16:56:48)'], 
            writer:'ON Hospital', 
            const:['I am an inpatient caregiver', 'Is there a time limit for entering the hospital room?', 'I am going today', 'please answer about my question']},
        {cate_no:5, 
            item_no:8, 
            title:'Where are the required documents for issuance of documents??', 
            date:['2022.05.27','(16:56:36)'], 
            date2:['22.05.27','(16:56:36)'], 
            writer:'ON Hospital', 
            const:['You can check it in ABOUT → Medical Information → Certificate Issuance in the upper MENU.']},
        // {cate_no:5, 
        //     item_no:7, 
        //     title:'담당 의사 시간표는 어디서 확인하나요?', 
        //     date:['2022.05.27','(16:56:17)'], 
        //     date2:['22.05.27','(16:56:17)'], 
        //     writer:'ON Hospital', 
        //     const:['MENU 상단에 있는 [DEPARTMENT/의료진] 선택 후 해당하는 DEPARTMENT 클릭하여 확인하시면 됩니다.', '문의로 적혀있는 경우는 [병원 안내] → [Contact No.]에서 해당 DEPARTMENT 번호 확인 가능하여 전화 문의하시면 됩니다.']},
        // {cate_no:5, 
        //     item_no:6, 
        //     title:'온라인 예약이 되지를 않습니다. 오류인가요?', 
        //     date:['2022.05.27','(16:56:05)'], 
        //     date2:['22.05.27','(16:56:05)'], 
        //     writer:'ON Hospital', 
        //     const:['온라인 예약이 되지 않는 경우는 예약이 불가능한 DEPARTMENT입니다. 해당 DEPARTMENT 전화 문의 후 시간표 안내받으시고 내원하시어 원무팀 접수 후 진료 부탁드립니다.']
        // },
        // {cate_no:5, 
        //     item_no:5, 
        //     title:'보건증 검사를 원합니다. 어디로 가면 되나요? 기본 안내사항도 알려주세요.', 
        //     date:['2022.05.27','(16:55:53)'], 
        //     date2:['22.05.27','(16:55:53)'], 
        //     writer:'ON Hospital', 
        //     const:[
        //         '보건증 검사는 서면 롯데백화점 맞은편 정근 안과 건물, 건강 검진 서면 센터 7층에서 가능합니다.',
        //         '예약은 따로 필요 없이 점심시간을 제외하고 신분증 지참 후 방문해주시면 됩니다.',
        //         '검사 비용은 15,000원이며 검사 결과 직접 수령은 5일, 우편 수령은 10일 이상 소요됩니다.',
        //         'AM 접수는 12시 이전까지 와주셔야 가능하며, 식사 여부는 상관 없습니다.',
        //         '추가 문의사항은 051)607-0784, 0301 연락해주시면 됩니다.'
        //     ]
        // },
        // {cate_no:5, 
        //     item_no:4, 
        //     title:'개인 택시 기사 자격 검사도 시행 중인가요?', 
        //     date:['2022.05.27','(16:55:10)'], 
        //     date2:['22.05.27','(16:55:10)'], 
        //     writer:'ON Hospital', 
        //     const:['서면 롯데백화점 맞은편 정근 안과 건물, 건강 검진 서면 센터 5층에서 가능하며,','추가 문의사항은 051)607-0301 연락해주시면 됩니다.'], 
        // },
        // {cate_no:5, 
        //     item_no:3, 
        //     title:'온라인 예약이 되지를 않습니다. 오류인가요?', 
        //     date:['2022.05.27','(16:56:05)'], 
        //     date2:['22.05.27','(16:56:05)'], 
        //     writer:'ON Hospital', 
        //     const:['온라인 예약이 되지 않는 경우는 예약이 불가능한 DEPARTMENT입니다. 해당 DEPARTMENT 전화 문의 후 시간표 안내받으시고 내원하시어 원무팀 접수 후 진료 부탁드립니다.']
        // },
        // {cate_no:5, 
        //     item_no:2, 
        //     title:'운전 면허 발급용 검사도 온 종합병원 본원에서 가능한가요?', 
        //     date:['2022.05.27','(16:55:00)'], 
        //     date2:['22.05.27','(16:55:00)'], 
        //     writer:'ON Hospital', 
        //     const:['서면 롯데백화점 맞은편 정근 안과 1층에서 가능합니다.', '비용은 1종 보통 5,000원, 대형 6,000원이며 추가 문의사항은 051)668-8000 연락해주시면 됩니다. ']
        // },
        // {cate_no:5, 
        //     item_no:1, 
        //     title:'점심시간이 있나요? 있으면 시간을 알려주세요.', 
        //     date:['2022.05.27','(16:54:44)'], 
        //     date2:['22.05.27','(16:54:44)'], 
        //     writer:'ON Hospital', 
        //     const:['월~금요일은 PM 12:30 ~ PM 1:30로 동일하며, 토요일은 점심시간 없이 진료 가능합니다.']
        // },
    ],
]