const NEWS_DETAIL = [
    // Announcements
    [
        {cate_no:0, 
            item_no:1, 
            title:'[Treatment Guidelines] Guide to medical treatment schedule in May', 
            date:['2023,04,24','(09:28:48)'], 
            date2:['23,04,24','(09:28:48)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            const:[''],
            red:[''],
            img_src:'notice/가정의달.jpg'
        },
        {cate_no:0, 
            item_no:2, 
            title:'[Recruitment] Hospice Volunteer Seminar & Certification Course', 
            date:['2023,03,16','(13:26:01)'], 
            date2:['23.03.16','(13:26:01)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            const:[''],
            red:[''],
            img_src:'notice/호스피스_자원봉사자_세미나_자격증과정.png'
        },
        {cate_no:0, 
            item_no:3, 
            title:'[Closed notice] March 1st holiday notice', 
            date:['2023,02,23','(09:41:05)'], 
            date2:['23.02.23','(09:41:05)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            const:[''],
            red:[''],
            img_src:'notice/삼일절_휴진_안내.jpg'},
        {cate_no:0, 
            item_no:4, 
            title:'[Treatment Information] January 2023 Treatment Schedule Guide (Lunar New Year Holidays)', 
            date:['2023,01,05','(09:53:38)'], 
            date2:['23.01.05','(09:53:38)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            const:['| Closed on January 21-23, 2023, substitute holiday on the 24th, only AM treatment is available, so please check the schedule.',],
            red:'',
            img_src:'notice/설연휴_2023년_1월.jpg'},
        {cate_no:0, 
            item_no:5, 
            title:'[Clinical treatment information] October medical treatment schedule information (National Foundation Day, Hangeul Day in 2022)', 
            date:['2022,09,16','(11:17:32)'], 
            date2:['22.09.16','(11:17:32)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            const:['| Closed on January 21-23, 2023, substitute holiday on the 24th, only AM treatment is available, so please check the schedule.',],
            red:[''],
            img_src:'notice/2022년_10월_휴진_안내.jpg'},
        // {cate_no:0, 
        //     item_no:5, 
        //     title:'[진료 안내] 6월 진료 일정 안내(2022년 지방선거, 현충일)', 
        //     date:['2022,05,27','(19:00:32)'], 
        //     date2:['22.05.27','(19:00:32)'], 
        //     writer:'ON Hospital', 
        //     const:['| 6월 1일(수), 6월 6일(월) 2022년 지방선거, 현충일은 AM 진료만 진행하니 진료에 착오 없으시길 바랍니다.',],
        //     red:[''],
        //     img_src:'notice/2022년_6월_휴진안내.jpg'},
        // {cate_no:0, 
        //     item_no:6, 
        //     title:'[휴진 안내] 어린이날 휴진 안내', 
        //     date:['2022,05,27','(19:00:15)'], 
        //     date2:['22.05.27','(19:00:15)'], 
        //     writer:'ON Hospital', 
        //     const:['| 5월 5일(목) 어린이날은휴진하오니 진료에 착오 없으시길 바랍니다.', '| '],
        //     red:[''],
        //     img_src:''},
        // {cate_no:0, 
        //     item_no:7, 
        //     title:'[휴진 안내] 설연휴 휴진 안내', 
        //     date:['2022,05,27','(19:00:02)'], 
        //     date2:['22.05.27','(19:00:02)'], 
        //     writer:'ON Hospital', 
        //     const:['| 1월 31일(월)~2월 2일(수) 설연휴는 휴진하오니 진료에 착오 없으시길 바랍니다.', '| ',],
        //     red:[''],
        //     img_src:''},
        // {cate_no:0, 
        //     item_no:8, 
        //     title:'[휴진 안내] 성탄절 및 신정 휴진 안내', 
        //     date:['2022,05,27','(18:59:50)'], 
        //     date2:['22.05.27','(18:59:50)'], 
        //     writer:'ON Hospital', 
        //     const:['| 12월 25일(토) 성탄절, 1월 1일(토) 신정휴진하오니 진료에 착오 없으시길 바랍니다.', ],
        //     red:[''],
        //     img_src:''},
        // {cate_no:0, 
        //     item_no:9, 
        //     title:'[Medical Information] 한글날 진료 안내', 
        //     date:['2022,05,27','(18:57:08)'], 
        //     date2:['22.05.27','(18:57:08)'], 
        //     writer:'ON Hospital', 
        //     const:['| 10월 9일(금) 한글날은 AM진료(09:00 ~ 13:00)하오니 진료에 착오 없으시길 바랍니다.'],
        //     red:[''],
        //     img_src:''},
        // {cate_no:0, 
        //     item_no:10, 
        //     title:'[휴진 안내] 추석 휴진 안내', 
        //     date:['2022,05,27','(18:59:21)'], 
        //     date2:['22.05.27','(18:59:21)'], 
        //     writer:'ON Hospital', 
        //     const:[''],
        //     red:[''],
        //     img_src:''},
    ],
    // More News
    [
        {cate_no:1, 
            item_no:1, 
            title:'This is ONN card news for April.', 
            date:['2023.05.03','(14:33:26)'], 
            date2:['23.05.03','(14:33:26)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            const:[''], 
            img_src:'ext/2023년_4월_카드뉴스.jpg'
        },
        {cate_no:1, 
            item_no:2, 
            title:'This is ONN card news for February.', 
            date:['2023.02.27','(15:59:31)'], 
            date2:['23.02.27','(15:59:31)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            const:[''], 
            img_src:'ext/2023년_2월_카드뉴스.jpg'
        },
        {cate_no:1, 
            item_no:3, 
            title:'This is the news of the dispatch of emergency medical volunteers to Turkey after the Great Earthquake in Turkey..', 
            date:['2023.02.20','(12:09:39)'], 
            date2:['23.02.20','(12:09:39)'], 
            writer:'ON Group Medical Foundation ON Hospital',
            img_src:'ext/튀르키예_대지진_대한민국_긴급의료봉사단_파견소식.png'
        },
        {cate_no:1, 
            item_no:4, 
            title:'[Rise and walk at the hospital] Rehabilitation exercise method in the acute phase (1 to 6 weeks) after total hip arthroplasty', 
            date:['2023.02.01','(13:18:05)'], 
            date2:['23.02.01','(13:18:05)'], 
            writer:'ON Group Medical Foundation ON Hospital',
            under_text:'These are rehabilitation exercises in the acute phase (1 to 6 weeks) after total hip arthroplasty.',
            num_text:[
                '01. Prevention of vascular complications and cardiopulmonary complications',
                '02. Prevention of dislocation and incomplete dislocation',
                '03. Improvement of muscle strength and endurance of arms and non-surgical legs',
                '04. Prevention of hip flexion contracture',
                '05.  Reflex inhibition and prevention of atrophy'
            ],
            ext_text: [
                'I prepared the video in the same order as above.',
                'Thank you for watching and interest:^)'
            ],
            recomm_text: [
                'More and more detailed rehabilitation treatment stories?',
                'Get up and walk, you can check it out at the On Rehabilitation Café!',
            ],
            link_text:['Get up and walk, go to On Rehabilitation Hospital Cafe', 'ext/thumbs_up.png'],
            img_src:'',
            iframe_link:'ext/인공_고관절_재활운동법.mp4'
        },
        {cate_no:1, 
            item_no:5, 
            title:'This is ONN card news for January.', 
            date:['2023.01.26','(15:55:09)'], 
            date2:['23.01.26','(15:55:09)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            const:[''], 
            img_src:'ext/2023년_1월_카드뉴스.jpg'
        },
        // {cate_no:1, 
        //     item_no:4, 
        //     title:'호스피스 자원봉사자 교육 및 실습과정 수강 신청', 
        //     date:['2022.05.27','(18:53:37)'], 
        //     date2:['22.05.27','(18:53:37)'], 
        //     writer:'ON Hospital', 
        //     const:[''], 
        //     img_src:'ext/호스피스_자원봉사자_교육_실습_수강모집.jpg'
        // },
    ],
    // News & Publications
    [
        {cate_no:2, 
            item_no:10, 
            title:'Busan ON Hospital "Sudden deafness and tinnitus should be actively treated rather than neglected"', 
            date:['2023.04.03','(17:33:44)'], 
            date2:['23.04.03','(17:33:44)'], 
            writer:'ON Group Medical Foundation ON Hospital',
            top_small:'',
            img_text:['Lee Il-woo, chief of OTOLARYNGOLOGY at ON Hospital in Busan, is treating patients. (Provided by Busan ON Hospital)'],
            top_bold:['검사 거쳐야 정확한 진단 가능', '이 과장"이명 원인 질환 제거 중요"'],
            top_content:'',
            center_con:[
                'Recently, an increasing number of people complain of tinnitus and sudden hearing loss, but many of them ignore the symptoms and neglect them.',
                'In particular, more and more young people complain of symptoms compared to the past, and if the symptoms get worse, it can worsen to a condition where it is difficult to restore hearing, so attention is needed.',
                'Hearing loss, which is a representative disease of the ear, refers to a condition in which hearing is reduced or lost.',
                'Hearing loss can be largely divided into conductive hearing loss and sensorineural hearing loss, but it is difficult for patients to accurately distinguish their own hearing loss. Diagnosis is made through examinations such as medical history and hearing tests, and treatment varies depending on the type of hearing loss.',
                'Sudden hearing loss is sensorineural hearing loss that has occurred within 3 days of hearing loss of 30 dB or more in 3 or more consecutive frequencies in pure tone audiometry.',
                'It is sometimes accompanied by ringing in the ears (tinnitus), a feeling of fullness in the ears (ear fullness), or dizziness. In most cases, no specific cause can be found, but the prognosis is good with early detection and appropriate treatment.',
                'Lee Il-woo, director of OTOLARYNGOLOGY at ON Hospital in Busan, said, “1/3 of patients with sudden hearing loss regain normal hearing, but the remaining 1/3 partially recovers but loses hearing, and the remaining 1/3 completely loses hearing.” It is necessary to conduct appropriate symptomatic treatment, check the patient`s condition well, and actively treat it.”',
                'Tinnitus is a state in which you feel that you hear a sound in the absence of an external auditory stimulus. If you listen to the history and remove the cause, the symptoms will improve. In very rare cases, tinnitus may occur due to an auditory nerve tumor or cerebellar pontine tumor.',
                'Manager Lee Il-woo emphasized, “The cause of tinnitus is unclear, so there are few people who persistently go to the hospital.”.'
            ],
            editor:'Reporter Ahn Do-il doit0805@getnews.co.kr',
            sources:'Source: Global Economic Daily (https://www.getnews.co.kr/news<span>/articleView.html?idxno=621452)</span>' ,
            a_link:'https://www.getnews.co.kr/news/articleView.html?idxno=621452',
            img_src:'media/돌발성_난청_이명.jpg'},
        {cate_no:2, 
            item_no:9, 
            title:'Busan ON Hospital provides pansy flower sea squirt bibimbap to hospice patients and their families', 
            date:['2023,03,24','(11:47:57)'], 
            date2:['23.03.24','(11:47:57)'], 
            writer:'ON Group Medical Foundation ON Hospital',
            top_small:'',
            img_text:['Pansy flower sea squirt bibimbap. Photo = ON Hospital'], 
            top_bold:[''],
            top_content:'Busan ON Hospital (Director Kim Dong-heon) announced on the 21st that it cooked pansy flower sea squirt bibimbap and served it as a meal to Hospice & Palliative Care patients and their families.',
            center_con:[
                'The hospice ward of ON Hospital prepares and serves various dishes once a week for inpatient patients and their guardians. The pansy flower sea squirt bibimbap was hosted by the hospice ward of ON Hospital, and was provided to patients and their guardians through the hands of the hospice ward staff.',
                'Guardian Choi, who was served a meal, said, “It was sad to be alone in the hospital room without being able to see the flowers even though spring came. Thank you for providing such food of love,” she said.',
                'The hospice social worker who planned the event said, “It would be great if patients and their caregivers could gain strength and comfort to fight diseases through a cooking event delivered with love and sincerity.',
                'Kim Dong-heon, director of the hospital, said, "We will work harder and support the hospice ward patients and their families so that they can receive comfort and lead meaningful lives every day.'
            ],
            editor:'Reporter Jeongheon Park, Busan/Gyeongnam, ilyo33@ilyo.co.kr',
            sources:'Source: Sunday Newspaper (https://ilyo.co.kr/?ac=<span>article_view&entry_id=449016)</span>' ,
            a_link:'https://ilyo.co.kr/?ac=article_view&entry_id=449016',
            img_src:'media/호스피스환자_가족에_팬지꽃_멍게_비빔밥.png'},
        {cate_no:2, 
            item_no:8, 
            title:'A Korean doctor who suffered a cerebral hemorrhage while volunteering in Turkey...Treats victims of victims to the end', 
            date:['2023,03,24','(09:28:37)'], 
            date2:['23.03.24','(09:28:37)'], 
            writer:'ON Group Medical Foundation ON Hospital',
            top_small:'',
            img_text:['Oh Moo-young, director of the Respiratory Allergy Center at ON Hospital, is doing medical volunteer work in Turkey. Courtesy of ON Hospital'], 
            top_bold:[
                'Need to differentiate between disease and treatment depending on symptoms', 
                'Spinal stenosis, pain relief when bending over', 
                'Exercises that reduce back strain, such as swimming and walking, help'
            ],
            top_content:'',
            center_con:[
                'A Korean doctor in his 70s who went to Turkiye for medical service completed the service despite symptoms of a brain hemorrhage.',
                'According to the Green Doctors Foundation, an international medical volunteer organization, on the 20th, Oh Moo-young, director of the Respiratory Allergy Center at ON Hospital, suffered a cerebral hemorrhage while performing emergency medical volunteer activities at the site of the Great Turkiye Earthquake, such as Antakya, on the 17th and 24th of last month.',
                'Kim Seok-kwon, head of ON Hospital PLASTIC SURGERY CENTER, appeared on ON Group`s medical channel ONN Doctor TV on the 17th and explained the situation at the time.',
                'In response to the moderator`s question, "Is it true that a doctor was injured during the service?", Center Director Kim said, "Center Oh, who had been using the same room for the fifth day of volunteering, complained that he took painkillers for a headache, but far from subsiding, it was accompanied by dizziness. I suspected a cerebral hemorrhage or cerebral infarction.',
                'According to Center Director Kim, Center Director Oh tried to get treatment at a local hospital, but his symptoms improved, so he gave up hospitalization and completed his volunteering schedule as scheduled.',
                'Upon returning home, director Oh immediately underwent surgery after examining the patient and confirming that he had a large amount of blood in his brain. He is expected to return to the medical field soon.',
                'Center Director Oh, a specialist in PEDIATRICS, mainly took care of children and teenagers suffering from skin diseases or digestive system diseases at the earthquake volunteer site in Turkiye. Center director Oh said that as a family from South Vietnam, he participated in the volunteer service because he had a strong desire to repay Turkiye, who shed blood to protect our country`s freedom in the Korean War long ago.',
                'Jeong-geun, chairman of the Green Doctors Foundation, said, “Director Oh, who has a spirit of volunteerism, did not inform his colleagues about his illness. At the end of the (volunteer schedule), all 15 crew members who knew this were anxiously taking care of the victims throughout the rest of the schedule. It is enough to become an example for many people, regardless of nationality or religion.'
            ],
            editor:'Reporter Hyewon Lee hyewon@donga.com',
            sources:'Source: Donga.com(https://www.donga.com/news/<span>Society/article/all/20230320/118435491/2)</span>',
            a_link:'https://www.donga.com/news/Society/article/all/20230320/118435491/2',
            img_src:'media/튀르키예_의료지원_절실_2.jpg'},
        {cate_no:2, 
            item_no:7, 
            title:'94-year-old liver cancer, 40-year-old pancreatic cancer treatment… ON Hospital is a famous surgery company', 
            date:['2023,03,15','(14:07:58)'], 
            date2:['23.03.15','(14:07:58)'], 
            writer:'ON Group Medical Foundation ON Hospital',
            top_small:'Department of Hepatobiliary and Pancreatic Surgery ON Hospital`s `High-tech Surgery Team`, composed of specialists in Hepatobiliary and Pancreatic Surgery, successfully performed high-level surgery on a 94-year-old liver cancer patient and a fourth-stage pancreatic cancer patient, attracting attention. Based on this, ON Hospital will intensively reinforce cancer-focused treatment and essential medical care to compete with university hospitals.',
            img_text:[
                'Based on the accumulated high-level surgical results of the `high-tech surgery team`, ON Hospital will expand its scope to the living donor liver transplantation field this year.', 
                'Also, it will compete with university hospitals by intensively reinforcing cancer-focused treatment and essential medical fields.', 
                'Kwang-Min Park (right, Medical Director) and Professor Park Yo-han of the High-Tech Surgery Team are looking at a patient in the hospital room.'
            ], 
            top_bold:[
                '- Expanded the scope to living donor liver transplant this year', 
                '- First introduction of the latest PET-CT boolean', 
                '- A number of DEPARTMENT OF NEUROSURGERY specialists were also invited'
            ],
            top_content:'',
            center_con:[
                'ON Hospital`s high-tech surgery team announced on the 13th that it had successfully performed surgery on liver cancer patient A (94) last month. He is known to be the oldest among patients who underwent liver resection. Initially, Mr. A’s liver CT and PET-CT (positron emission tomography) tests revealed liver cancer cells with a diameter of 8 cm. The hospital was reluctant to undergo surgery because of Mr. A’s advanced age, but considered the cardiopulmonary function to be good and the extreme pain of terminal cancer if left unattended, they went into surgery. Mr. A, who has been one month after the operation, is living in a general hospital room without any pain.',
                'This team also succeeded in the operation of stage 4 pancreatic cancer patient B (female, 40) suspected of liver metastasis and superior mesenteric vein invasion. Pancreaticoduodenal resection (Whipple operation) and liver resection, which is called the `flower of surgery`, were performed at the same time to completely remove his cancer cells. Mr. B is expected to survive long-term through advanced chemotherapy in the future.',
                'Park Kwang-min, head of the high-tech surgery team (former head professor at the Department of Hepatobiliary and Pancreatic Surgery, Asan Medical Center) said, “Patients with stage 4 pancreatic cancer who are suspected of having infiltrated into the portal vein and superior mesenteric vein must first reduce the size of the cancer with chemotherapy before surgery is possible. However, the actual reduction in the size of the cancer is only 30-40%, and even that causes the cancer to severely adhere to the surrounding tissue due to the inflammatory reaction during the chemotherapy process. ” he pointed out. Team leader Park said, “Nevertheless, for cancer patients with a high degree of difficulty, such as stage 4 pancreatic cancer, receiving chemotherapy after excision surgery as soon as possible can increase the treatment effect. Therefore, it is important for SURGERY doctors to take a positive attitude.” At the same time, he predicted that Mr. B`s surgery could be considered as a groundbreaking treatment for stage 4 pancreatic cancer patients with liver metastasis.',
                'According to the hospital, the high-tech surgery team has succeeded in 20 ultra-difficulty cancer surgeries out of 500 cancer surgeries since March 2020. In addition, this year, it will expand its scope to living donor liver transplantation. To this end, Professor Park Kwang-min, who performed more than 1,000 liver transplants at Asan Medical Center in Seoul, led by Professor Park Yo-han (former Busan Paik Hospital Liver Transplant Center), Professor Moon Gi-myeong (former Pusan ​​National University Yangsan Hospital Liver Transplant Center), pancreatic biliary surgeon Lee Sang- yeop, Head of Hepatobiliary and Pancreatic Surgery Dept, etc. have come together. Recently, infection medicine and department ofRESPIRATORY MEDICINESenior professors are recruited to prepare for perfect liver transplantation.',
                'ON Hospital also introduced `digital PET-CT` for the first time in Busan, Ulsan, and Gyeongnam to activate the operation of the high-tech surgery team, enabling early diagnosis of various microscopic cancers. This equipment is very effective not only for cancer diagnosis, but also for early diagnosis of Parkinson`s disease and torticollis dementia, so it is expected to be of great help in the treatment.',
                'Kim Dong-heon, director of ON Hospital (former director of Pusan ​​National University Hospital and surgeon), said, “This year, we have secured a number of DEPARTMENT OF NEUROSURGERY specialists who are capable of brain surgery and cerebrovascular intervention, enhancing our ability to respond to essential emergency medical care. In addition, by expanding to a total of 720 beds, including 10 negative pressure rooms and 36 beds in the intensive care unit, ON Hospital, which is celebrating its 13th anniversary, has grown to a level where it can stand shoulder to shoulder with university hospitals.” Director Kim also pledged to fulfill its role as a hub hospital in Busan by taking the lead in strengthening essential medical services and coping with infectious diseases.'
            ],
            editor:'Senior Reporter Siyoung Koo ksyoung@kookje.co.kr',
            sources:'Source: International Newspaper (http://www.kookje.co.kr/news2011/asp/newsbody.asp?code=0700&key=20230314.22017003699)' ,
            a_link:'http://www.kookje.co.kr/news2011/asp/newsbody.asp?code=0700&key=20230314.22017003699',
            img_src:'media/94세_간암_췌장암치료_수술명가.jpg',
            img_src_2:'media/94세_간암_췌장암치료_수술명가_2.jpg',
        },
        {cate_no:2, 
            item_no:6, 
            title:'ON Hospital, guidance on how to use the correct denture for the first time', 
            date:['2023,03,14','(11:10:43)'], 
            date2:['23.03.14','(11:10:43)'], 
            writer:'ON Group Medical Foundation ON Hospital',
            top_small:'There is a proverb that goes, "If there are no teeth, live by the gums." It means that if something is gone, even if it is inconvenient, you will live with it as it is not there. However, living with gums without teeth is not easy. If teeth are not directly involved in food intake, which is essential for survival, or if it is difficult to chew food properly due to poor teeth, various functions of our body will be abnormal.',
            img_text:'Busan ON Hospital DENTISTRY Manager Euijeong Lee (DENTISTRY specialist). Photo = Courtesy of ON Hospital', 
            top_bold:['It is widely used for its economic advantages...correct management is important for first time wear'],
            top_content:'',
            center_con:[
                'If you can`t chew food properly because you don`t have teeth, saliva is not secreted and food that is not broken into small pieces puts a lot of pressure on the stomach, which can easily lead to indigestion and nutritional imbalance. According to a Japanese research team, teeth also affect cognitive function. When 1,167 elderly people aged 70 or older were surveyed, the group with normal cognitive function had 14.9 teeth, whereas the group with dementia had 9.4 teeth. It is estimated that the act of chewing food also affects the cognitive function of the brain.',
                'If the `teeth` that play such an important role and function are lost, dentures or implants, which can replace the role of teeth, must be treated. Dentures and implants each have their pros and cons, so they are progressed according to the patient`s condition. Many people use dentures because of their economic advantages.',
                'A `denture` is a dental prosthetic that is inserted into the mouth and removed in order to masticate when teeth and gums are lost and to recover aesthetic deficits. Dentures are very important in maintaining the shape of the face by maintaining the shape of the face by restoring the lips that have been rolled due to missing teeth, allowing them to chew food properly when teeth are missing, and to be able to pronounce properly. Therefore, it is important to know how to properly use and care for your dentures.',
                'Busan ON Hospital DENTISTRY Euijeong Lee (DENTISTRY specialist) said, “It is more important than using dentures to care for them after use.” Therefore, you should visit the DENTISTRY once every six months to check if there are any uncomfortable parts,” he explained.',
                'For those who have difficulty moving or cannot visit a hospital, a cream-type adhesive that helps attach dentures can be used. It is a one-time product that can be worn for a day and then washed off. It has staying power to prevent food from getting caught between the denture and the roof of the mouth, and it is also a great help for masticatory function. However, it is difficult to see it as a solution in the long run.',
                'To clean your dentures, you often use regular toothpaste or boil them in boiling water, which should be avoided. This is because toothpaste contains abrasives, which cause fine scratches on dentures and wear, which can cause dentures to not fit well and bacteria to propagate in the tiny gaps. This is because heating can change the shape of the denture.',
                'Dr. Euijeong Lee (DENTISTRY specialist) said, “Especially at night, many people forget to sleep with their dentures on. This increases the propagation of bacteria and accelerates the sinking of gum tissue, so it is absolutely forbidden.” It is better to use detergent or a denture brush, or use a denture cleaner that can be purchased at a pharmacy and soak it in a glass of water,” he emphasized.'
            ],
            editor:'Reporter Jeongheon Park, Busan/Gyeongnam, ilyo33@ilyo.co.kr',
            sources:'Source: Sunday Newspaper(https://ilyo.co.kr/?ac=article_view&entry_id=448537)' ,
            a_link:'https://ilyo.co.kr/?ac=article_view&entry_id=448537',
            img_src:'media/올바른_틀니_최초_사용법.png'
        },
        {cate_no:2, 
            item_no:5, 
            title:'Busan ON Hospital “It is difficult to recover if left unattended, considering cataracts and presbyopia”', 
            date:['2023,03,08','(15:07:53)'], 
            date2:['23.03.08','(15:07:53)'], 
            writer:'ON Group Medical Foundation ON Hospital',
            top_small:'',
            img_text:'Jang Yeong-joon ophthalmology chief treatment. (Provided by Busan ON Hospital)', 
            top_bold:[
                'Recently, presbyopia has increased due to the use of electronic devices among young people', 
                '“Every patient’s condition is different, so consultation is required before surgery”'
            ],
            top_content:'',
            center_con:[
                'In the past, people in their 60s and older complained of symptoms of presbyopia, but recently, due to severe stress and excessive use of smartphones, TVs, and computers, the number of cases of presbyopia is increasing even in those in their 30s or younger.',
                'Diseases that occur in the eyes do not have any particular abnormal symptoms in the early stages, so they are often discovered in the middle or above of symptoms over time.',
                'Cataracts, like presbyopia, appear as an aging phenomenon, and it is a phenomenon in which the lens becomes cloudy due to aging. Light entering the eye is not transmitted properly to the retina, resulting in reduced visual acuity. It is a common disease that occurs in a significant number of elderly people over the age of 75, but recently it is also frequently seen in people over the age of 50.',
                'Cataracts are simply presbyopia, and if left untreated, it can become an obstacle to the recovery of normal vision in the future, so timely treatment is needed.',
                'Jang Yeong-joon, director of ophthalmology at ON Hospital in Busan, explained, “Presbyopia and cataract have similar symptoms, but the treatment is different, so it is necessary to distinguish them.”',
                'In the case of simple presbyopia, vision can be corrected using multifocal glasses and multifocal lenses as a non-surgical correction method. For surgical correction, vision correction is performed by cutting the cornea with a laser.',
                'Cataracts need to be treated with medication that uses eye drops to slow their progression, and surgery to remove the clouded lens and insert an artificial lens.',
                'However, if you suffer from presbyopia and cataracts at the same time, the treatment is different. In general, if only cataract surgery is performed, the lens is removed and an artificial lens is inserted.',
                'If presbyopia and cataract are present at the same time, surgery is performed by inserting a multifocal intraocular lens that can adjust the implanted intraocular lens. If you have simple presbyopia, you do not need to consider cataract surgery.',
                'Director Jang Yeong-joon emphasized, “When deciding on a multifocal intraocular lens, it is most important to determine the appropriate type of intraocular lens based on the patient’s individual eye condition and lifestyle.',
                'If you have been using your eyes for a long time, it is helpful to take enough rest and consciously blink your eyes frequently. It is good to maintain proper humidity indoors and wear sunglasses to block UV rays while driving or doing outdoor activities.',
                'Director Jang said, “After performing this type of correction, there may be side effects such as tearing, glare symptoms, and night light smearing symptoms, but they decrease over time.” We need to hear an explanation about it,” he said.'
            ],
            editor:'Reporter Ahn Do-il doit0805@getnews.co.kr',
            sources:'Source: Global Economic Daily (https://www.getnews.co.kr/news/articleView.html?idxno=619143)' ,
            a_link:'https://www.getnews.co.kr/news/articleView.html?idxno=619143',
            img_src:'media/백내장_노안_방치.jpg'
        },
        {cate_no:2, 
            item_no:4, 
            title:'Onlife mutual aid, `exotic` pet-healthcare product launch', 
            date:['2023,02,08','(15:21:07)'], 
            date2:['23.02.08','(15:21:07)'], 
            writer:'ON Group Medical Foundation ON Hospital',
            top_small:'',
            img_text:'On-Life mutual aid product presentation. (Provided by On-Life Mutual Assistance)', 
            top_bold:[
                'In the age of 15 million companions, funerals such as cremation and burial are also `like sending a family`', 
                'Reflecting the demand for products tailored to the aging population, such as examinations, plastic surgery, and implants'],
            top_content:'',
            center_con:[
                'On the 7th, Busan On Life Sangjo, which jumped into the mutual aid market in September of last year, announced on the 7th that it will launch a pet product in the era of 15 million companions. In addition, as the average life expectancy increases, it is attracting great attention from companions and the elderly by introducing healthcare products that can improve the quality of life.',
                'According to On Life Mutual Care, pet mutual aid products, `Baby and Me`, priced at 3.9 million won and 4.9 million won, have been on sale since February. Pet mourning products of On Life Mutual Care provide not only funeral-related products such as makeup, veterinary clothes, veterinarian clothing, coffins, picture frames, and relic boxes, but also hair dryers, feed, and pet supplies. In the case of `390 Products`, a pet mutual aid product for `Baby and Me`, 30,000 won per month is paid 130 times. `490 products` is paid 35,000 won per month a total of 140 times. An OnLife mutual aid official explained that the payment period was set in consideration of the average life span (15 to 18 years) of a companion dog or cat. Both products are refundable at maturity.',
                'On Life Mutual Aid emphasized, "When a companion animal suddenly dies, people are usually confused and do not know what to do," and emphasized, "If you contact the mutual aid company immediately after a bereavement, all services can be provided immediately."',
                'In addition to pet products, On Life Mutual Care also provides health care products such as On VIP plastic surgery products, On VIP eye love products, On VIP tooth love products, and On VIP health checkup products as the number of elderly people who are concerned about the quality of life is increasing due to the aging population. Introduce complementary products.',
                '`On-VIP Plastic Surgery Product` is a new product that On Life Mutual Care has eagerly launched in line with `a new trend in plastic surgery these days where more and more elderly people want to spend the rest of their lives enjoying themselves.` Basically, you can receive help in liposuction and fat transplantation for the treatment of obesity, which most elderly people are experiencing, as well as eye and nose plastic surgery.',
                'The `On VIP Eye Love Product` provides not only cataract and glaucoma surgery, but also blepharoplasty and eye surgery services. The `OnVIP Tooth Love Product` can also be of great help for implants or dentures, which require a considerable amount of treatment. The `OnVIP health checkup product` provides early diagnosis services for various diseases that threaten the health of the elderly, such as cancer, through general blood and hearing tests, ophthalmologic tests, as well as ultrasound or MRI (magnetic resonance imaging) tests. In particular, as the image quality is clear while minimizing radiation exposure, you can even receive a digital PET-CT (Positron Emission Tomography) test that can even check for fine cancer, cardiovascular and cerebrovascular disease, and dementia.',
                'Jeong Geun, director of On Life Mutual Aid, pointed out that “the number of companions is increasing in line with the trend of aging population,” and added, “In order to end a happy companionship with both elderly companions and companion animals beautifully, subscribing to related mutual aid products in advance is also the wisdom of old age life.” said.',
            ],
            editor:'Reporter Won Dong-hwa dhwon@busaneconomy.com',
            sources:'Source: Busan Jeil Economy (https://www.busaneconomy.com/news/articleView.html?idxno=297602)' ,
            a_link:'https://www.busaneconomy.com/news/articleView.html?idxno=297602',
            img_src:'media/이색_펫_상품출시.jpg',
        },
        {cate_no:2, 
            item_no:3, 
            title:'Jung Geun “Changed the company name to On Life Construction Responsible Management… Cash payment for the current month”', 
            date:['2023.02.06','(14:48:51)'], 
            date2:['23.02.06','(14:48:51)'], 
            writer:'ON Group Medical Foundation ON Hospital',
            top_small:'',
            img_text:'Geun Jeong, the group leader of Ongroup.', 
            top_bold:[''],
            top_content:'On Group, which leads subsidiaries such as Jeonggeun Eye Hospital and ON Hospital (group director Jeonggeun, photo), changes the name of Sejeong Construction Co., Ltd., which it acquired last year, to Onlife Construction Co., Ltd.',
            center_con:[
                'On the 1st, Director Jeong Geun said, “This year, On Construction Group has established itself as the best creditable construction company in Busan without debt, so we borrowed the name of On Group, which has ‘zero debt’, from Sejeong Construction, which has been used for the past 30 years, and changed the company name to On Life Construction. “We will change, grow, and develop the existing ON Hospital construction companies, On Construction, On Materials, and On Life Construction, into the ON Construction Group, a construction company.”',
                'Founded in 1989 by Sejeong Group Indians, Sejeong Construction was acquired by Ongroup in January last year. Onlife Construction, which builds general buildings such as buildings, plans to comply with responsible construction and completion of the construction period with the principle of cash payment for the current month starting next month.',
                'Director Jeong said, “After taking over Sejeong Construction, we paid off the entire bank debt (50 billion won) with the cash we had, and were responsible for completing 12 out of 13 construction sites that were insolvent before the acquisition.” It has been reborn as a financially stable and sound construction company with assets of around 100 billion won, such as the City Tower (48% stake in a land area of ​​4,554m2 and total building area of ​​49,500m2) without debt.”',
                'He added, “The 200 billion won order target set this year is currently in the process of completing many contracts.”'
            ],
            editor:'Reporter Youngji Choi jadore@kookje.co.kr',
            sources:'Source: International Newspaper (http://www.kookje.co.kr/news2011/asp/newsbody.asp?code=2100&key=20230202.22017000434)' ,
            a_link:'http://www.kookje.co.kr/news2011/asp/newsbody.asp?code=2100&key=20230202.22017000434',
            img_src:'media/온라이프건설_현금결제.jpg'
        },
        {cate_no:2, 
            item_no:2, 
            title:'Luke Church donates wheelchairs to ON Hospital in Busan', 
            date:['2023.01.20','(12:25:03)'], 
            date2:['23.01.20','(12:25:03)'], 
            writer:'ON Group Medical Foundation ON Hospital',
            top_small:'',
            img_text:'Commemorative photo taken after receiving the wheelchair. Photo = Courtesy of ON Hospital', 
            top_bold:['In 2023, collect donations and donate for patients'],
            top_content:'ON Hospital announced on the 16th that Luke Church (Pastor Kwon Yong-soo), located within the hospital, had donated 10 wheelchairs (worth 3 million won) to the On Hospital Group.',
            center_con:[
                'Luke Church is a church belonging to ON Hospital in Busan (Hospital Director Kim Dong-heon), and operates Sunday and Wednesday worship services every week, and about 120 patients and guardians are comforted by their bodies and minds exhausted from illness.',
                'Patient A, who had a worship service and made a donation, said, “I was tired and tired from living in the hospital for a long time, but I am getting healed by going to Luke Church.” revealed.',
                'Pastor Kwon Yong-soo of Luke Church said, “As we start the new year of hope in 2023, we collected donations from Samaria for Good Neighbors and donated wheelchairs to comfort the hearts of patients and their guardians.” There are many people who use it, and I would be happy if they use it well.”',
                'Meanwhile, 9 standard wheelchairs and 1 elevated wheelchair are expected to help patients move conveniently within the hospital.',
                'Pastor Kwon of Luke Church said, “I will continue to give courage through prayer and help to the weak, the sick, and those in need.” .'
            ],
            editor:'Reporter Jeongheon Park, Busan/Gyeongnam, ilyo33@ilyo.co.kr',
            sources:'Source: Sunday Newspaper (https://ilyo.co.kr/?ac=article_view&entry_id=445215)' ,
            a_link:'https://ilyo.co.kr/?ac=article_view&entry_id=445215',
            img_src:'media/누가교회_휠체어_기부.jpg'
        },
        {cate_no:2, 
            item_no:1, 
            title:'ON Hospital, Former Pusan ​​National University Hospital Professor Gunje Cho Invited', 
            date:['2023.01.19','(16:21:08)'], 
            date2:['23.01.19','(16:21:08)'], 
            writer:'ON Group Medical Foundation ON Hospital',
            top_small:'',
            img_text:'', 
            top_bold:['Served as the president of the Korean Society of Hematology... "Strengthening expertise in cancer treatment, including blood cancer"'],
            top_content:'',
            center_con:[
                'Busan ON Hospital (Chief Director Kim Dong-heon) announced on the 16th that it recently invited former Pusan ​​National University Hospital Department of HEMATO-ONCOLOGY professor Cho Gun-je.',
                'Professor Gunje Jo, who started treatment at ON Hospital on the 2nd of this month, is a first-generation professor of DEPARTMENT OF HEMATO-ONCOLOGY who graduated from Pusan ​​National University College of Medicine and completed his master`s and doctoral degrees at the same graduate school.',
                'He retired in 2013 after serving as the head of internal medicine, the head professor, and the department of HEMATO-ONCOLOGY professor at Pusan ​​National University Hospital. He later served as the director of the Hemophilia Foundation Busan. ',
                'In the academic field, he served as the president of the Korean Society of Hematology and the Korean Society of Hematopoietic Stem Cell Transplantation.',
                'Kim Dong-heon, head of ON Hospital, said, “We expect to be able to provide more professional treatment to patients suffering from blood cancer and solid cancer with the recruitment of Professor Gunje Jo.”'
            ],
            editor:'Reporter Seulbi Lee sbl@dailymedi.com',
            sources:'Source: Dailymedi (https://www.dailymedi.com/news/news_view.php?wr_id=893395)' ,
            a_link:'https://www.dailymedi.com/news/news_view.php?wr_id=893395',
            img_src:'media/조균제_교수_초빙.jpg'
        },
    ],
    // Employment
    [
        {cate_no:3, item_no:10, 
            title:'[Closed] 2023 ON Hospital New Nurse Recruitment Announcement', 
            date:['2022.08.24','(14:48:05)'], 
            date2:['22.08.24','(14:48:05)'], 
            writer:'ON Hospital', 
            con1:[''], 
            img_src:'recruitment/2023년_신규간호사_채용공고_마감.png'},
        {cate_no:3, item_no:9, 
            title:'[Closed] 2022 ON Hospital Hospice Nurse Coordinator Job Announcement', 
            date:['2022.08.11','(15:11:57)'], 
            date2:['22.08.11','(15:11:57)'], 
            writer:'ON Hospital', 
            con1:[
                ' ON Hospital was opened in March 2010 based on Christian ideology',
                'It is a hospital that has grown significantly internally and externally in a short period of time, including a certified medical institution by the Ministry of Health and Welfare, an intern training hospital, a doctor training institution, a comprehensive nursing service pilot project institution, and a local emergency medical institution.',
                'It is also planned to expand to 800 beds in the future.',
            ],
            con2:[
                '1)Hospice nurse (coordinator)',
                '      - Completion of hospice education - full-time',
                '      I have a sense of mission as a hospice ward nurse, and I would like to ask for your support as a warm-hearted nurse.'
            ],
            con3:[
                ' -Experienced applicants preferred',
                ' -In the case of veterans and disabled people, preferential treatment is given according to the relevant laws.'
            ],
            con4:[
                ' 1.Full reduction of medical expenses (ON Hospital, Jeonggeun Eye Hospital)',
                '2.Patient INTRODUCTION Incentive payment',
                '3. Free use of staff cafeteria',
                '4. Free dormitory provided (limited to those who work in the 3rd shift)',
                '5.Overseas training for ward shift workers and friendly staff',
                '6.All staff summer retreat & sports meet',
                '7.Special support for club activities',
                '8.Participation in overseas medical volunteering (hosted by Green Doctors)',
                '9.Payment of birthday gifts, congratulations and condolences vacations, and congratulations and condolences money',
                '10.Employee Relations Association operation',
                '11.On Scholarship Foundation Benefit Grant (scheduled)'
            ],
            con5:[
                '가)Resume, self-INTRODUCTION 1 copy (form of the main office)',
                '     ①According to Article 11 of the Act on Fair Recruitment Procedures, job seekers` recruitment documents are kept for 180 days, after which they are destroyed in accordance with the Personal Information Protection Act.',
                '      ②If you wish to return employment documents, please contact the person in charge of personnel below, fill out the request for return of employment documents, and submit it via e-mail.',
                '      ③In principle, the job offerer is responsible for the cost of returning the employment documents, but the postal charges and postal service fees incurred in the case of delivery by special handling mail',
                '        Please note that the fee is borne by the job seeker.',
                '      ※Recruitment documents can only be submitted by e-mail',
            ],
            con6:[
                '   -Information on the interview schedule for successful applicants in the first document',
                '   -Information on passing the 2nd interview'
            ],
            con7:[
                '   -Human receptionist',
                '   -E-mail reception',
                '    Please write 1) hospice nurse "hospice nurse (coordinator) applicant OOO" in the subject line of the email and send it.',
                '   -Email address: onhospital@hanmail.net'
            ],
            con8:[
                '  -Person in charge: Personnel manager (general affairs planning team)ㅣonhospital@hanmail.net',
                '  -Tel: 051)607-0133'
            ],  
            con_title:[
                '■ Hospital INTRODUCTION', 
                '■ Recruitment fields',
                '■ Preferential treatment',
                '■ ON Hospital`s special employee benefits',
                '■ Submission documents',
                '■ Selection method',
                '■ How to apply',
                '■ Inquiries'
            ], 
            img_src:'recruitment/2022년_호스피스_전문간호사_코디네이터_채용공고_마감.jpg'},
        {cate_no:3, item_no:8, 
            title:'[Closed] 2022 ON Hospital Hospice Nurse Recruitment Announcement', 
            date:['2022.06.16','(14:22:22)'], 
            date2:['22.06.16','(14:22:22)'], 
            writer:'ON Hospital', 
            con1:[
                ' ON Hospital was opened in March 2010 based on Christian ideology',
                'It is a hospital that has grown significantly internally and externally in a short period of time, including a certified medical institution by the Ministry of Health and Welfare, an intern training hospital, a doctor training institution, a comprehensive nursing service pilot project institution, and a local emergency medical institution.',
                'It is also planned to expand to 800 beds in the future.',
                'Located in Seomyeon, the center of Busan, it is directly connected to Buam Station (ON Hospital Station) of subway line 2, making it the most accessible and convenient urban general hospital.'
            ],
            con2:[
                ' 1)Hospice ward nurse', 
                '     - Completion of hospice education',
                '       I have a sense of mission as a hospice ward nurse, and I would like to ask for your support as a warm-hearted nurse.'
            ],
            con3:[
                ' -Experienced applicants preferred',
                ' -In the case of veterans and disabled people, preferential treatment is given according to the relevant laws.'
            ],
            con4:[
                ' 1.Full reduction of medical expenses (ON Hospital, Jeonggeun Eye Hospital)',
                '2.Patient INTRODUCTION Incentive payment',
                ' 3.Free use of staff cafeteria',
                ' 4.Free dormitory provided (limited to those who work in the 3rd shift)',
                ' 5.Overseas training for ward shift workers and friendly staff',
                ' 6.All staff summer retreat & sports meet',
                ' 7.Special support for club activities',
                ' 8.Participation in overseas medical volunteering (hosted by Green Doctors)',
                ' 9.Payment of birthday gifts, congratulations and condolences vacations, and congratulations and condolences money',
                ' 10.Employee Relations Association operation',
                '11.On Scholarship Foundation Benefit Grant (scheduled)'
            ],
            con5:[
                ' 가)Resume, self-INTRODUCTION 1 copy (form of the main office)',
                '     ①According to Article 11 of the Act on Fair Recruitment Procedures, job seekers` recruitment documents are kept for 180 days, after which they are destroyed in accordance with the Personal Information Protection Act.',
                '      ②If you wish to return employment documents, please contact the person in charge of personnel below, fill out the request for return of employment documents, and submit it via e-mail.',
                '      ③In principle, the job offerer is responsible for the cost of returning the employment documents, but the postal charges and postal service fees incurred in the case of delivery by special handling mail',
                '        Please note that the fee is borne by the job seeker.',
                '      ※Recruitment documents can only be submitted by e-mail',
                '      ※Recruitment may be canceled if information such as resume and career is different from the facts.'
            ],
            con6:[
                '   -Information on the interview schedule for successful applicants in the first document',
                '   -Information on passing the 2nd interview'
            ],
            con7:[
                '   -Human receptionist',
                '   -E-mail reception',
                '    Please write 1) hospice nurse "hospice nurse (coordinator) applicant OOO" in the subject line of the email and send it.',
                '   -Email address: onhospital@hanmail.net'
            ],
            con8:[
                '  -Person in charge: Personnel manager (general affairs planning team)ㅣonhospital@hanmail.net',
                '  -Tel: 051)607-0133'
            ], 
            con_title:[
                '■ Hospital INTRODUCTION', 
                '■ Recruitment fields',
                '■ Preferential treatment',
                '■ ON Hospital`s special employee benefits',
                '■ Submission documents',
                '■ Selection method',
                '■ How to apply',
                '■ Inquiries'
            ],
            img_src:'recruitment/2022년_호스피스_병동_간호사_채용공고_마감.jpg'},
        {cate_no:3, item_no:7, 
            title:'[Announcement] 2022 ON Hospital Nurse, Nursing Assistant (Ward, Treatment) Recruitment Notice', 
            date:['2022.06.16','(14:14:07)'], 
            date2:['22.06.16','(14:14:07)'], 
            writer:'ON Hospital', 
            con1:[
                ' ON Hospital was opened in March 2010 based on Christian ideology',
                'It is a hospital that has grown significantly both internally and externally in a short period of time, including a certified medical institution by the Ministry of Health and Welfare, an intern training hospital, a doctor training institution, a comprehensive nursing service pilot project institution, and a local emergency medical institution.',
                'It is also planned to expand to 800 beds in the future.',
                'Located in Seomyeon, the center of Busan, it is directly connected to Buam Station (ON Hospital Station) of subway line 2, making it the most accessible and convenient urban general hospital.'
            ],
            con2:[
                ' 1) QPS Team Leader - 5 years experience',
                ' 2) QPS nurse',
                ' 3) Ward nursing assistant',
                ' 4) Operating room PA nurse',
                ' 5) Operating room scrub nurse',
                ' 6) Operating room therapist (nursing assistant)',
                ' 7) Liver PA nurse',
                ' 8) Shift nurses - Ward, emergency room, intensive care unit 2nd shift/3rd shift',
                ' 9) DEPARTMENT OF GASTROENTEROLOGY PA NURSE',
                ' 10) Department of Hepatobiliary and Pancreatic Surgery PA nurse'
            ],
            con3:[
                ' -Experienced applicants preferred',
                ' -In the case of veterans and disabled people, preferential treatment is given according to the relevant laws.'
            ],
            con4:[
                ' 1.Full reduction of medical expenses (ON Hospital, Jeonggeun Eye Hospital)',
                '2.Patient INTRODUCTION Incentive payment',
                ' 3.Free use of staff cafeteria',
                ' 4.Free dormitory provided (limited to those who work in the 3rd shift)',
                ' 5.Overseas training for ward shift workers and friendly staff',
                ' 6.All staff summer retreat & sports meet',
                ' 7.Special support for club activities',
                ' 8.Participation in overseas medical volunteering (hosted by Green Doctors)',
                ' 9.Payment of birthday gifts, congratulations and condolences vacations, and congratulations and condolences money',
                ' 10.Employee Relations Association operation',
                '11.On Scholarship Foundation Benefit Grant (scheduled)'
            ],
            con5:[
                ' 가)Resume, self-INTRODUCTION 1 copy (form of the main office)',
                '     ①According to Article 11 of the Act on Fair Recruitment Procedures, job seekers` recruitment documents are kept for 180 days, after which they are destroyed in accordance with the Personal Information Protection Act.',
                '      ②If you wish to return employment documents, please contact the person in charge of personnel below, fill out the request for return of employment documents, and submit it via e-mail.',
                '      ③In principle, the job offerer is responsible for the cost of returning the employment documents, but the postal charges and postal service fees incurred in the case of delivery by special handling mail',
                '        Please note that the fee is borne by the job seeker.',
                '      ※Recruitment documents can only be submitted by e-mail',
                '      ※Recruitment may be canceled if information such as resume and career is different from the facts.'
            ],
            con6:[
                '   -Information on the interview schedule for successful applicants in the first document',
                '   -Information on passing the 2nd interview'
            ],
            con7:[
                '   -Human receptionist',
                '   -E-mail reception',
                '    1) QPS Team Leader_"QPS Team Leader Nurse Applicant OOO"',
                ' 2)QPS team member_"QPS team member applicant OOO"', 
                '3)Ward Nursing Assistant_"Nursing Assistant Applicants OOO"', 
                '4)Operating Room PA Nurse_"Operating Room PA Applicants OOO"',
                '5)Operating room scrub nurse_"Operating room scrub applicant OOO"',
                '6)Operating room healer_Please fill out and send "applicant for healer OOO"',
                '   -Email Address',
                ': onhospital@hanmail.net'
            ],
            con8:[
                '  -Person in charge: Personnel manager (general affairs planning team)ㅣonhospital@hanmail.net',
                '  -Tel : 051)607-0133'], 
            con_title:[
                '■ Hospital INTRODUCTION', 
                '■ Recruitment fields',
                '■ Preferential treatment',
                '■ ON Hospital`s special employee benefits',
                '■ Submission documents',
                '■ Selection method',
                '■ How to apply',
                '■ Inquiries'
            ], 
            img_src:'recruitment/2022년_간호사_간호조무사_채용공고_공고.jpg'},
        // {cate_no:3, item_no:6, 
        //     title:'[마감]2022년 ON Hospital 간호사(QPS간호사, 교육전담간호사) 채용공고', 
        //     date:['2022.05.27','(17:07:34)'], 
        //     date2:['22.05.27','(17:07:34)'], 
        //     writer:'ON Hospital',
        //     con1:[' ON Hospital은 기독교이념을 바탕으로 2010년 3월 개원하였으며, 20개 DEPARTMENT목 500병상 규모로 70여명의 의료진과 700여명의 직원이 근무 중인 종합병원입니다.','보건복지부 인증의료기관, 인턴수련병원, 의사연수교육기관, 포괄간호서비스 시범사업기관, 지역응급의료기관 등 짧은 기간에 내·외적으로 크게 성장해온 병원입니다.','또한 향후 800병상 규모로 증축을 예정 하고 있습니다.','Located in Seomyeon, the center of Busan, it is directly connected to Buam Station (ON Hospital Station) of subway line 2, making it the most accessible and convenient urban general hospital.'],
        //     con2:[' 1)QPS팀장 - 경력5년',' 2)QPS간호사',' 3)간호간병통합병동 간호교육전담간호사','    -경력 5년 이상 중 병동근무경력 1년 이상 필수', '   -주40시간'],
        //     con3:'-보훈대상자 및 장애인의 경우 관련법에 의하여 우대합니다.',
        //     con4:[' 1.진료비 전액 감면혜택(ON Hospital, 정근안과병원)','2.환자 INTRODUCTION 인센트브 지급',' 3.직원식당 무료 이용',' 4.기숙사 무료제공(3교대 근무자에 한함)',' 5.병동교대근무 근속자 및 친절직원 해외연수',' 6.전직원 여름수련회&체육대회',' 7.동아리활동 특별지원',' 8.해외의료봉사 참여(그린닥터스 주관)',' 9.생일선물, 경조휴가 및 경조금 지급',' 10.직원상조회 운영','11.온장학재단 혜택부여(예정)'],
        //     con5:[' 가)이력서, 자기INTRODUCTION서 1부(본원양식)','     ①채용절차의 공정화에 관한 법률 제11조에 따라 구직자의 채용서류는 180일간 보관되며 이후 개인정보 보호법에 따라 채용서류는 파기됩니다.','      ②채용서류 반환을 원하시는 분들은 하단 인사담당자에게 연락하셔서 채용서류 반환청구서를 작성하신 후 전자우편으로 제출 부탁드립니다.','      ③채용서류의 반환에 소요되는 비용은 원칙적으로 구인자가 부담하지만 특수취급우편물로 송달하는 경우에 드는 우편에 관한 요금 및 우편이용에 관한','        수수료는 구직자가 부담함을 알려드립니다.','      ※채용서류는 이메일로만 접수 가능합니다.(우편, 방문접수 불가)','      ※이력, 경력 등의 정보가 사실과 다를시 채용이 취소될 수 있습니다.'],
        //     con6:['  -이메일 제목을 1)"QPS팀장 간호사 지원자 OOO"','                       2)"QPS간호사 지원자 OOO"','                       3)"교육전담간호사 지원자 OOO"로 작성하여 보내주십시오.','   -이메일 주소 ',': onhospital@hanmail.net'],
        //     con7:['  -담당자 : 인사담당자(총무기획팀)ㅣonhospital@hanmail.net','  -전화 : 051)607-0133'], 
        //     con_title:['■병원INTRODUCTION', '■모집분야','■우대사항','■ON Hospital만의 특별한 직원복리후생','■제출서류','■전형방법','■문의사항'], 
        //     img_text:'ON Hospital에서 2022년 간호사(QPS간호사, 교육전담간호사) 채용을 아래와 같이 진행하오니 많은 관심과 지원바랍니다.',
        //     img_src:'recruitment/2022년_QPS_교육전담간호사_채용공고_마감.jpg'
        // },
        // {cate_no:3, item_no:5, 
        //     title:'[마감]2022년 ON Hospital 간호사, 간호조무사, 도우미 모집', 
        //     date:['2022.05.27','(17:07:05)'], 
        //     date2:['22.05.27','(17:07:05)'], 
        //     writer:'ON Hospital',
        //     con1:[' ON Hospital은 기독교이념을 바탕으로 2010년 3월 개원하였으며, 20개 DEPARTMENT목 500병상 규모로 70여명의 의료진과 700여명의 직원이 근무 중인 종합병원입니다.','보건복지부 인증의료기관, 인턴수련병원, 의사연수교육기관, 포괄간호서비스 시범사업기관, 지역응급의료기관 등 짧은 기간에 내·외적으로 크게 성장해온 병원입니다.','또한 향후 800병상 규모로 증축을 예정 하고 있습니다.','Located in Seomyeon, the center of Busan, it is directly connected to Buam Station (ON Hospital Station) of subway line 2, making it the most accessible and convenient urban general hospital.'],
        //     con2:[' 1)PA간호사(간췌담도SURGERY, 비뇨기과, Liver, DEPARTMENT OF <SPAN>RESPIRATORY MEDICINE</SPAN>, 혈액종양학과)',' 2)수술어시스트(간호사, 간호조무사)',' 3)교대근무간호사(병동, 중환자실, 응급실)(D-keep, E-keep, 파트타임 가능)','4)코로나병동 (간호사, 간호조무사, 도우미)'],
        //     con3:['-경력자 우대', '-보훈대상자 및 장애인의 경우 관련법에 의하여 우대합니다.'],
        //     con4:[' 1.진료비 전액 감면혜택(ON Hospital, 정근안과병원)','2.환자 INTRODUCTION 인센트브 지급',' 3.직원식당 무료 이용',' 4.기숙사 무료제공(3교대 근무자에 한함)',' 5.병동교대근무 근속자 및 친절직원 해외연수',' 6.전직원 여름수련회&체육대회',' 7.동아리활동 특별지원',' 8.해외의료봉사 참여(그린닥터스 주관)',' 9.생일선물, 경조휴가 및 경조금 지급',' 10.직원상조회 운영','11.온장학재단 혜택부여(예정)'],
        //     con5:[' 가)이력서, 자기INTRODUCTION서 1부(본원양식)','     ①채용절차의 공정화에 관한 법률 제11조에 따라 구직자의 채용서류는 180일간 보관되며 이후 개인정보 보호법에 따라 채용서류는 파기됩니다.','      ②채용서류 반환을 원하시는 분들은 하단 인사담당자에게 연락하셔서 채용서류 반환청구서를 작성하신 후 전자우편으로 제출 부탁드립니다.','      ③채용서류의 반환에 소요되는 비용은 원칙적으로 구인자가 부담하지만 특수취급우편물로 송달하는 경우에 드는 우편에 관한 요금 및 우편이용에 관한','      ※채용서류는 이메일로만 접수 가능합니다.(우편, 방문접수 불가)','      ※이력, 경력 등의 정보가 사실과 다를시 채용이 취소될 수 있습니다.'],
        //     con6:['-1차 서류 합격자 면접일정안내', '-2차 면접 합격여부 안내'],
        //     con7:['-사람인 접수', '-이메일 접수', '이메일 제목을 1) PA간호사 " 지원부서 PA간호사 지원자 000 "', '                    2) 수술어시스트 "어시스트 간호사 지원자 000", "어시스트 간호조무사 지원자 000"','                    3) 교대근무간호사 "지원부서 간호사 지원자 000"','                    4) 코로나병동 "코로나병동 간호사 000", "코로나병동 간호조무사 000", "코로나병동 도우미 000"로 작성하여 보내주십시오.','이메일 : onhospital@hanmail.net'],
        //     con8:['  -담당자 : 인사담당자(총무기획팀)ㅣonhospital@hanmail.net','  -전화 : 051)607-0133'], 
        //     con_title:['■병원INTRODUCTION', '■모집분야','■우대사항','■ON Hospital만의 특별한 직원복리후생','■제출서류','■전형방법','■ 접수방법','■문의사항'], 
        //     img_text:'ON Hospital은 간호사, 간호조무사, 도우미 채용을 아래와 같이 진행하오니 많은 관심과 지원바랍니다.',
        //     img_src:'recruitment/2022년_간호사_간호조무사_도우미_모집_마감.jpg'
        // },
        // {cate_no:3, item_no:4, 
        //     title:'[마감]2022년 ON Hospital 간호사/간호조무사 채용', 
        //     date:['2022.05.27','(17:06:39)'], 
        //     date2:['22.05.27','(17:06:39)'], 
        //     writer:'ON Hospital',
        //     con1:[' ON Hospital은 기독교이념을 바탕으로 2010년 3월 개원하였으며, 20개 DEPARTMENT목 500병상 규모로 70여명의 의료진과 700여명의 직원이 근무 중인 종합병원입니다.','보건복지부 인증의료기관, 인턴수련병원, 의사연수교육기관, 포괄간호서비스 시범사업기관, 지역응급의료기관 등 짧은 기간에 내·외적으로 크게 성장해온 병원입니다.','또한 향후 800병상 규모로 증축을 예정 하고 있습니다.','Located in Seomyeon, the center of Busan, it is directly connected to Buam Station (ON Hospital Station) of subway line 2, making it the most accessible and convenient urban general hospital. (출퇴근도 편리합니다.)'],
        //     con2:[' 1) 처치사(간호사, 간호조무사)',' 2) 교대근무 간호사(병동, 응급실)',' 3) PA간호사(혈액종양학과, 비뇨기과(남자), OBSTETRICS AND GYNECOLOGY, DEPARTMENT OF ORTHOPEDICS)','4) 스크럽, 마취과 간호사사'],
        //     con3:['- 경력자 우대', '- 보훈대상자 및 장애인의 경우 관련법에 의하여 우대합니다.'],
        //     con4:[' 1.진료비 전액 감면혜택(ON Hospital, 정근안과병원)','2.환자 INTRODUCTION 인센트브 지급',' 3.직원식당 무료 이용',' 4.기숙사 무료제공(3교대 근무자에 한함)',' 5.병동교대근무 근속자 및 친절직원 해외연수',' 6.전직원 여름수련회&체육대회',' 7.동아리활동 특별지원',' 8.해외의료봉사 참여(그린닥터스 주관)',' 9.생일선물, 경조휴가 및 경조금 지급',' 10.직원상조회 운영','11.온장학재단 혜택부여(예정)'],
        //     con5:[' 가)이력서, 자기INTRODUCTION서 1부(본원양식)','     ①채용절차의 공정화에 관한 법률 제11조에 따라 구직자의 채용서류는 180일간 보관되며 이후 개인정보 보호법에 따라 채용서류는 파기됩니다.','      ②채용서류 반환을 원하시는 분들은 하단 인사담당자에게 연락하셔서 채용서류 반환청구서를 작성하신 후 전자우편으로 제출 부탁드립니다.','      ③채용서류의 반환에 소요되는 비용은 원칙적으로 구인자가 부담하지만 특수취급우편물로 송달하는 경우에 드는 우편에 관한 요금 및 우편이용에 관한','        수수료는 구직자가 부담함을 알려드립니다.','      ※채용서류는 이메일로만 접수 가능합니다.(우편, 방문접수 불가)','      ※이력, 경력 등의 정보가 사실과 다를시 채용이 취소될 수 있습니다.'],
        //     con6:['-1차 서류 합격자 면접일정안내', '-2차 면접 합격여부 안내'],
        //     con7:['- 사람인 접수', ' - 이메일 접수', '   이메일 제목을  1) `처치사 간호사 지원자 OOO`, `처치사 간호조무사 지원자 OOO`','                             2) `병동 간호사 지원자 OOO`, `응급실 간호사 지원자 OOO`', '                             3) `DEPARTMENT OF HEMATO-ONCOLOGY 간호사 지원자 OOO`, `비뇨기과 간호사 지원자 OOO`, `OBSTETRICS AND GYNECOLOGY 간호사 지원자 OOO`, `DEPARTMENT OF ORTHOPEDICS', '                                 간호사 지원자 OOO`', '                             4) `스크럽 간호사 지원자 OOO`, `마취과 간호사 지원자 OOO`로 작성하여 보내주십시오.', ' 이메일 : onhospital@hanmail.net'],
        //     con8:['  -담당자 : 인사담당자(총무기획팀)ㅣonhospital@hanmail.net','  -전화 : 051)607-0133'], 
        //     con_title:['■병원INTRODUCTION', '■모집분야','■우대사항','■ON Hospital만의 특별한 직원복리후생','■제출서류','■전형방법','■접수방법','■문의사항'], 
        //     img_text:'ON Hospital은 2022년 간호사/간호조무사 채용을 아래와 같이 진행하오니 많은 관심과 지원바랍니다.',
        //     img_src:'recruitment/2022년_간호사_간호조무사_채용_마감.jpg'
        // },
        // {cate_no:3, item_no:3, 
        //     title:'[마감]2022년 ON Hospital 간호사 및 PA전문간호사 채용', 
        //     date:['2022.05.27','(17:05:57)'], 
        //     date2:['22.05.27','(17:05:57)'], 
        //     writer:'ON Hospital',
        //     con1:[' ON Hospital은 기독교이념을 바탕으로 2010년 3월 개원하였으며, 20개 DEPARTMENT목 500병상 규모로 70여명의 의료진과 700여명의 직원이 근무 중인 종합병원입니다.','보건복지부 인증의료기관, 인턴수련병원, 의사연수교육기관, 포괄간호서비스 시범사업기관, 지역응급의료기관 등 짧은 기간에 내·외적으로 크게 성장해온 병원입니다.','또한 향후 800병상 규모로 증축을 예정 하고 있습니다.','Located in Seomyeon, the center of Busan, it is directly connected to Buam Station (ON Hospital Station) of subway line 2, making it the most accessible and convenient urban general hospital.'],
        //     con2:[' 1)Urology Department PA간호사',' 2)DEPARTMENT OF ORTHOPEDICS PA간호사',' 3)Liver PA간호사','4)췌담도내과 PA간호사', '5)SURGERY(수술실 어시스트) PA간호사', '6)항암담당 PA간호사', '7)병동 교대근무간호사(응급실, 병동, 중환자실)'],
        //     con3:['- 경력자 우대','-보훈대상자 및 장애인의 경우 관련법에 의하여 우대합니다.'],
        //     con4:[' 1.진료비 전액 감면혜택(ON Hospital, 정근안과병원)','2.환자 INTRODUCTION 인센트브 지급',' 3.직원식당 무료 이용',' 4.기숙사 무료제공(3교대 근무자에 한함)',' 5.병동교대근무 근속자 및 친절직원 해외연수',' 6.전직원 여름수련회&체육대회',' 7.동아리활동 특별지원',' 8.해외의료봉사 참여(그린닥터스 주관)',' 9.생일선물, 경조휴가 및 경조금 지급',' 10.직원상조회 운영','11.온장학재단 혜택부여(예정)'],
        //     con5:[' 가)이력서, 자기INTRODUCTION서 1부(본원양식)','     ①채용절차의 공정화에 관한 법률 제11조에 따라 구직자의 채용서류는 180일간 보관되며 이후 개인정보 보호법에 따라 채용서류는 파기됩니다.','      ②채용서류 반환을 원하시는 분들은 하단 인사담당자에게 연락하셔서 채용서류 반환청구서를 작성하신 후 전자우편으로 제출 부탁드립니다.','      ③채용서류의 반환에 소요되는 비용은 원칙적으로 구인자가 부담하지만 특수취급우편물로 송달하는 경우에 드는 우편에 관한 요금 및 우편이용에 관한','        수수료는 구직자가 부담함을 알려드립니다.','      ※채용서류는 이메일로만 접수 가능합니다.(우편, 방문접수 불가)','      ※이력, 경력 등의 정보가 사실과 다를시 채용이 취소될 수 있습니다.'],
        //     con6:['-1차 서류 합격자 면접일정안내', '-2차 면접 합격여부 안내'],
        //     con7:['- 이메일 주소: onhospital@hanmail.net'],
        //     con8:['  -담당자 : 인사담당자(총무기획팀)ㅣonhospital@hanmail.net','  -전화 : 051)607-0133'], 
        //     con_title:['■병원INTRODUCTION', '■모집분야','■우대사항','■ON Hospital만의 특별한 직원복리후생','■제출서류','■전형방법','■접수방법','■문의사항'], 
        //     img_text:'ON Hospital은 PA전문간호사 채용을 아래와 같이 진행하오니 많은 관심과 지원바랍니다.',
        //     img_src:'recruitment/2022년_간호사_PA전문간호사_채용_마감.jpg'
        // },
        // {cate_no:3, item_no:2, 
        //     title:'2022년 신규 간호사 최종 합격자 발표', 
        //     date:['2022.05.27','(17:04:40)'], 
        //     date2:['22.05.27','(17:04:40)'], 
        //     writer:'ON Hospital',
        //     con1:[
        //         'ON Hospital 2022년 신규간호사 합격자 발표', 
        //         '합격을 축하합니다.', 
        //         '추후 합격자는 전체카톡으로 ON Hospital 소식을 공유하겠습니다.', 
        //         '간호사 국가고시 모두가 합격하길 기도합니다.'
        //     ],
        //     con_small:'2022년 신규간호사 최종합격자 발표 2021.10.16.xlsx',
        //     img_src:''
        // },
        // {cate_no:3, item_no:1, 
        //     title:'[마감] 총무기획팀 경력 사원 모집', 
        //     date:['2022.05.27','(16:59:32)'], 
        //     date2:['22.05.27','(16:59:32)'], 
        //     writer:'ON Hospital',
        //     con1:['ON Hospital 총무기획팀 경력직 직원채용을 아래와 같이 진행하오니 많은 관심과 지원바랍니다.'],
        // },
    ],
    // Today's Meal
    [
        {cate_no:4, 
            item_no:10, 
            title:'April 17th - April 23rd', 
            date:['2023.04.11','(16:28:40)'], 
            date2:['23.04.11','(16:28:40)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            img_src:'diet/2023_4월_17_23일.jpg'},
        {cate_no:4, 
            item_no:9, 
            title:'April 10th - April 16th', 
            date:['2023.04.06','(15:14:08)'], 
            date2:['23.04.06','(15:14:08)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            img_src:'diet/2023_4월_10_16일.jpg'
        },
        {cate_no:4, 
            item_no:8, 
            title:'April 3 - April 9', 
            date:['2023.03.30','(09:36:38)'], 
            date2:['23.03.30','(09:36:38)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            img_src:'diet/2023_4월_3_9일.jpg'
        },
        {cate_no:4, 
            item_no:7, 
            title:'March 27th - April 2nd', 
            date:['2023.03.23','(16:42:46)'], 
            date2:['23.03.23','(16:42:46)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            img_src:'diet/2023_3월_27_4월_2일.jpg'
        },
        {cate_no:4, 
            item_no:6, 
            title:'March 20th - March 26th', 
            date:['2023.03.16','(14:35:26)'], 
            date2:['23.03.16','(14:35:26)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            img_src:'diet/2023_3월_20_26일.jpg'
        },
        {cate_no:4, 
            item_no:5, 
            title:'March 13th - March 19th', 
            date:['2023.03.08','(17:37:03)'], 
            date2:['23.03.08','(17:37:03)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            img_src:'diet/2023_3월_13_19일.jpg'
        },
        {cate_no:4, 
            item_no:4, 
            title:'March 6th - March 12th', 
            date:['2023.03.02','(16:31:12)'], 
            date2:['23.03.02','(16:31:12)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            img_src:'diet/2023_3월_6_12일.jpg'
        },
        {cate_no:4, 
            item_no:3, 
            title:'February 27th - March 5th', 
            date:['2023.02.23','(14:00:57)'], 
            date2:['23.02.23','(14:00:57)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            img_src:'diet/2023_2월_27_3월_5일.jpg'
        },
        {cate_no:4, 
            item_no:2, 
            title:'February 20th - February 26th', 
            date:['2023.02.16','(09:59:14)'], 
            date2:['23.02.16','(09:59:14)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            img_src:'diet/2023_3월_20_26일.jpg'
        },
        {cate_no:4, 
            item_no:1, 
            title:'February 13th - February 19th', 
            date:['2023.02.08','(13:27:35)'], 
            date2:['23.02.08','(13:27:35)'], 
            writer:'ON Group Medical Foundation ON Hospital', 
            img_src:'diet/2023_2월_13_19일.jpg'
        },

    ],
    // Frequently Asked Questions
    [
        {cate_no:5, 
            item_no:10, 
            title:'How to reissue health certificate', 
            date:['2022.05.27','(16:56:58)'], 
            date2:['22.05.27','(16:56:58)'], 
            writer:'ON Hospital', 
            const:['Do I have to visit in person to reissue the health certificate?', 'Is there any way to issue it online?']},
        {cate_no:5, 
            item_no:9, 
            title:'Hospitalization room access time for inpatient guardians', 
            date:['2022.05.27','(16:56:48)'], 
            date2:['22.05.27','(16:56:48)'], 
            writer:'ON Hospital', 
            const:['I am an inpatient caregiver', 'Is there a time limit for entering the hospital room?', 'I am going today', 'please answer about my question']},
        {cate_no:5, 
            item_no:8, 
            title:'Where are the required documents for issuance of documents??', 
            date:['2022.05.27','(16:56:36)'], 
            date2:['22.05.27','(16:56:36)'], 
            writer:'ON Hospital', 
            const:['You can check it in ABOUT → Medical Information → Certificate Issuance in the upper MENU.']},
        {cate_no:5, 
            item_no:7, 
            title:'Where can I find my doctor`s timetable?', 
            date:['2022.05.27','(16:56:17)'], 
            date2:['22.05.27','(16:56:17)'], 
            writer:'ON Hospital', 
            const:[
                'After selecting [DEPARTMENT/medical staff] at the top of MENU, click the relevant DEPARTMENT to check..', 
                'If it is written as an inquiry, you can check the relevant DEPARTMENT number in [Hospital Information] → [Contact No.] and make an inquiry by phone.']},
        {cate_no:5, 
            item_no:6, 
            title:'Online reservations are not available. is it an error?', 
            date:['2022.05.27','(16:56:05)'], 
            date2:['22.05.27','(16:56:05)'], 
            writer:'ON Hospital', 
            const:['If online reservation is not possible, it is a DEPARTMENT that cannot be reserved. After contacting the relevant DEPARTMENT by phone, receive information on the timetable, visit the hospital, and receive treatment from the hospital administration team.']
        },
        // {cate_no:5, 
        //     item_no:5, 
        //     title:'보건증 검사를 원합니다. 어디로 가면 되나요? 기본 안내사항도 알려주세요.', 
        //     date:['2022.05.27','(16:55:53)'], 
        //     date2:['22.05.27','(16:55:53)'], 
        //     writer:'ON Hospital', 
        //     const:[
        //         '보건증 검사는 서면 롯데백화점 맞은편 정근 안과 건물, 건강 검진 서면 센터 7층에서 가능합니다.',
        //         '예약은 따로 필요 없이 점심시간을 제외하고 신분증 지참 후 방문해주시면 됩니다.',
        //         '검사 비용은 15,000원이며 검사 결과 직접 수령은 5일, 우편 수령은 10일 이상 소요됩니다.',
        //         'AM 접수는 12시 이전까지 와주셔야 가능하며, 식사 여부는 상관 없습니다.',
        //         '추가 문의사항은 051)607-0784, 0301 연락해주시면 됩니다.'
        //     ]
        // },
        // {cate_no:5, 
        //     item_no:4, 
        //     title:'개인 택시 기사 자격 검사도 시행 중인가요?', 
        //     date:['2022.05.27','(16:55:10)'], 
        //     date2:['22.05.27','(16:55:10)'], 
        //     writer:'ON Hospital', 
        //     const:['서면 롯데백화점 맞은편 정근 안과 건물, 건강 검진 서면 센터 5층에서 가능하며,','추가 문의사항은 051)607-0301 연락해주시면 됩니다.'], 
        // },
        // {cate_no:5, 
        //     item_no:3, 
        //     title:'온라인 예약이 되지를 않습니다. 오류인가요?', 
        //     date:['2022.05.27','(16:56:05)'], 
        //     date2:['22.05.27','(16:56:05)'], 
        //     writer:'ON Hospital', 
        //     const:['온라인 예약이 되지 않는 경우는 예약이 불가능한 DEPARTMENT입니다. 해당 DEPARTMENT 전화 문의 후 시간표 안내받으시고 내원하시어 원무팀 접수 후 진료 부탁드립니다.']
        // },
        // {cate_no:5, 
        //     item_no:2, 
        //     title:'운전 면허 발급용 검사도 온 종합병원 본원에서 가능한가요?', 
        //     date:['2022.05.27','(16:55:00)'], 
        //     date2:['22.05.27','(16:55:00)'], 
        //     writer:'ON Hospital', 
        //     const:['서면 롯데백화점 맞은편 정근 안과 1층에서 가능합니다.', '비용은 1종 보통 5,000원, 대형 6,000원이며 추가 문의사항은 051)668-8000 연락해주시면 됩니다. ']
        // },
        // {cate_no:5, 
        //     item_no:1, 
        //     title:'점심시간이 있나요? 있으면 시간을 알려주세요.', 
        //     date:['2022.05.27','(16:54:44)'], 
        //     date2:['22.05.27','(16:54:44)'], 
        //     writer:'ON Hospital', 
        //     const:['월~금요일은 PM 12:30 ~ PM 1:30로 동일하며, 토요일은 점심시간 없이 진료 가능합니다.']
        // },
    ],
]