const CENT_LIST = [
    [
        {cate_no:0, 
            item_no:1, 
            img_src:'', 
            sub_title:['', ''], 
            icon_src:'medi_icon_15_1',
            name:'Pancreatic and Colorectal Cancer Center',
            sub_context3: ['At ON Hospital, specialists in gastroenterology, oncology, hepatobiliary surgery, radiation oncology, radiology, and pathology with rich clinical experience and expertise collaborate to establish an organic system that is patient-centered from diagnosis to treatment, providing prompt diagnosis and personalized treatment for each patient.'],
            sub_context2: ['Generally, the prognosis for malignant tumors of the biliary tract and pancreas is worse compared to other organ malignancies.','In addition, specialized diagnosis and treatment including diagnosis, surgery, neoadjuvant and adjuvant chemotherapy, and radiation therapy are provided for malignant tumors of the biliary tract and pancreas to improve patient outcomes and quality of life.'],
            sub_context1: ['As various treatment methods for liver and pancreatic cancer have been developed and utilized, good results can be expected when optimal treatment is received.','Furthermore, specialized diagnosis and treatment such as diagnosis, surgery, pre- and post-operative chemotherapy, and radiation therapy are provided for malignant tumors in the bile duct and pancreas, thereby promoting improvement in the patient`s treatment rate and quality.'] },
        {cate_no:0, 
            item_no:2, 
            img_src:['2_1.jpg', '2_2.jpg'], 
            sub_title:['',''], 
            icon_src:'medi_icon_15_1',
            name:'Liver Center',
            num:['051) 607-0350', '051) 607-0745/0257'],
            num_bold:['Liver Center Outpatient Clinic','(3F)', 'Liver Center Reception/Payment'],
            table_th:['High-frequency ablation therapy', 'Transarterial chemoembolization (TACE)', 'Transarterial chemoinfusion therapy'],
            table_td:['A liver cancer treatment that involves inserting acupuncture needles into early-stage liver cancer of 3cm or less and flowing high-frequency waves, producing a minimum of 50 degrees Celsius or higher, to destroy liver cancer cells', 'A treatment method for malignant liver lesions that aims for complete cure, targeting multiple and giant cancer tumors. This method involves injecting anti-cancer agents slowly through the hepatic artery to the liver', 'A procedure that involves injecting chemotherapy agents and blocking the necessary blood vessels for tumor growth through the hepatic artery. This is a surgical procedure that blocks the necessary blood vessels for the tumor growth with both chemotherapy agents and embolic material'],
            sub_context1: ['Offering a new hope with a treatment success rate of 60% for those suffering from liver cancer!', 'Composed of liver specialists with a university professor background', 'Successfully performed the first thoracoscopic lobectomy in Busan and Gyeongsangnam-do'] },
        {cate_no:0, 
            item_no:3, 
            img_src:'', 
            icon_src:'medi_icon_15_1',
            name:'Infection Control Center',
            sub_title:[ '','Main tasks of the Infection Control Team'], 
            text:'Cooperating with the Infection Control Committee to carry out healthcare-related infection prevention and management activities.',
            li_text:['Establishing and revising infection control regulations', 'Monitoring healthcare-related infections and their management', 'Managing infectious disease outbreaks', 'Managing legal infectious diseases', 'Managing the cleaning, disinfection, and sterilization of medical equipment', 'Providing education and promotion of infection control', 'Managing infections among hospital staff', 'Environmental management','Consultation on infection control', 'Fostering local community networks for infection control activities'],
            sub_context1: ['To provide a safe environment from healthcare-related infections for both patients and visitors, the hospital performs activities to recognize and reduce the risk of infection transmission among all individuals exposed to the hospital environment','Cooperating with the Infection Control Committee to carry out healthcare-related infection prevention and management activities.']  },
        {cate_no:0, 
            item_no:4, 
            img_src:'4_.jpg', 
            sub_title:['INTRODUCTION', 'SPECIALIZED CLINICS'], 
            sub_context5: ['fistula, anal fissure, pilonidal disease, anal pain, anal prolapse, anorectal infections','Constipation or bowel dysfunction, irritable bowel syndrome, inflammatory bowel diseases',],
            sub_context4: ['The center provides patients with treatment opportunities through various methods, including minimally invasive surgery.','It also provides specialized treatments through the cooperation of specialized clinical departments.','In particular, the center strives to provide fast and comfortable treatment from colorectal cancer to anorectal diseases that require high-level surgical procedures. It is responsible for linking with the special clinics and providing appropriate treatment for the causes of anorectal diseases, as well as treating anorectal diseases.',],
            sub_context3: ['Additionally, the frequency of various functional anorectal diseases is also rapidly increasing.','In this context, the Colorectal Center at ON Hospital offers the highest level of medical care with top-notch medical equipment and excellent specialists. Even for the same disease, the optimal treatment can vary depending on the patient`s condition and the progression of the disease.',],
            sub_context2: ['As modernization and Westernization continue, the incidence of colorectal diseases is expected to increase. Colorectal cancer has become the most rapidly increasing cancer over the past decade and is the fourth most common cancer in Korea.',],
            sub_context1: ['The Colorectal Center at ON Hospital aims to deliver accurate knowledge and consultation on colorectal diseases, as well as provide optimal treatment for patients.',] },
        {cate_no:0, 
            item_no:5, 
            img_src:'5_.jpg', 
            sub_title:['Attention Deficit Hyperactivity Disorder(ADHD)', 'Learning Disability', 'School phobia - separation anxiety disorder', 'Asperger`s syndrome and bullying'], 
            bold_top:['"Every morning, I don`t want to go to school"', '"I think I`m smart, but my grades are not good"', '"I feel like I`m being bullied by my peers at school."'],
            small_top:['For children who step out of the family fence and enter into another world, school life can be a challenge and an adventure. The Child and Adolescent Mental Health Center specializes in the diagnosis and treatment of common mental health disorders in children and adolescents, such as conduct disorder, learning disabilities, Asperger`s syndrome, and separation anxiety disorder.'],
            sub_context8:['In addition, neurofeedback therapy and psychological testing are conducted, and counseling and treatment for adult mental health are also available, not only for children and adolescents.'],
            sub_context7: ['Despite their high intelligence and unique interests, they often struggle to adapt to family or school life and experience significant disabilities. However, there have been cases where they later became university professors or artists. ', '다만 특수교육을 통해 사회적응능력을 키워주고 반복적인 좌절로 인한 우울 증세를 치료하는 것이 필요하다.'],
            sub_context6: ['People with Aspergers syndrome have sufficient judgment and language skills, but they often fail in social interaction and emotional communication.','There is no fundamental cure for this condition currently, but it is necessary to improve their social adaptation skills and treat depression caused by repeated frustration through special education.'],
            sub_context5: ['If the separation anxiety is severe, it may be a solution to go to school with the child and wait outside the classroom or attend classes together for up to one month, rather than forcing them to go alone. If there is no improvement, it is recommended to seek counseling from a pediatric psychiatrist. Play therapy, art therapy, and parent education can be provided after identifying the cause through psychological tests, and medication therapy can also be applied.'],
            sub_context4: ['School phobia refers to cases where a child repeatedly refuses to go to school and becomes anxious or experiences panic attacks when forced to go.','Rather than fearing school itself, it can be said that the child is afraid of being separated from their mother. They may complain of physical symptoms such as stomach aches or headaches when it`s time for school in the morning or on weekends. If forced to go, they may become anxious, exhibit extreme resistance, or even try to hide or run away. In such cases, it is necessary to make going to school a rule for the child, regardless of what excuses they come up with.',],
            sub_context3: ['Since the causes of learning disabilities are diverse, it is important to identify the difficulties that the child is experiencing and find the underlying cause. Apart from attention deficit hyperactivity disorder, medication is not the primary treatment for learning disabilities. Adequate educational approaches and environmental and emotional support are important.','Occasionally, some parents consider their children to have learning disabilities when they do not. In today`s world, where parents tend to raise one or two children, it is common for parents to rush their children and have high expectations, leading to misconceptions about their children`s learning abilities.'],
            sub_context2: ['A learning disability refers to a situation where an individual has a normal or above-average intelligence quotient but experiences a lower academic performance due to functional abnormalities in the brain and nervous system.','It is a developmental disorder that occurs during the brain and nervous system`s developmental processes. Learning disabilities can appear in areas such as listening, thinking, speaking, reading, spelling, and mathematical calculations. In addition to learning disabilities, there are also "learning delays" that occur in children with an intelligence quotient below 70 or who have organic brain damage, and "learning underachievement" in those who have an intelligence quotient of about 75-85, but suffer from emotional or environmental problems.',],
            sub_context1: ['Attention Deficit Hyperactivity Disorder (ADHD), which has been gaining attention in various media outlets recently, is characterized by frequent talking, lack of stillness, and impulsivity, often resulting in careless mistakes.','It is common for children to show signs of being fussy or highly active from infancy, and ADHD is often detected when they begin group activities in kindergarten or elementary school. It is reported that ADHD is 3-4 times more prevalent in boys than girls. About 70-80% of cases are known to develop before the age of 4.','Experts attribute the causes of ADHD to genetic factors, abnormalities in neurotransmitters due to decreased prefrontal lobe function in the brain, brain injuries during birth, and so on. If symptoms arise, it is not the fault of the child or the parent, and they should not blame themselves. If the problem is not severe, environmental adjustment, parental counseling, and behavior modification methods should be prioritized without medication. However, in severe cases, medication such as central nervous system stimulants and antidepressants should be used.']  },
        {cate_no:0, 
            item_no:6, 
            img_src:'6_.jpg', 
            sub_title:['INTRODUCTION', 'SPECIALIZED CLINICS'], 
            sub_context2:[
                'Specializing in gastrointestinal diseases (stomach, esophagus), gastritis, gastric ulcers, and reflux esophagitis', 
                'Specializing in pancreatic and biliary tract diseases, liver diseases', 
                'Upper Gastrointestinal Nerve Center, colonoscopy, endoscopic mucosal resection/ Gastrointestinal Nerve Center clinic'
            ] , 
            sub_context1: [
                'With the reality of Korean eating habits becoming more westernized, there has been an increasing trend in patients with gastrointestinal disorders.',
                'To provide high-quality medical services, ON Hospital has established a Gastrointestinal Nerve Center center based on an organic collaboration system of medical departments related to gastrointestinal diseases, such as gastroenterology, surgery, and radiology.',
                'The Gastrointestinal Nerve Center Center at ON Hospital has state-of-the-art medical staff, advanced medical equipment, and a sophisticated medical system in place to enable patients to receive high-level medical treatment quickly and comfortably.', 
                'In addition, to alleviate the increasing backlog of endoscopic exams due to the rising number of hospital visits by patients with gastrointestinal disorders, specialized medical staff for endoscopic exams have been trained and dispatched, and state-of-the-art medical equipment has been acquired for efficient management of personnel and equipment, ensuring differentiated endoscopic exams.', 
                'Based on the highest level of clinical experience and advanced technology in each field, we strive to provide world-class medical care.',
                ' 이에 온 종합병원 소화기내시경센터는 환자들이 좀 더 편리하게 최상의 진료를 받을 수 있도록 끊임없이 노력하겠습니다.'
            ], 
            },
        {cate_no:0, 
            item_no:7, 
            img_src:'page-img1.jpg', 
            sub_title:['Department of Liver, Biliary and Pancreatic Surgery','Surgery', 'Digestive Endoscopy Center'], 
            black_bold:['Stomach and Colon Endoscopy Clinic', 'Liver and Bile Duct Clinic'],
            small_phone:['051) 607-0707', '051) 607-0230', '051) 607-0244,0257'],
            chk_text:[
                'The top-notch medical facility of university hospital grade with advanced technology is available', 
                'Immediate surgery and hospitalization one-stop service upon detection of a tumor', 
                'Reservations for upper and lower gastrointestinal endoscopies available on desired dates', 
                'Explanation of test results immediately after the examination', 
                'Specialized procedure for liver, biliary and pancreatic ERCP (Endoscopic Retrograde Cholangio-Pancreatography)', 
                'Ultrasonic disinfection of endoscopic equipment'
            ],
            sub_context1: [
                'This department specializes in treating diseases that occur in the most difficult areas of surgery, such as the liver, bile duct system, spleen, pancreas, and other organs', 
                'Professor Park Kwang-min has succeeded in liver, biliary, and pancreatic surgeries more than 10,000 times', 
                'Specialized in the treatment of stomach cancer, colorectal cancer, rectal cancer, and other large intestine diseases', 
                'Equipped with the highest specification and clearest image quality, using the Olympus CV290 equipment'
            ] 
        },
        {cate_no:0, 
            item_no:8, 
            img_src:'8_.jpg', 
            sub_title:['The following are the diseases and symptoms treated at the Neurology Center.', ''], 
            table_td:[
                'The center diagnoses and treats dementia and memory impairment, which have become social problems as society ages.',
                'The center identifies and treats the causes of seizure attacks that exhibit repetitive loss of consciousness and limb convulsions.', 
                'The center treats and prevents hemiplegia and language disorders caused by cerebral infarction and cerebral hemorrhage.', 
                'The center diagnoses and treats movement disorders such as tremors and Parkinson`s disease.', 
                'The center identifies and treats causes such as numbness in hands and feet, muscle weakness, muscle atrophy, facial paralysis, and drooping eyelids.', 
                'Common headaches can be an initial symptom of brain disease. The center distinguishes the causes of headaches and treats them.',
                'The center diagnoses and treats insomnia, sleep attacks, excessive daytime sleepiness, and sleep apnea.',
                'The center identifies and treats the causes of dizziness, which requires sophisticated neurological functions to maintain balance.', 
                'The center diagnoses and treats meningitis and encephalitis accompanied by fever, headache, and vomiting.', 
                'In addition to the above-mentioned diseases, the center diagnoses and treats neuropathic pain, multiple sclerosis, congenital or hereditary neurological disorders, and other related conditions.'
            ],
            table_th:[
                'Dementia', 
                'Epilepsy', 
                'Stroke', 
                'Movement disorders', 
                'Peripheral nerve and muscle disorders', 
                'Headache', 
                'Sleep disorders', 
                'Dizziness', 
                'Neurological inflammation', 
                'Other diseases'
            ],
            sub_context1: [
                'The Neurology Center at the ON Hospital diagnoses and treats diseases that occur in the brain and spinal cord (central nervous system), peripheral nerves, and muscles. The center also investigates the causes of neurological disorders and conducts research for better treatment methods.', 
                'With specialized clinics such as the Multiple Sclerosis Clinic, Epilepsy Clinic, Stroke Clinic, Peripheral Nerve and Muscle Disorders Clinic, as well as neurological psychology testing rooms, electroencephalogram testing rooms, and electromyography testing rooms, the Neurology Center strives to provide more specialized care and treatment.'
            ] 
        },
        {cate_no:0, 
            item_no:9, 
            img_src:'9_.jpg', 
            sub_title:['',''], 
            sub_context9: ['Located in the heart of Busan`s downtown Seomyeon district, On Hospital strives to provide high-quality emergency medical services to patients competing for the golden time through its 24-hour Cardiovascular and.'],
            sub_context8: ['In addition, the center operates with a collaborative system of specialized neurovascular and cardiovascular surgical teams to ensure early detection and systematic management of cerebrovascular diseases.'],
            sub_context7: ['The Cardiovascular and Cerebrovascular Center at On Hospital has introduced the Biplane Angio, a state-of-the-art vascular surgery equipment from Philips, which allows for clear and precise visualization of even the smallest veins through 3D imaging and reduces radiation exposure to patients by shortening examination time. The center provides treatment for various diseases, including vascular diseases of the arms and legs, spinal and spinal cord vessels, and central nervous system and cranial diseases such as spinal tumors.'],
            sub_context6: ['As important as treatment, the management methods for the heart, brain, blood vessels, etc. include regular exercise suitable for oneself, moderating salt and oily foods, refraining from overeating and smoking, and especially avoiding chronic diseases such as hypertension, diabetes, and hyperlipidemia.'],
            sub_context5: ['The Cardiovascular Center actively manages risk factors for strokes such as hypertension, diabetes, and smoking through collaboration with internal medicine, and performs tests such as magnetic resonance imaging (MRI) and magnetic resonance angiography (MRA) to examine the brain blood vessels, and examines the vascular condition very accurately and precisely through cerebral angiography via the femoral artery and treats it through interventional radiology.'],
            sub_context4: ['In addition, stroke refers to a condition where brain cells are damaged because nutrients and oxygen-carrying blood do not flow to the brain due to the brain blood vessels being blocked or ruptured. The Center specializes in preventing and treating strokes caused by damage to the part where the blood vessel that supplies blood to the brain is blocked or ruptured.'],
            sub_context3: ['Myocardial infarction is mainly caused by coronary artery sclerosis and is characterized by chest pain that lasts more than a few minutes. The Cardiovascular Center performs tests such as electrocardiograms, 24-hour electrocardiograms, echocardiography, exercise stress tests, CT scans, and MRI scans for patients complaining of chest pain, and if stenosis vessels are discovered through coronary artery angiography, intervention through coronary artery intervention is possible. In case of acute emergency, prompt intervention such as percutaneous coronary intervention and stent insertion is very important within the golden time (2 hours after vascular occlusion).'],
            sub_context2: ['Representative coronary artery diseases of the cardiovascular system such as myocardial infarction and angina, and cerebrovascular diseases such as stroke account for 80% of premature deaths, caused by complications with chronic diseases such as hypertension, diabetes, and hyperlipidemia or from environmental and occupational risk factors.'],
            sub_context1: ['Among the top 10 causes of death from disease in recent years, 7 are chronic diseases, and among them, cardiovascular diseases have the highest incidence. Aging is causing an increase in incidence rates, but in contrast, the fatality rate is decreasing due to the development of many treatment methods. However, the disability rate due to the aftermath of the disease is also on the rise. Appropriate management and treatment can reduce the incidence of the disease, and prompt early response is important in case of acute onset (such as myocardial infarction and stroke), and appropriate procedures and treatments can reduce disability rates.'] },
        {cate_no:0, 
            item_no:10,
            img_src:'10_.jpg', 
            sub_title:['1. Asthma', '2. Atopic Dermatitis', '3. Allergic Rhinitis'], 
            top_text:[
                'Allergy Center', 
                'is a place that specializes in treating diseases caused by hypersensitive immune reactions to various external substances.', 
                'Allergic reactions include respiratory allergies such as asthma, allergic rhinitis, and chronic cough, as well as skin allergies such as atopic dermatitis, urticaria, and angioedema. It also includes anaphylaxis, eosinophilic disorders, food, drug, bee sting, exercise allergies, and various complex symptoms.'
            ],
            sub_context1: [
                'The airways of asthma patients are sensitive and easily irritated. When irritated, the inside of the airways become swollen and produce mucus, and the muscles surrounding the airways contract, making the airways narrow. This narrowing of the airways can cause symptoms such as coughing, chest tightness, difficulty breathing, and wheezing.', 
                'Risk factors that contribute to asthma exacerbation include dust mites, pets, cockroaches, mold, pollen, respiratory infections such as colds and pneumonia, direct or indirect smoking, and indoor and outdoor air pollution. Symptoms of asthma include coughing or wheezing sounds that do not easily disappear and often recur. In some cases, breathing difficulty or coughing becomes severe during exercise and cannot continue.', 
                'To successfully manage asthma, it is essential to use prescribed medications regularly and accurately. Based on test results, each asthma patient undergoes individualized treatment such as medication and immunotherapy according to the severity and causes and triggering factors.',
                'It is a chronic and recurrent skin inflammation that mainly occurs in infants and children, characterized by itchy and distinctive distribution and appearance of skin lesions.', 
                'Itching is the most characteristic symptom, which is severe mainly in the early evening or at night, causing the baby to scratch the bedding or bedclothes continuously, resulting in blisters and scabs on the skin, and frequent secondary bacterial infections.',
                'Dry skin, infections, rough clothing, house dust mites, synthetic fibers and wool, and heat can exacerbate the itching of atopic dermatitis.',
                'Bathing is necessary to prevent skin infections and provide adequate skin moisturization, and if necessary, soap with moisturizing effects should be used.',
                'After bathing, apply enough moisturizer, keep your nails short, and make sure your hands do not touch your face. Soft cotton clothes are preferred, and wool should be avoided, and creating an environment without house dust mites can also be helpful.',
                'Suspected foods should be restricted, but random restrictions can lead to severe nutritional deficiencies, so only restrict the foods recommended by the doctor after examination.',
                'After exposure to an allergen, the mucous membrane of the nose undergoes an allergic inflammatory response in the stimulated area, causing allergic rhinitis.',
                'The main symptoms are consecutive sneezing, clear runny nose, nasal congestion, and itching.',
                'Sneezing and runny nose may improve in the afternoon after being severe in the morning. In addition, there may be itching and congestion around the eyes, headache, and decreased sense of smell.',
                'Common allergens include house dust mites, pet hair, food, and medication.',
                'In seasons, tree pollen, such as oak and birch, can be the cause in spring, and weed pollen, such as mugwort and pigweed, in autumn.',
                'Avoiding allergens is the most effective treatment, but it is practically difficult to avoid house dust mites and pollen. Therefore, it is necessary to control symptoms with appropriate medication and consider immunotherapy as a fundamental treatment.'
            ] 
        },
        {cate_no:0, 
            item_no:11,
            sub_title:['',''], 
             img_src:'11_.jpg', },
        {cate_no:0, 
            item_no:12,
             img_src:'12_.jpg', 
             sub_title:['Women`s Cancer Center',''], 
             sub_context2: ['Cervical cancer', 'Abnormal uterine bleeding', 'Menstrual irregularities', 'Cervical cancer vaccination'],
             sub_context1: ['Treatment of uterine fibroids and ovarian diseases', 'Endometriosis treatment', 'Specialized treatment for women`s health issues'] },
        {cate_no:0, 
            item_no:13,
             img_src:'13_.jpg', 
             sub_title:['INTRODUCTION', 'SPECIALIZED CLINICS'],
             sub_context4:['Breast Cancer Clinic, Endoscopic Breast Surgery Clinic'], 
             sub_context3:['To maintain our excellent level of care, we consistently conduct educational activities, including breast cancer support groups and nurse meetings.'],
             sub_context2:[
                'The Breast Center at ON Hospital`s most significant feature is its treatment methods that preserve the most beautiful breast after breast cancer surgery.', 
                'We perform minimally invasive surgeries with the highest level of breast conservation and minimal lymph node surgery using sentinel lymph node biopsy, endoscopic breast cancer surgery, and wide or breast resection when necessary. In addition, we perform cosmetic surgeries such as latissimus dorsi flap surgery or prosthetic implant surgery to achieve the best possible aesthetic outcome.'
            ],
             sub_context1: [
                'The Breast Center at ON Hospital specializes in the diagnosis and treatment of breast cancer and other breast diseases, which are the most common cancer among women worldwide and also the most prevalent cancer in women in Korea.', 
                'Breast cancer can be detected early, and if diagnosed early, the cure rate is up to 90%, making early screening crucial.', 
                'Our center is equipped with the latest breast imaging and ultrasound machines, essential for early screening. We also have various tools and equipment for tissue testing without surgery. ', 
                'Additionally, specialized nurses in the Breast Cancer Center provide psychological and rehabilitation education to improve the quality of life for breast cancer patients.'
            ] 
        },
        {cate_no:0, 
            item_no:14,
             img_src:'women_.png', 
             sub_title:['Breast and Thyroid Cancer Center',''], 
             chk_text:['One-stop medical service', 'Top medical staff', 'Treatment with the latest equipment'],
             middle_text:['From screening to reconstruction!', 'Mammotome tissue examination'],
             circle_text:['Surgery', 'Cancer treatment', 'Radiation therapy'],
             blue_text:'Available non-stop',
             sub_context1: ['Mammotome procedure: The latest technology that uses a thick needle to divide and remove various lumps or abnormal areas without causing incisions', '051) 607-0232'] },
        {cate_no:0, 
            item_no:15,
            sub_title:['',''], 
             img_src:'emergency.png' },
        {cate_no:0, 
            item_no:16,
             img_src:'16_.jpg', 
             sub_title:['Newest Hemodialysis Machines with High Satisfaction!',''], 
             phone_num:['Nephrology Department','(2F)', 'Artificial Kidney Surgery','(13F)'],
             phone_text:['051) 607-0209', '051) 607-0128,0020'],
             chk_text: ['The most comfortable hotel-like facilities in Busan!', '60 state-of-the-art dialysis machines!', 'Germany FMC 5008S 4.5V'] },
        {cate_no:0, 
            item_no:17,
             img_src:'17_.jpg', 
             sub_title:['Possible procedures',''], 
             chk_text:[
                'Clinic hours: Mon-Fri (closed on Saturdays)', 
                'Inquiries: 051-607-0281, 0229', 
                'Please note that clinic hours are subject to change, and all procedures require advance reservation. Please call to make an appointment before visiting.'
            ],
             top_text:['Intervention, also known as interventional therapy, is an advanced medical field that uses real-time imaging techniques such as fluoroscopy or ultrasound to create a path to the diseased area using a thin needle or catheter with a diameter of about 1-2mm, and treats the disease through it. Compared to traditional treatment methods, it minimizes patient risks as it does not require general anesthesia or skin incisions.'],
             sub_context1: [
                'Chemotherapy for hepatic artery cancer', 
                'Treatment for peripheral arterial disease', 
                'Vascular reconstruction for hemodialysis arteriovenous fistulas', 
                'Cholecystectomy', 
                'Percutaneous nephrolithotomy, percutaneous renal biopsy', 
                'Central venous catheterization (POCC, anticancer port insertion)', 
                'Tissue biopsy (ultrasound or CT-guided)', 
                'Endometrial ablation for uterine fibroids', 
                'Transurethral resection of the prostate for benign prostatic hyperplasia', 
                'Sclerotherapy for cysts', 
                'Pelvic congestion syndrome', 
                'Varicocele', 
                'Stent insertion for esophageal, gastric, and duodenal stenosis'
            ] 
        },
        {cate_no:0, 
            item_no:18,
             sub_title:['',''], 
             link:['https://bryonsilver.github.io/ON_Hospital/on_hospital/medi_center.html?cen_v=13'],},
        {cate_no:0, 
            item_no:19,
             img_src:'19_.jpg', 
             sub_title:['',''], 
             sub_context4: ['In addition, diagnostic facilities such as electromyography rooms, gait and motion analysis rooms, bio-dex rooms, and nerve conduction study rooms enable accurate diagnosis and treatment. Furthermore, specialized pain treatments such as IMS therapy and taping therapy are also provided.'],
             sub_context3: ['Facilities include exercise therapy rooms, physical therapy rooms, hydrotherapy rooms, occupational therapy rooms, as well as special facilities for specific treatments such as Vojta therapy, Bobath therapy, prosthetics/orthotics clinic, spasticity clinic, and frozen shoulder clinic.'],
             sub_context2: ['Various specialized treatments are provided for specific areas such as stroke, spinal cord injury, traumatic brain injury, pain, prosthetics and orthotics, electrodiagnosis, pediatric rehabilitation, and physical and biomechanical therapy.'],
             sub_context1: ['The Rehabilitation Therapy Center is a specialized treatment center that evaluates and treats individuals with functional impairments to maximize their physical, mental, and social abilities, as well as their potential for hobbies, occupations, and education, enabling them to live as close to a normal life as possible under the given conditions.'] },
        {cate_no:0, 
            item_no:20,
             img_src:'20_.jpg', 
             sub_title:['INTRODUCTION','SPECIALIZED CLINICS'], 
             sub_context3: [
                'Urological Tumor Clinic, Urinary Stone Clinic, Urinary Incontinence Clinic, Pediatric Urology Clinic', 
                'Bladder Surgery, Laparoscopic Surgery, Endoscopic Surgery, Urological Trauma Clinic, Urinary Tract Infection Clinic'
            ],
             sub_context2: ['ON Hospital`s Men`s Center is led by a team of specialized medical professionals, including clinical professors from university hospitals. They operate various specialized clinics and play a leading role in each field, striving to provide international-level medical care.'],
             sub_context1: [
                'The Prostate and Urinary Dysfunction Center at ON Hospital was established to provide specialized diagnosis and treatment for male urinary and reproductive system disorders.',
                'The center deals with diseases such as urological tumors, urinary stones, urinary incontinence, pediatric urology, neurogenic bladder, male medicine, urological trauma, and urinary tract infections.'
            ]  
        },
        {cate_no:0, 
            item_no:21,
             img_src:'21_.jpg', 
             sub_title:['Prostate Cancer Center', 'Led by professors specialized in the field of medicine', 'Holmium YAG laser surgical equipment'], 
             check_box:['Hematuria Center', 'Urinary Incontinence Clinic', 'Prostate Cancer'],
             small_title:'Features',
             special:[
                '① Removal of stones that are difficult to remove with extracorporeal shock wave lithotripsy',
                '② One-time treatment is possible',
                '③ Shorter recovery period after treatment'
            ],
             sub_context1: ['Holmium YAG laser surgical equipment that is safe and effective in removing prostate hypertrophy tissue, a new treatment for prostate hypertrophy called Holmium Laser Enucleation of the Prostate (HoLEP)'] },
        {cate_no:0, 
            item_no:22,
             img_src:'22_.jpg', 
             sub_title:[
                'With cooperation among departments of orthopedics, neurosurgery, rehabilitation medicine, and anesthesia pain medicine, ', 
                'the center provides total care where diagnosis, surgery, and rehabilitation are carried out as one to address ', 
                'the difficulty of patients in choosing the right medical department and provide comprehensive treatment'
            ], 
             circle_num:['01','02','03','04','05','06','07','08','09'],
             circle_text:[
                'Minimally invasive endoscopic microscopic surgery is performed', 
                'Minimally invasive arthroscopic surgery is performed without blood loss', 
                'Short surgery time and fast recovery', 
                'Minimization of post-anesthetic aftereffects through local anesthesia', 
                'Latest spine and joint rehabilitation exercise center', 
                'Scientific exercise prescription program using the latest equipment', 
                'Personalized exercise prescription program with 1:1 expert consultation', 
                'Spine and joint strengthening program', 
                'Post-surgical relapse prevention program'
            ],
             sub_context1: [
                'Arthroscopic surgery is possible with accurate diagnosis and treatment since only 3-4 small holes are created around the joint, allowing direct observation through a miniaturized microscope.', 
                'In addition, it leaves almost no unsightly scars and allows for a quick return to daily life. Not only for partial tears of rotator cuffs, shoulder joint dislocation, calcific tendinitis, joint ligament injuries, but also for severe rotator cuff tears, minimally invasive surgery using arthroscopy is possible.'
            ] },
        {cate_no:0, 
            item_no:23,
             img_src:'23_.jpg', 
             sub_title:['What is ultrasound diagnosis?', 'Advantages of musculoskeletal ultrasound examination'], 
             small_top:[
                'Ultrasound diagnosis is a treatment method that repairs and strengthens ligament damage in the spine or joint areas.',
                'The musculoskeletal system includes muscles, ligaments, cartilage, bones, and related nerves or blood vessels, and ultrasound examinations of these are called musculoskeletal ultrasound. It can quickly and easily confirm inflammation, damage, and degenerative changes in joints, ligaments, and more.'
            ],
             sub_context1: [
                'It is a non-invasive examination that does not require injections or incisions and usually causes little pain.',
                'It can be performed when X-ray or other radiation tests are difficult to confirm and is harmless to the body as there is no need for radiation exposure.',
                'It is considered safe for both pregnant women and fetuses.',
                'It is a helpful examination that assists in procedures such as tissue examinations by providing real-time images.',
                'It can be applied to a wide range of areas, is easy to use, and generally costs less than other tests such as CT or MRI.'
            ] },
        {cate_no:0, 
            item_no:24,
             img_src:'24_.jpg', 
             sub_title:[
                'Increasing Trend in Pancreatic and Biliary Diseases, What are the Causes?',
                'Why is the survival rate for pancreatic and bile duct cancer low?', 
                'Treatment for pancreatic and bile duct diseases', 
                'Pancreatic and Biliary Tract Diseases', 
                'Diagnosis of Pancreatic and Biliary Tract Diseases'
            ], 
             bold_top: [
                'Diagnosis and Treatment of Pancreatic and Biliary Diseases', 
                'Endoscopic Ultrasound (EUS)',
                'Endoscopic Retrograde Cholangiopancreatography (ERCP)'
            ],
             sub_context5: [
                '1. EUS (Endoscopic Ultrasound)- A revolutionary turning point in the early detection of pancreaticobiliary diseases',
                'A technique that uses high-resolution imaging and various techniques to access the closest area of the gallbladder, bile duct, and pancreas through the duodenum using ultrasound attached to the end of the endoscope for early and accurate diagnosis. There is no exposure to radiation, and real-time tissue and cell sampling can be performed during the examination, allowing simultaneous pathological confirmation. It is the most suitable method for the early detection of pancreatic cancer of less than 1 cm and for diagnosing pancreatic duct cancer with revolutionary diagnostic techniques as it allows for both examination and tissue sampling',
                '2. ERCP (Endoscopic Retrograde Cholangiopancreatography)-Simultaneous diagnosis and treatment, high-difficulty endoscopic procedure',
                'A high-difficulty procedure that uses a special endoscope called the duodenoscope to access the duodenal papilla, where the pancreatic duct and bile duct meet, and then captures images of the pancreatic and bile ducts to make an accurate diagnosis. If a lesion is detected, real-time removal of gallstones, bile duct drainage, pancreatic duct stone removal, and pancreatic duct drainage can be performed.'
            ],
             sub_context4: [
                'Both diseases can be cured through surgical removal if detected early. However, with an early diagnosis rate of less than 20%, and even if the patient is a surgical candidate, elderly or those with underlying diseases hesitate to undergo surgery if extensive liver resection or multiple organ removal is required, especially because the recurrence rate after surgery is very high, and the 5-year survival rate is less than 5%, indicating a poor prognosis. Therefore, regular monitoring and testing for pancreatic and biliary diseases are crucial for early diagnosis and lesion detection.',
                'For patients with inoperable gallbladder and bile duct cancer, bile duct drainage and anti-cancer treatment are carried out as bile duct obstruction is a necessary accompanying condition.',
                'In some cases, localized lesions can be eliminated through regional chemotherapy to maintain bile duct drainage for a longer time and improve prognosis with periodic anti-cancer treatment.'],
             sub_context3: [
                'Both diseases can be cured through surgical resection if detected early, but the early detection rate is less than 20%. Even if surgery is indicated, extensive liver resection or multi-organ resection may be necessary, causing elderly or comorbid patients to hesitate to undergo surgery. In particular, the high recurrence rate after surgery results in a poor prognosis with a five-year survival rate of less than 5%. Therefore, regular management is necessary for pancreatic and bile duct examinations and lesion detection for early diagnosis.',
                'In cases where surgery is not possible for gallbladder and bile duct cancer, biliary drainage and chemotherapy are performed concurrently because biliary obstruction is essential. In some patients, the local lesion can be eliminated through wide-field dynamic therapy, which maintains biliary drainage for a longer period and improves the prognosis through periodic chemotherapy.'],
             sub_context2: [
                'The main reason is the difficulty of early detection, which correlates with the difficulty of achieving a cure through surgery. The pancreas and bile ducts are located deep within the body, making it difficult to detect abnormalities early on through common diagnostic techniques such as blood tests and abdominal ultrasounds. Additionally, due to the nature of these organs, symptoms typically do not appear until the disease has progressed significantly, leading many individuals to believe they are healthy until the disease has already advanced considerably. Although the widespread use of diagnostic tools such as CT and MRI has increased diagnostic rates, the early detection rate is still less than 20%, and the five-year survival rate is extremely poor at less than 5%.',
                'Recently, the proliferation of endoscopic ultrasound (EUS) has made it possible to detect small pancreatic tumors less than 1cm in size early on, which is expected to contribute to a revolutionary improvement in the prognosis for pancreatic and bile duct cancer.'],
             sub_context1: [
                'Pancreatic cancer, although ranking 9th in incidence rate in Korea as of 2018, is a relatively common disease ranking within the top 3 in the United States. The incidence of pancreatic cancer is gradually increasing in Korea, and the main causes are excessive intake of fat and protein due to Westernized eating habits, as well as an unexplained increase in pancreatic cysts. Excessive intake of fatty foods can cause damage to pancreatic duct cells and pancreatic enzyme-secreting cells, leading to malignant tumors through genetic mutations.', 
                'Meanwhile, mucinous pancreatic cysts have a high potential for malignancy as time goes by after onset, but if detected early and thoroughly tracked, there is a higher chance of complete recovery even if pancreatic cancer develops. Biliary tract cancer has a high incidence rate, especially in the Busan, Ulsan, and Gyeongsangnam-do regions, due to infection with Clonorchis sinensis, which can lead to biliary tract cancer after an infection acquired by eating raw freshwater fish repeatedly.'] },
        {cate_no:0, 
            item_no:25,
             img_src:'page-img10.jpg', 
             sub_title:['INTRODUCTION', 'SPECIALIZED CLINICS'], 
             pro_context5:'교정발치, 빠른 교정을 위한 피질골절단술, 구개확장, 매복치의 SURGERY적노출, 골신장술',
             pro_context4:'구순구개열, 안면기형',
             pro_context3:'안면골절, 외상 후 부정교합, 외상 후 치아/치조골 재건술(임플란트)',
             pro_context2:'사각턱, 돌출입수술, 무턱, 귀족수술, 턱끝성형술',
             pro_context1:['양악수술, 하악수술, 주걱턱, 안면비대칭, 긴얼굴, 잇몸노출증, 개교합, 무턱','(술전교정수술, 최소교정수술, 선수술, 무교정수술)'],
             pro_title:['턱교정(악교정)클리닉','얼굴윤곽클리닉','악안면외상클리닉','안면기형클리닉','구강악안면SURGERY'],
             sub_context5:['기존의 술전교정(1년이상)/ 수술/술후 교정(6개월)으로 이루어지던 약 2년의 치료기간이 걸리던 것과 달리 선수술은 수술을 먼저 시행하고 수술 후 교정을 시행하는 것으로 그 치료기간이 6개월에서 1년 정도 단축되는 것이 가장 큰 장점이라 할 수 있습니다.'],
             sub_context4:['정확한 치아와 골격의 분석을 통하여 선수술이 가능한 환자는 수술을 먼저 시행하거나 최소교정 후 수술을 시행하여 술전교정 기간 중 교정으로 인한 불편감과 전체치료기간을 줄였습니다. 기존의 치료가 약 2년의 치료기간(술전교정[1년이상] / 수술 / 술후 교정[6개월])인 것과 달리 선수술은은 수술을 먼저 시행하고 수술 후 교정을 시행하는 것으로 그 치료기간이 6개월에서 1년 정도 단축되는 것이 가장 큰 장점이라 할 수 있습니다.'],
             sub_context3:['ON Hospital 턱ㆍ얼굴(악안면)수술센터는 최신의 장비를 이용하여 수술전 분석(2D cephalometry/3D CT/model 분석)을 시행하여 환자 개인에 맞는 최상의 수술계획을 수립하고 있습니다.'],
             sub_context2:['환자중심의 CENTERS One-stop/ One-way(외래/수술준비/입원/수술)시스템 및 턱ㆍ얼굴(악안면)수술환자을 위한 1인실/2인실 입원시스템 그리고 복잡한 과정(접수/대기/반복내원)을 줄여 불편감을 최소로 하였습니다.'],
             sub_context1: ['ON Hospital MAXILLOFACIAL SURGERY는 최고 수준의 진료를 제공하기 위하여 구강악안면SURGERY 의료진을 중심으로 OTOLARYNGOLOGY 전문의, 마취통증 의학과 전문의 등 체계화된 협진체제로 구성되어 정확한 평가와 치료와 수술 후 최상의 결과를 제공하고 있다.']},
        {cate_no:0, 
            item_no:26,
             img_src:'26_.jpg', 
             sub_title:['', 'SPECIALTY'], 
             sub_context2: ['암수술/폐·흉부종양의 흉강 내시경 수술','다한증(손발겨드랑이 다한증 및 겨드랑이 땀냄새)의 수술 및 비수술적 치료','기흉/하지 정맥류/누두흉(오목가슴)등의 흉벽기형'],
             sub_context1: ['심장, 폐 기관, 식도, 대동맥 등 생명 유지에 기본이 되는 중요 장기의 질환 진단 및 수술', '부산.경남 최초 흉강경이용 폐엽절제술 성공']},
        {cate_no:0, 
            item_no:27,
             img_src:'27_.jpg', 
             sub_title:['INTRODUCTION', 'SPECIALIZED CLINICS'], 
             bold:'항암 방사선 치료',
             sub_context5: ['- ON Hospital 방사선 치료 안내.pdf', '다운로드'],
             sub_context4: ['단순히 방사선을 쬐는 것만으로는 방사선 치료가 이루어지는 것은 아닙니다.','종양의 크기, 퍼진 정도, 형태와 분화도 및 종양의 방사선에 대한 민감도 등을 모두 감안하여 방사선량, 치료기간 등이 결정되며, 여기에 환자의 건강상태 등도 고려되어야 합니다.', '따라서 방사선 치료를 위해서는 숙련된 의료진과 진단장비 및 첨단 방사선치료기기가 필수적이며, 아울러 질환에 적합한 치료 기법을 선택할 수 있도록 다양한 치료기법을 시행 할 수 있는지도 고려 되어져야하고, 정상세포에 대한 영향을 최소화 하기 위해 고도의 기술적 축적이 요구 됩니다.'],
             sub_context3: ['방사선치료기법의 발전으로 인체 암에 대해 방사선을 조사할 때 과거에 비하여 종양주변 정상조직에는 방사선을 크게 줄이고, 종양조직에만 고선량의 방사선을 조사 할 수 있게 되었으며, 이로 인하여 방사선치료와 연관 된 합병증은 낮게 유지하면서 종양에 대한 제어율을 크게 높아졌습니다. ',' 이와 같은 방사선 치료 선진국에서 전체 암 환자의 60%가 방사선치료를 받을 정도로 방사선치료가 암 치료에 지대한 역할을 담당하고 있습니다.'],
             sub_context2: ['방사선 치료는 방사선이 발생되는 장치(라이낙 치료기)혹은 방사선 동위원소를 이용하여 고에너지 방사선을 조사하여 암세포를 죽이는 치료법입니다.','방사선 치료에 사용되는 방사선은 파장이 매우 짧고 높은 에너지를 갖고 있으며, 인체에 조사될 경우 핵산에 변성을 초래하여 종양 세포를 죽이게 되며, 암세포에 집중적으로 방사선을 조사하면 암세포를 파괴하고 더 이상 증식되는 것을 막아줍니다.','이 경우 주변의 정상 세포도 방사선의 영향을 받지만 정상세포는 종양세포보다 빠르게 회복되는 잇점과 대부분의 손상이 빠르게 회복되어 영향을 최소화 할 수 있습니다. 방사선은 암세포처럼 빠르게 증식하는 조직에 대하여 파괴 효과가 높기 때문입니다.'],
             sub_context1: ['항암 방사선 치료센터는 방사선을 이용하여 환자를 치료하는 임상의학의 한 방법으로, 수술, 항암 화학 요법과 더불어 3대 암 치료 중 하나입니다.']  },
        {cate_no:0, 
            item_no:28,
             img_src:'28_.jpg', 
             sub_title:['"ON Hospital 호스피스 완화의료병동은 이렇게 운영 됩니다."', '호스피스 완화의료에 대한 오해와 진실'], 
             top_small:'호스피스 완화의료 서비스는 `포기`가 아닌 적극적인 `치료와 돌봄`으로 말기 암 환자의 신체적 증상을 조절하고 환자와 가족의 심리사회적, 영적 어려움을 도와 삶의 질을 향상시키는 것을 목표로 하는 의료서비스입니다.',
             top_li:['보건복지부 지정 호스피스 완화의료 병동 운영', '말기 암 환자를 대상으로 입원형 호스피스 운영', '본인부담 5%으로 최저비용, 최고효율 효과! 의료도우미 제공!', '최고의 시설, 쾌적한 환경의 임원병동 운영'],
             main_title:['호스피스 완화의료는 삶을 포기하고, 죽음을 기다리는 것이다?', '호스피스 완화의료 기관에서는 아무것도 하는 게 없다?', '호스피스 완화의료 기관에서는 가족과 함께 지낼 수 없다?', '호스피스 완화의료는 비용이 비싸다?'],
             main_num:['1', '2', '3', '4'],
             main_red_text:'NO! 아닙니다!',
             sub_context4: ['건강보험이 적용되어 암환자는 본인 부담 5%만 적용됩니다.', '다만, 상급병실료나 특진비 등 Billing and Insurance 항목은 일부의 비용을 부담할 수 있습니다.'] ,
             sub_context3: ['가족이 함께 지낼 수 있으며, 가족의 심리적, 사회적 어려움에 대해서도 도움을 받으실 수 있습니다.'] ,
             sub_context2: ['환자가 겪고 있는 통증, 섬망 등의 증상에 대해 완화전문 의료진으로 부터 통증관리 및 증상을 조절하고 삶을 의미 있게 보내실 수 있도록 심리치료, 마사지, 음악요법, 미술요법 등 다양한 프로그램을 제공하고 있습니다.'] ,
             sub_context1: ['통증, 구토, 호흡곤란, 복수 등의 신체적 증상을 적극적으로 치료하고 심리적, 사회적, 영적인 어려움을 도와드리기 위해 각 분야의 전문가가 팀을 이루어 삶의 질 향상을 목표로 하는 의료서비스입니다.', '증상조절이 되면 퇴원 후 일상생활을 할 수 있습니다.'] },
        {cate_no:0, 
            item_no:29,
             img_src:'', 
             sub_title:['#안전한 병원치료#음압시스템#유기적인 협진시스템'], 
             circle_border:'교수출신 호흡기·알레르기·결핵',
             circle_text:['폐렴', '폐암', '만성 폐쇄성 폐질환 COPD'],
             sub_context3:['주요 진료 분야는 만성 폐쇄성 폐질환, 기관지 천식, 폐암, 폐렴, 폐결핵, 만성기침, 기관지 확장증, 간질성 폐 질환, 호흡부전, 흉막 질환(기흉, 흉막염, 흉수, 농흉), 식도암, 종격동 종양, 다한증, 오목가슴, 기관 협착 등이며 폐암 진단 시 정기적이고 지속적인 관리를 해드립니다. 저희 Respiratory 의료진 모두는 환자분들 편에 서서 여러분의 고통을 해결해 드리기 위해 최선을 다할 것으로 약속드립니다.'],
             sub_context2:['Respiratory는 DEPARTMENT OF <SPAN>RESPIRATORY MEDICINE</SPAN>와 THORACIC SURGERY로 구서오디어 있어 질병의 정확한 진단, 치료 및 수술까지 빠르고 정확하게 진료할 수 있습니다.', '또한 관련 DEPARTMENT와 협진을 통해 여러 분야의 전문의들이 모여 환자 중심의 진료를 받을 수 있습니다.'],
             sub_context1: ['우리 사회의 고령화 추세가 높아지면서 호흡기계 중증 질환자의 수가 급격하게 증가하고 있습니다.','이처럼 호흡기계 질환자의 증가에 따라 효율적인 진료를 위해 Respiratory를 개설, 운영하고 있습니다.'] },
    ]
]

const CENT_TITLE = [
    [
        {cate_no:0, item_no:1, title:'Hepatobiliary Pancreatic / Gastric / Colorectal Cancer', icon_src:'medi_w_cetner_1', name:'간담췌외과 위 대장암'},
        {cate_no:0, item_no:2, title:'Liver', icon_src:'medi_w_cetner_2', name:'간센터'},
        {cate_no:0, item_no:3, title:'Infection', icon_src:'medi_w_cetner_3', name:'감염센터'},
        {cate_no:0, item_no:4, title:'Proctology', icon_src:'medi_w_cetner_4', name:'대장항문센터'},
        {cate_no:0, item_no:5, title:'Child and Adolescent <br>Mental Health Center', icon_src:'medi_w_cetner_5', name:'소아청소년 정신건강센터'},
        {cate_no:0, item_no:6, title:'Gastrointestinal <br>Nerve Center', icon_src:'medi_w_cetner_6', name:'소화내시경센터'},
        {cate_no:0, item_no:7, title:'Digestive Cancer <br>Surgery Center', icon_src:'medi_w_cetner_7', name:'소화기암수술센터'},
        {cate_no:0, item_no:8, title:'Neurology Center', icon_src:'medi_w_cetner_8', name:'신경센터'},
        {cate_no:0, item_no:9, title:'Cardiovascular Center', icon_src:'medi_w_cetner_9', name:'심뇌혈관센터'},
        {cate_no:0, item_no:10, title:'Allergy Center', icon_src:'medi_w_cetner_10', name:'알레르기 센터'},
        {cate_no:0, item_no:11, title:'Rehabilitation Program', icon_src:'medi_w_cetner_11', name:'암재활프로그램'},
        {cate_no:0, item_no:12, title:'Women`s Cancer', icon_src:'medi_w_cetner_12', name:'여성암센터'},
        {cate_no:0, item_no:13, title:'Breast and Thyroid Cancer Center', icon_src:'medi_w_cetner_14', name:'유방 갑상선암 센터'},
        {cate_no:0, item_no:14, title:'Breast Cancer Center', icon_src:'medi_w_cetner_14', name:'유방암센터'},
        {cate_no:0, item_no:15, title:'Emergency Medical Center', icon_src:'medi_w_cetner_15', name:'응급의료센터'},
        {cate_no:0, item_no:16, title:'Renal Care Center', icon_src:'medi_w_cetner_16', name:'인공신장센터'},
        {cate_no:0, item_no:17, title:'Intreventional Surgery', icon_src:'medi_w_cetner_17', name:'인터벤션센터'},
        {cate_no:0, item_no:18, title:'Funeral Home/Mortuary', icon_src:'medi_w_cetner_18', name:'장례식장'},
        {cate_no:0, item_no:19, title:'Rehabilitation Therapy Center', icon_src:'medi_w_cetner_19', name:'재활치료센터'},
        {cate_no:0, item_no:20, title:'Prostate and Urinary Dysfunction Center', icon_src:'medi_w_cetner_20', name:'전립선 배뇨장애 센터'},
        {cate_no:0, item_no:21, title:'Prostate Cancer Center', icon_src:'medi_w_cetner_21', name:'전립선암센터'},
        {cate_no:0, item_no:22, title:'Spondyloarthropathy', icon_src:'medi_w_cetner_22', name:'척추관절센터'},
        {cate_no:0, item_no:23, title:'Ultrasound Diagnostic Center', icon_src:'medi_w_cetner_23', name:'초음파진단센터'},
        {cate_no:0, item_no:24, title:'Pancreatic Duct Center', icon_src:'medi_w_cetner_24', name:'췌장담도센터'},
        {cate_no:0, item_no:25, title:'Maxillofacial Surgery', icon_src:'medi_w_cetner_25', name:'턱얼굴수술센터'},
        {cate_no:0, item_no:26, title:'Lung Cancer', icon_src:'medi_w_cetner_26', name:'폐암수술센터'},
        {cate_no:0, item_no:27, title:'Chemotherapy Radiation', icon_src:'medi_w_cetner_27', name:'항암방사선치료센터'},
        {cate_no:0, item_no:28, title:'Hospice & Palliative Care', icon_src:'medi_w_cetner_28', name:'호스피스완화의료병동'},
        {cate_no:0, item_no:29, title:'Respiratory', icon_src:'medi_w_cetner_29', name:'호흡기센터'},
    ]
]
const HOSPI_TITLE = [
    [
        {cate_no:0, item_no:1, title:'Liver'},
        {cate_no:0, item_no:5, title:'Gastrointestinal Cancer Surgery'},
        {cate_no:0, item_no:10, title:'Women`s Cancer'},
        {cate_no:0, item_no:11, title:'Breast/Thyroid Cancer'},
        {cate_no:0, item_no:15, title:'Intreventional Surgery'},
        {cate_no:0, item_no:18, title:'Prostate Cancer'},
        {cate_no:0, item_no:24, title:'Lung Cancer'},
        {cate_no:0, item_no:25, title:'Chemotherapy Radiation'},
    ]
]
const LIST_N = [
    [
        {cate_no:0, item_no:1, name:''},
        {cate_no:0, item_no:1, name:''},
        {cate_no:0, item_no:2, name:'3'},
        {cate_no:0, item_no:3, name:'4'},
        {cate_no:0, item_no:4, name:'5'},
        {cate_no:0, item_no:5, name:'6'},
        {cate_no:0, item_no:6, name:'7'},
        {cate_no:0, item_no:7, name:'8'},
        {cate_no:0, item_no:8, name:'9'},
        {cate_no:0, item_no:9, name:'10'},
        {cate_no:0, item_no:10, name:'11'},
        {cate_no:0, item_no:11, name:'12'},
        {cate_no:0, item_no:12, name:'13'},
        {cate_no:0, item_no:13, name:'14'},
        {cate_no:0, item_no:14, name:'15'},
        {cate_no:0, item_no:15, name:'16'},
        {cate_no:0, item_no:16, name:'17'},
        {cate_no:0, item_no:17, name:'18'},
        {cate_no:0, item_no:18, name:'19'},
        {cate_no:0, item_no:19, name:'20'},
        {cate_no:0, item_no:20, name:'21'},
        {cate_no:0, item_no:21, name:'22'},
        {cate_no:0, item_no:22, name:'23'},
        {cate_no:0, item_no:23, name:'24'},
        {cate_no:0, item_no:24, name:'25'},
        {cate_no:0, item_no:25, name:'26'},
        {cate_no:0, item_no:26, name:'27'},
        {cate_no:0, item_no:27, name:'28'},
        {cate_no:0, item_no:28, name:'29'},
    ]
]


const CENT_BANNER = [
    [{}]
]

